### ISSUE TITLE
convert2html.rb: "wrong number of arguments (given 3, expected 2)"

### ISSUE THREAD

**Issue by cstrobbe** [BIK-BITV/BIK-Web-Test#1]
Ich versuche mit dem Skript `convert2html.rb` die AsciiDoc-Dateien in HTML-Dateien zu konvertieren. Ich habe Ruby 2.3.3p222, asciidoctor und ruby-cmdparse (`sudo apt-get install ruby-full` und `sudo apt-get install asciidoctor ruby-cmdparse`). Wenn ich das Skript ausführen will (`ruby convert2html.rb ...`), bekomme ich immer die gleiche Fehlermeldung:

```
/usr/lib/ruby/2.3.0/optparse.rb:1621:in `[]=': wrong number of arguments (given 3, expected 2) (ArgumentError)
	from /usr/lib/ruby/2.3.0/optparse.rb:1621:in `permute!'
	from /usr/lib/ruby/2.3.0/optparse.rb:1642:in `parse!'
	from ./convert2htm.rb:13:in `<main>'
```

Diese Fehlermeldung erscheint unabhängig von der Zahl der Parameter, die ich dem Skript übergebe (0, 1, 2, ...). Wie kann ich das Skript ausführen, damit die Konvertierung gelingt?

**Comment by helmsaccess** [comment]
Hallo,

das Script habe ich nur unter Windows getestet, sollte allerdings auch unter anderen Systemen laufen. Vielleicht ist es ein Problem der Ruby Version, ich habe hier Version 2.7 installiert. Zusätzlich wird das Asciidoctor GEM-Paket in Version 2.0.10 benötigt.

Das Script benötigt keine Parameter, es erstellt einfach einen HTML-Ordner mit den ganzen Prüfschritten. Will man HTML-Dateien mit Header-Informationen erstellen (Standalone), kann man den Parameter „-s“ anfügen.

Unter Windows rufe ich das Script entsprechend folgendermaßen auf:
„ruby convert2html.rb“ bzw. „ruby convert2html.rb –s„

Viele Grüße
Emanuel Helms

**Comment by cstrobbe** [comment]
Okay, das Problem liegt offensichtlich an den alten Packages für MX Linux 18.3 (ruby 2.3.3p222 und asciidoctor 1.5.4-2). Mit den rezenteren Versionen, die unter Ubuntu 18.04 vorhanden sind, funktioniert es.
