### ISSUE TITLE
12.2.2 Technischer Support

### ISSUE THREAD

**Issue by pp-ernst** [BIK-BITV/BIK-Web-Test#172]
Der Prüfschritt kann nicht immer anwendbar sein, da nicht bei jedem Webauftritt Support angeboten wird.

**Comment by johannesFischer84** [comment]
Genau, laut Anhang C bzw. der Pre-Condition in der EN wäre die Prüfung anwenbar, wenn ein Unterstützungsdienst (Support) angeboten wird.

**Comment by detlevhfischer** [comment]
Richtig, es gab hierzu schon einen Pull request #158 , den ich jetzt gemergt habe. @pp-ernst, danke für den Hinweis!

**Comment by MarcHaunschild** [comment]
>Verbreitet sollten jedoch Assistenzsysteme sein, die den Support-Mitarbeiter durch die Problemlösung führt.

Diesen Satz verstehe ich sprachlich nicht. Was ist hier gemeint? Zusammen mit dem folgenden Satz glaube ich erraten zu können, dass es kaum möglich ist, eine Prüfung der Unterlagen durchzuführen, wenn die Mitarbeiter ein Assistenz-System haben, das sie bei Ihrer Arbeit unterstützt. Dennoch lässt sich der Satz sicher besser formulieren?

**Comment by detlevhfischer** [comment]
@MarcHaunschild  siehe Update. Den Satz gibt es nun nicht mehr.
