### ISSUE TITLE
9.3.3.4 Fehlervermeidung wird unterstützt - immer anwendbar?

### ISSUE THREAD

**Issue by darthnorman** [BIK-BITV/BIK-Web-Test#176]
Bei diesem Prüfschritt kann nicht gewählt werden, dass er "nicht anwendbar" ist, obwohl in der Erklärung des Schritts steht, dass er nur unter bestimmten Bedingungen anwendbar ist.

Entweder die Option kommt dazu oder die Anwendbarkeit wird so formuliert, dass der Schritt immer anwendbar ist.

**Comment by detlevhfischer** [comment]
Ich habe das angepasst, danke für den Hinweis.
