### ISSUE TITLE
9.2.2.2: Ausnahme für unverzichbare Animation ("essential") wird nicht berücksichtigt

### ISSUE THREAD

**Issue by cstrobbe** [BIK-BITV/BIK-Web-Test#18]
[Erfolgskriterium 2.2.2](https://www.w3.org/TR/WCAG21/#pause-stop-hide) enthält die folgende Ausnahme:

>  unless the movement, blinking, or scrolling is part of an activity where it is **essential**;

Diese Ausnahme wird weder im Abschnitt "Prüfung" noch in den anderen Teilen des Prüfschritt berücksichtig.

Mögliche Verbesserungen:

* **Technische Angaben: Prüfschritt erfüllt**: "Bewegte oder blinkende Inhalte **sind unverzichtbar für den Informationsinhalt oder die Funktionen der Webseite**, sind nicht vorhanden, stoppen spätestens nach 5 Sekunden, oder es gibt eine Möglichkeit, die Bewegung/das Blinken anzuhalten, zu beeenden oder auszublenden."
* **Was wird geprüft?** Neuer Absatz: Unverzichtbar für die Funktionen einer Webseite ist zum Beispiel die ständige Aktualisierung der verbleibenden Zeit bei einem zeitbegrenztem Assessment.
* **Prüfung**: Neuer Schritt (als erster Schritt): Prüfen, ob die Bewegung unverzichtbar ist für den Informationsinhalt oder die Funktionen der Webseite.

**Comment by johannesFischer84** [comment]
Ich stimme vollständig zu.
Eine Sache, die im Vergleich zur WCAG 2.2.2 auch noch in der Anleitung fehlt: Bewegungen/Aktualisierungen müssen nur pausiert werden können. wenn die Animation parallel zu anderen Inhalten dargestellt wird. Ist die Animation der einzige nutzbare Inhalt einer Ansicht, ist der Pausierungs-Mechanismus nicht verpflichtend.

**Comment by detlevhfischer** [comment]
Wir können das gerne ergänzen; die praktische Relevanz ist aber glaube ich gering. Ich hätte wenigstens die Aktualisierung der ablaufenden Zeitanzeige niemals als Blinken oder Bewegung erfasst und weiss auch von keinem Fall, wo andere Prüfer das getan haben.

**Comment by detlevhfischer** [comment]
@cstrobbe Ich würde den Zusatz bei Bewertung: "sind unverzichtbar für den Informationsinhalt oder die Funktionen der Webseite" hier lieber nicht aufnehmen, sondern Fälle, in denen Sich Inhalte ändern (auto-updaten) und dies wichtig ist (Runterzählen der verbleibenden Zeit vor Logout, Erhöhung von Gebotssummen usw.) schon bei Anwendbareit des Prüfschritts deutlicher ausnehmen. Dann kann auch der vorgeschlagene erste Schritt entfallen, denn er findet schon bei der Einschätzung der Anwendbarkeit des Prüfschritts statt. Ich finde es gut, hier schon die genannten gängigen Ausnahmen bei Aktualisierung zu nennen.

**Comment by detlevhfischer** [comment]
@johannesFischer84 Der Fall von Inhalten, die nicht gleichzeitig mit anderen Inhlaten dargestellt werden, wird bereits im Abschnitt 1. Anwendbarkeit des Prüfschritts" berücksichtigt.

**Comment by cstrobbe** [comment]
Hintergrund für dieses Issue ist u.a. auch eine BITV-Evaluation einer Assessment-Website, in der die verbleibende Zeit nicht nur als Text sondern auch als animierter Kreis dargestellt wird. (Der Rand des Kreises wird im Uhrzeigersinn fortschreitend eingefärbt.) Es handelt sich also um eine Kombination von bewegendem Inhalt und automatischer Aktualisierung, bei der man den animierten Kreis streng genommen als redundant einstufen kann. (Im WCAG-Erfolgskriterium wird deutlich zwischen beiden Typen von Inhalt unterschieden.)

**Comment by detlevhfischer** [comment]
@cstrobbe Der Fortschritt der Grafik ist höchstwahrscheinlich zu langsam, um überhaupt als Bewegung, geschweige denn als störende, wahrgenommen zu werden. Bist Du mit den Änderungen in #20 einverstanden? Sonst editier das gern noch...

**Comment by johannesFischer84** [comment]
@detlevhfischer Du hast Recht, die Darstellung mit anderen Inhalten gemeinsam ist bereits in der Anwendbarkeit enthalten. Vielleicht hat sich das irgendwann geändert oder ich habe es immer überlesen. Für mich passen auch die Änderungen im Pull Request #20.

**Comment by cstrobbe** [comment]
@detlevhfischer  Ich bin mit den Änderungen im Pull Request einverstanden.
(Die Grafik wurde jede Sekunde aktualisiert; allerdings wird die Frequenz der Aktualisierung in SC 2.2.2 gar nicht berücksichtigt.)
