### ISSUE TITLE
12.1.1 Dokumentation von Kompatibilität und Barrierefreiheit

### ISSUE THREAD

**Issue by SaschaNoack** [BIK-BITV/BIK-Web-Test#185]
In den Folien zu diesem Prüfschritt stand:

![image](https://user-images.githubusercontent.com/80102968/111862696-36d4ae00-8957-11eb-8503-8a1c3350a453.png)

Mit der „Anwendbarkeit“ komme ich nicht ganz klar.. hier steht anwendbar, wenn das Angebot webbasierte Dokumentation von Zugänglichkeitsfeatures hat“ ... Im Original steht  „Product documentation provided with the ICT whether provided separately or integrated within the ICT shall list and explain how to use the accessibility and compatibility features of the ICT.
Daraus schieße ich folgende Szenarien:
- Eine Anwendung hat Features und eine Dokumentation, die aber nichts zu den Features sagt --> "nicht erfüllt"
- Eine Anwendung hat Features und keine Dokumentation --> "nicht anwendbar"
- Eine Anwendung hat Features und eine Dokumentation, die etwas zu den Features sagt --> Beschreibung der Features prüfen und dann bewerten.

Dann treibt mich noch etwas um... was genau ist unter Feature zu verstehen...? Nur explizit aktivierbare Funktionen wie Vorlesen, Kontrastumschalter etc? Oder ist ein Feature auch ein im Code verborgenes ARIA, welches ja Screenreaderausgaben unterstützt?
 
Der Originaltext sagt „**Accessibility and compatibility features include accessibility features that are built-in** and **accessibility features that provide compatibility with assistive technology.**„
 
Ich deute es dann so:
 
**Accessibility and compatibility features include accessibility features that are built-in** --> das sind Schalter mit denen ich was aktivieren kann, z.B. Kontrastumschalter.
 
and **accessibility features that provide compatibility with assistive technology**. --> im zweiten Satzteil ist nicht mehr die Rede von “build-in“... d.h. könnte man hier auch ARIA darunter verstehen?
  
Somit wäre der Prüfschritt "nicht erfüllt", wenn ARIA eingesetzt wird, es jedoch nicht in der Dokumentation erläutert ist und "nicht anwendbar" wenn es überhaupt keine Doku im Webformat gibt?

**Comment by MarcHaunschild** [comment]
Das ist ein guter Hinweis! Man sollte die Test-Anweisung so formulieren, dass ein Feature etwas ist, was bedient werden muss, um kompatibel mit ATs zu sein.
Mir scheint die en setzt (nicht nur hier) "Features" gleich mit "Funktionen", die genutzt werden können/ müssen.

**Comment by johannesFischer84** [comment]
> - Eine Anwendung hat Features und eine Dokumentation, die aber nichts zu den Features sagt --> "nicht erfüllt" 
> - Eine Anwendung hat Features und keine Dokumentation --> "nicht anwendbar"
> - Eine Anwendung hat Features und eine Dokumentation, die etwas zu den Features sagt --> Beschreibung der Features prüfen und dann bewerten.

Hier würde ich zustimmen.

> and accessibility features that provide compatibility with assistive technology. --> im zweiten Satzteil ist nicht mehr die Rede von “build-in“... d.h. könnte man hier auch ARIA darunter verstehen?

Meiner Meinung nach beziehen sich die Kompatibilitätseigenschaften darauf, dass dem Nutzer vermittelt werden soll, wenn er an seiner Technik eine bestimmte Einstellung vornehmen muss, damit er bestimmte Inhalte wahrnehmen bzw. bedienen kann. Bei ARIA muss ein Nutzer aber in der Regel keine Einstellungen treffen, assistive Technologien sollten damit bereits in ihrer Standardkonfiguration umgehen können. Daher muss man ARIA auch nicht in einer Dokumentation aufführen.
Ein weiteres Beispiel würde ich noch ein einer Anwendung sehen, die aus irgendeinem Grund nur mit einem Screenreader bzw. einer bestimmten Version funktioniert. Auf so etwas sollte in der Dokumentation hingewiesen werden.

**Comment by detlevhfischer** [comment]
Ich habe Anwendbasrkeit und Bewertung versucht in meinem PR https://github.com/BIK-BITV/BIK-Web-Test/pull/231 genauer zu fassen.

**Comment by johannesFischer84** [comment]
Im Bereich "Hinweise" steht jetzt unter Punkt 4:
> Manche Barrierefreiheitsfunktionen, etwa Kontrastschalter im Kopfbereich, ändern unmittelbar die Darstellung der Seite und können damit als selbsterklärend gelten. Sofern diese einfachen Schalter zugänglich umgesetzt sind (also z.B. einen programmatisch ermittelbaren Namen und Zustand haben) müssen sie nicht explizit in der Erklärung zur Barrierefreiheit dokumentiert sein.

Ich würde sagen, dass ein Kontrastumschalter in der Erklärung zur Barrierefreiheit bzw. Hilfe zumindest genannt werden werden müsste. Es kann ja auch sein, dass der Schalter erst hinter der Navigation oder in einem Untermenü zu finden ist und beispielsweise Nutzende mit Unterstützung eines Screenreaders diese Funktion nicht direkt finden.
Eine Erklärung muss nicht sein, aber eine Nennung schon.

**Comment by sweckenmann** [comment]
Ich schlage dann vor, dass wir in der Weise ergänzen, dass der Punkt 4 nur für einen Kotrastschalter gilt, der deutlich sichtbar im Header verortet ist (was wir bei 9.1.4.3 auch fordern), so etwa:

> Manche Barrierefreiheitsfunktionen, etwa Kontrastschalter im Kopfbereich, ändern unmittelbar die Darstellung der Seite und können damit als selbsterklärend gelten. Sofern diese einfachen Schalter im Kopfbereich direkt sichtbar und zugänglich umgesetzt sind (also z.B. einen programmatisch ermittelbaren Namen und Zustand haben) müssen sie nicht explizit in der Erklärung zur Barrierefreiheit dokumentiert sein.

**Comment by johannesFischer84** [comment]
Ja, mit dem Hinweis "direkt sichtbar" klingt es besser, danke.
Ich würde zwar immer empfehlen, die Funktion dennoch in der Erklärung bzw. in einer Hilfe zu nennen, aber einfordern muss man es in dem Fall der direkten Sichtbarkeit und selbsterklärenden Nutzung nicht.

**Comment by sweckenmann** [comment]
Okay, für das nächste Release werde ich das so ändern (wir veröffentlichen zukünftig jeweils zum neuen Quartal ein Release). Danke auch für den Hinweis.
