### ISSUE TITLE
12.2.2 Technischer Support

### ISSUE THREAD

**Issue by jkphl** [BIK-BITV/BIK-Web-Test#191]
Zur Anwendbarkeit des Prüfschritts heißt es:

> Der Prüfschritt ist anwendbar, wenn das Webangebot in seiner Dokumentation Informationen zu Barrierefreiheits-Funktionen oder zur Hilfsmittel-Kompatibilität bereitstellt.

1. Ist davon auszugehen, dass unter „Barrierefreiheits-Funktionen“ nur solche ausdrücklichen Ergänzungen verstanden werden, wie sie etwa unter [12.1.1 Dokumentation von Kompatibilität und Barrierefreiheit](https://github.com/BIK-BITV/BIK-Web-Test/blob/master/Pr%C3%BCfschritte/de/12.1.1%20Dokumentation%20von%20Kompatibilit%C3%A4t%20und%20Barrierefreiheit.adoc) aufgeführt werden? Also beispielsweise Vorlesefunktionen, Kontrastumschalter etc.?
2. Anders gefragt: Wenn die Website „nur“ möglichst barrierefrei umgesetzt ist, ohne dass dokumentationsrelevante Funktionen gem. 12.1.1. integriert wurden, ist dann dieser Prüfschritt (bzw. dieser Aspekt des Prüfschritts) _nicht anwendbar_?
3. Ist der Prüfschritt _nicht anwendbar_, wenn zwar besondere Barrierefreiheits-Funktionen integriert wurden, diese aber nicht in der Dokumentation auftauchen?

Und allgemein:

4. Wie soll die Abgrenzung zwischen „technischem Support“ („ICT support services“) und allgemeiner Kontaktmöglichkeit (z.B. Telefonnummer oder E-Mail-Adresse im Impressum) in der Praxis stattfinden? Welche Kriterien müssen erfüllt sein, damit eine Kontaktmöglichkeit als „technischer Support“ gilt?

**Comment by johannesFischer84** [comment]
> 1. Ist davon auszugehen, dass unter „Barrierefreiheits-Funktionen“ nur solche ausdrücklichen Ergänzungen verstanden werden, wie sie etwa unter 12.1.1 Dokumentation von Kompatibilität und Barrierefreiheit aufgeführt werden? Also beispielsweise Vorlesefunktionen, Kontrastumschalter etc.?

Mir scheint die Auflistung von 12.1.1 relativ ausführlich zu sein, wobei sie nie abschließend sein muss. Aber ich würde prinzipiell zustimmen, nur die in 12.1.1 genannten Funktionen, wenn in der Dokumentation genannt.

> 2. Anders gefragt: Wenn die Website „nur“ möglichst barrierefrei umgesetzt ist, ohne dass dokumentationsrelevante Funktionen gem. 12.1.1. integriert wurden, ist dann dieser Prüfschritt (bzw. dieser Aspekt des Prüfschritts) nicht anwendbar?
3. Ist der Prüfschritt nicht anwendbar, wenn zwar besondere Barrierefreiheits-Funktionen integriert wurden, diese aber nicht in der Dokumentation auftauchen?

Anhang C der EN hat als Precondition (Anwendbarkeits-Bedingung) nur den Technischen Support genannt. Daher würde ich bei beiden Fragen wohl auf _erfüllt_ entscheiden, sofern ein Technischer Support vorhanden ist. _Nicht anwendbar_ würde ich wählen, wenn kein Support da ist.

> 4. Wie soll die Abgrenzung zwischen „technischem Support“ („ICT support services“) und allgemeiner Kontaktmöglichkeit (z.B. Telefonnummer oder E-Mail-Adresse im Impressum) in der Praxis stattfinden? Welche Kriterien müssen erfüllt sein, damit eine Kontaktmöglichkeit als „technischer Support“ gilt?

Was ein Support sein kann, ist in der EN in Abschnitt 12.2.1 mit Beispielen beschrieben. Aus meiner Sicht sollte der Support Unterstützung zu den Funktionalitäten der Seite bieten oder eine zusätzliche Dienstleistung zu dem Webseitenangebot bieten. Wenn es zum Beispiel eine Service-Telefonnummer eines Verkehrsverbundes zu ÖPNV-Verbindungen gibt oder wenn eine Bibliothek einen Chat anbietet, um Fragen zur Ausleihe zu klären, dann würde ich das als Support zählen. Eine einfache Kontakt-Möglichkeit des Betreibers würde ich da nicht ausreichend sehen. Falls jedoch ein einfacher Kontakt nur per E-Mail oder nur per Telefon möglich wäre, würde ich zumindest einen Hinweis geben, dass man über eine zweite Kontakt-Alternative nachdenken sollte.

**Comment by sweckenmann** [comment]
> Service-Telefonnummer eines Verkehrsverbundes zu ÖPNV-Verbindungen, Chat einer Bibliothek, um Fragen zur Ausleihe zu klären

Wäre das wirklich ein **technischer** support oder nicht vielmehr ein Support zur Dienstleistung? Da gehts doch mehr um inhaltliche Fragen wie z.B. "wie lang kann ich ausleihen" etc. Abgrenzung ist sicher nicht ganz einfach.

**Comment by johannesFischer84** [comment]
> Wäre das wirklich ein technischer support oder nicht vielmehr ein Support zur Dienstleistung? Da gehts doch mehr um inhaltliche Fragen wie z.B. "wie lang kann ich ausleihen" etc. Abgrenzung ist sicher nicht ganz einfach.

Die EN hat eigentlich den Begriff "ICT support services". Der "technical support" ist in 12.2.1 nur ein Beispiel dazu. Nach meinem Gefühl wäre ein Support zur Dienstleistung des Webangebots schon umfasst. Aber da es kein Understanding-Dokument mit schöner Erläuterung zur EN gibt, sehe ich das leider als Interpretationsspielraum. Ich kann nachvollziehen, dass du es anders interpretierst.

**Comment by 00travelgirl00** [comment]
Müsste bei dem Punkt "Der Prüfschritt ist anwendbar" nicht stehen "wenn Support angeboten wird"? 
Eine Dokumentation der Barrierefreiheitsfunktionen setzt ja nicht voraus, dass es einen Support gibt.

**Comment by johannesFischer84** [comment]
> @johannesFischer84 @sweckenmann Ich denke, bei dem Verständnis, was zum Begriff "ICT support services" so dazu gehört, kann man aus dem Fokus auf "Barrierefreiheits-Funktionen oder [Infos zur] zur Hilfsmittel-Kompatibilität" in diesem Prüfschritt schon schließen, dass es nicht um inhaltlichen Support bezüglich der angebotenen Dienstleistungen, sondern um technischen Support für die Nutzung des Angebots, hier mit Bezug auf Hilfsmittel, geht hier mit Bezug auf Extra-Funktionen und Hilfsmittel.

Der Unterstützungsdienst/Support ist in 12.2.1 definiert. Dort ist aber nur von Help Desks, Call Centres usw. die Rede. Diese sind ganz allgemeine Dienstleistungen und haben nicht nur etwas mit speziell assistiven Technologien zu tun. Daher kann man den Begriff des Supports aus meiner Sicht nicht einschränken. Im Beispiel einer Service-Hotline eines Verkehrsverbunds zur Ermittlung von Verbindungen ist das ja auch ein Dienst für Menschen, denen es schwer fällt, die Verbindungssuche auf der Webseite zu nutzen, also für Menschen, denen das Sprechen am Telefon leichter fällt als die Bedienung eines Computers. Wenn diese Alternative auf der Webseite genannt wird, muss sie auch barrierefrei im Sinne eines Unterstützungsdienstes sein.

> "Der Prüfschritt ist anwendbar, wenn das Webangebot:
> - ergänzende Barrierefreiheits-Funktionen integriert und diese dokumentiert hat
und / oder (?)
> - ein technischer Support für die Bedienbarkeit des Webangebots angeboten wird."

Streng genommen ist nach der EN im Anhang C nur der zweite Punkt für die Anwendbarkeit relevant (Pre-Condition). Also eigentlich ist 12.2.2 anwendbar, sobald ein Support angeboten wird. Wenn keine Barrierefreiheitsfunktionen dokumentiert sind, muss man natürlich trotzdem nicht den Support kontaktieren. Die Bewertung wäre trotzdem _erfüllt_ statt _nicht anwendbar_. Aber das sind nur Kleinigkeiten, die nicht so entscheidend sind.

**Comment by sweckenmann** [comment]
@johannesFischer84 

> Der Unterstützungsdienst/Support ist in 12.2.1 definiert. Dort ist aber nur von Help Desks, Call Centres usw. die Rede. Diese sind ganz allgemeine Dienstleistungen

Das kann man so sehen. Aber es ist doch auch so, dass Help Desks, Call Center zu einem bestimmten Zweck zur Verfügung gestellt werden und die Mitarbeitenden entsprechend ausgebildet sind. Eine Service, der nur dazu da ist, telefonische Informationen zu einer Zugverbindung zu übermitteln oder der am Telefon die Buchung einer Fahrkarte übernimmt für Leute, die das nicht über die Website zu wollen, wird nicht dazu ausgebildet sein, über Funktionen einer Website zu informieren. Wohingegen man von einem Help Desk oder ein Call Center, das technische Unterstützung geben soll, dies schon erwarten könnte. Die Begriffe sind zwar allgemein, aber ich finde es recht praxisfern, wenn man hier nicht auf technische Unterstützende fokussieren würde.

> Wenn diese Alternative auf der Webseite genannt wird, muss sie auch barrierefrei im Sinne eines Unterstützungsdienstes sein.

Aber das ist nicht Gegenstand von 12.2.2? Hier gehts doch nur darum, dass man vom Support Informationen zu "accessibility and compatibility features that are mentioned in the product documentation" einholen können soll.

> Streng genommen ist nach der EN im Anhang C nur der zweite Punkt für die Anwendbarkeit relevant (Pre-Condition). Also eigentlich ist 12.2.2 anwendbar, sobald ein Support angeboten wird. Wenn keine Barrierefreiheitsfunktionen dokumentiert sind, muss man natürlich trotzdem nicht den Support kontaktieren. Die Bewertung wäre trotzdem erfüllt statt nicht anwendbar.

Naja, aber wenn keine Barrierefreiheitsfunktionen dokumentiert sind, kann man nicht prüfen, ob der Support Auskunft darüber geben KANN. Insofern kann man auch nicht sagen "erfüllt" sondern "nicht anwendbar" (im Sinne "es gibt hier nichts zu prüfen")? Aber stimme zu, ist nicht entscheidend.

**Comment by johannesFischer84** [comment]
@sweckenmann 
> Eine Service, der nur dazu da ist, telefonische Informationen zu einer Zugverbindung zu übermitteln oder der am Telefon die Buchung einer Fahrkarte übernimmt für Leute, die das nicht über die Website zu wollen, wird nicht dazu ausgebildet sein, über Funktionen einer Website zu informieren.

Ja, das kann sein. Wenn so eine Hotline aber als "Auskunft & Service" oder als "Service-Hotline" bezeichnet wird, kann man aus meiner Sicht durch die Bezeichnung allein nicht wissen, ob tatsächlich nur eine Verbindungsauskunft dieses Verkehrsverbunds gegeben wird oder ob man den Support im Hinblick auf jegliche Dienstleistung des Verkehrsverbunds inklusive aller Details der Webseite kontaktieren kann.

> > Wenn diese Alternative auf der Webseite genannt wird, muss sie auch barrierefrei im Sinne eines Unterstützungsdienstes sein.

> Aber das ist nicht Gegenstand von 12.2.2? Hier gehts doch nur darum, dass man vom Support Informationen zu "accessibility and compatibility features that are mentioned in the product documentation" einholen können soll.

Ja, in 12.2.2 soll der Support nur nur um Infos zur Barrierefreiheit/Kompatibilität geben können, die auch in der Produktdokumentation vorhanden sind. Ich denke allerdings, dass das nur eine Zusatzforderung zu dem übrigen Angebot der Service-Hotline ist. Dass z. B. über Zugverbindungen bzw. die Dienste der Webseite Auskunft gegeben werden soll, muss in der EN ja nicht extra nochmal gefordert werden. Aber an Barrierefreiheits-Dienste denkt nicht gleich jeder, daher wird das wohl in der EN erwähnt, so meine Vermutung.

Also ich kann schon nachvollziehen, warum du die 12.2.2 so interpretierst, Sonja. Leider definiert die EN den Support in 12.2.1 nicht genauer und so bleibt Interpretationsspielraum ...

> Naja, aber wenn keine Barrierefreiheitsfunktionen dokumentiert sind, kann man nicht prüfen, ob der Support Auskunft darüber geben KANN. Insofern kann man auch nicht sagen "erfüllt" sondern "nicht anwendbar" (im Sinne "es gibt hier nichts zu prüfen")? Aber stimme zu, ist nicht entscheidend.

Ich stimme dir zu. Nur ist das im Annex C der EN nicht so aufgeschrieben. Wahrscheinlich auch ein Fehler, der vielleicht in einer Folgeversion mal korrigiert werden könnte auf "nicht anwendbar". Man könnte sich natürlich die Freiheit herausnehmen, diesen Fehler in eigenen Prüfanleitungen zu "korrigieren".
