### ISSUE TITLE
9.3.1.2 Anderssprachige Wörter und Abschnitte ausgezeichnet

### ISSUE THREAD

**Issue by tetzla** [BIK-BITV/BIK-Web-Test#199]
Kaum eine Web-Anwendung wird heutzutage durch manuelles Schreiben von HTML-Quellcode realisiert, vielmehr wird der HTML-Quellcode auf Basis eines UI-Frameworks generiert. Die anzuzeigenden Oberflächentexte werden dabei meist in sprachspezifischen Properties-Dateien abgelegt. Die Verwendung von HTML-Code in den Properties-Dateien ist weder empfehlenswert noch zulässig (Negativ-Beispiel: `Der <span lang="en">Code of Conduct</span> ist eine Sammlung von Verhaltensweisen...`). Auf Ebene des UI-Frameworks (z. B. XHTML) ist häufig nicht bestimmbar, welche Oberflächentexte konkret zur Anzeige gebracht werden. Eine Anreicherung mit lang-Attributen ist daher hier ebenfalls nicht möglich.

Fazit: Ich verstehe die Intention des Prüfschritts. Er scheint mir jedoch für viele Web-Anwendungen technisch nicht realisierbar. Wie soll damit umgegangen werden? Darf der Prüfschritt als "nicht anwendbar" eingestuft werden?

**Comment by MarcHaunschild** [comment]
Der Prüfschritt ist nicht anwendbar, wenn es keine anderssprachigen Texte gibt.
Wenn man ein Framework benutzt, das nicht barrierefreien Code erzeugt, erhält man eine nicht barrierefreie Website.
Barrierefreiheit muss von Anfang an mitgedacht werden.
Schon bei der Entscheidung für ein bestimmtes Werkzeug.
Gerade die saubere Trennung von Inhalt, Layout und Funktion ist dabei hilfreich.
In dem von dir genannten Beispiel wurde die vermutlich nicht zu Ende gedacht oder das Framework hat dafür eine Lösung, die bei der Verwendung nicht berücksichtigt wurde.

**Comment by johannesFischer84** [comment]
> (Negativ-Beispiel: `Der <span lang="en">Code of Conduct</span> ist eine Sammlung von Verhaltensweisen...`)

Warum ist das ein Negativbeispiel? Die Auszeichnung ist doch richtig?

Bei WCAG Kriterium 3.1.2 gibt es zunächst ein paar Ausnahmen: Vor allem Eigennamen und Fachbegriffe sind von der Pflicht ausgenommen, sie mit dem `lang`-Attribut auszuzeichnen. Ansonsten müssen Sprachwechsel laut den WCAG ausgezeichnet werden. Man kann ggf. darüber diskutieren/streiten, ob "kleinlich" jedes kleine Wort ausgezeichnet werden muss. Aber die Pflicht im Allgemeinen besteht.

Mein Vorschlag auf Basis Ihrer Beschreibung mit den Properties-Dateien wäre: Man muss ja in den Properties-Dateien nicht unbedingt HTML-Code angeben. Aber wenn die Properties-Dateien sprachspezifisch sind, sollte sich zum Beispiel die Sprache daran erkennen lassen, aus welcher Properties-Datei ein Begriff kommt. Ebenso könnte man bei nicht sprachspezifischen Dateien die Sprache eines Begriffs als eigene Eigenschaft (Property) bei dem Begriff in der Datei abspeichern. Dann könnte man diese Eigenschaft abfragen, bevor der Text ins HTML gesetzt wird. So kann das `lang`-Attribut anschließend gesetzt werden.

**Comment by tetzla** [comment]
Vielen Dank für die schnellen Rückmeldungen. Ich habe zumindest ein paar Denkanstöße bekommen.

@MarcHaunschild: Es handelt sich nicht wirklich um einen Framework- oder Entwickler-Fehler.

Beispiel: Ein komplexe Anwendung besteht aus mehreren Teilkomponenten. Die Teilkomponenten stammen von unterschiedlichen Software-Anbietern. Der Quellcode zum Generieren des Menüs sammelt die Namen aller registrieren Menüeinträge aus den Properties-Dateien der Teilkomponenten ein und generiert den passenden HTML-Code daraus.

HTML-Code in den Properties-Dateien wird der "Menü-Generator" niemals als solchen interpretieren, sondern 1:1 als Text an der Oberfläche anzeigen (siehe "Negativbeispiel" -> Stichwort: IT-Security). Die Sprache des Menüeintrags könnte der "Menü-Generator" nur mit eingebautem Wörterbuch ermitteln. (Etwas derartiges habe ich noch nie gesehen.)

@johannesFischer84 : Ich habe mir die Liste der Ausnahmen nochmal angeschaut: Eigennamen, Fachbegriffe, im Duden enthaltene oder identisch ausgesprochene Fremdwörter -> Es handelt sich um eine komplexe Geschäftsanwendung. Für (nahezu?) alle englischsprachigen Begriffe greifen die genannten Ausnahmen.

Der Vorschlag zu den Properties-Dateien wäre machbar, wenngleich aufwändig. Ebenso wäre es denkbar in den deutschen Dateien nur deutsche Texte zu pflegen und in den englischen Dateien nur englische Texte. Der Code-Generator könnte bei nicht Vorhandensein eines deutschen Textes einen Fallback auf den englischen Text durchführen und den generierten Quellcode automatisch mit dem lang-Attribut kennzeichnen. Dieses Feature unterstützt das verwendete Framework tatsächlich nicht.

**Comment by MarcHaunschild** [comment]
> @MarcHaunschild: Es handelt sich nicht wirklich um einen Framework- oder Entwickler-Fehler.
> 
> Beispiel: [...]

Danke, das hat beim Verständnis geholfen. An meiner ersten Antwort ändert das nichts.

Wenn ein Menü in einem System generiert wird, muss es um auf der sicheren Seite zu sein, in diesem Fall z.B. eine Schnittstelle anbieten, über die ein Redakteur zum Beispiel für einen Menüpunkt eine andere Sprache festlegen kann.

Andere Möglichkeiten sind auch denkbar, zum Beispiel eine API, die es erlaubt Attribute in Tags einzufügen o.ä.

Daher meine ich BF von Anfang an mitdenken.

Die BITV gibt ja gerade für zentrale Elemente einer Site wie die Hauptnavigation vor, dass diese Barrierefreiheit nach dem Stand der Technik umsetzen soll. Auch wenn das eine Soll-Bestimmung ist, gibt das bei Tests auf Barrierefreiheit auch dem Prüfer einen Auftrag, hier genau hinzusehen. An den Minimal-Anforderungen, die die EN vorgibt ist daher nicht zu rütteln.

Anders ausgedrückt: einen Ermessensspielraum sehe ich hier nicht.

Aber:

> @johannesFischer84 : Ich habe mir die Liste der Ausnahmen nochmal angeschaut: Eigennamen, Fachbegriffe, im Duden enthaltene oder identisch ausgesprochene Fremdwörter -> Es handelt sich um eine komplexe Geschäftsanwendung. Für (nahezu?) alle englischsprachigen Begriffe greifen die genannten Ausnahmen.

Die Frage ist dann, ob es für die wenigen Fälle, wo die Ausnahmen nicht greifen, ein deutschsprachiger Begriff gefunden werden kann oder ein im Universalwörterbuch enthaltener Anglizismus.

Mir ist klar, dass das in der Hauptnavigation schwierig ist, aber wenn es sich weder um einen Eigennamen noch einen Fachbegriff handelt, sollte das mit gutem Willen fast immer machbar sein. Aber ja, das kann ein anstrengender Prozess sein.

Grundsätzlich ist eine möglichst leichte Sprache zu verwenden. Das ist nicht nur eine lästige Pflicht. Leichte Sprache ist das meist gewünschte Accessibility-"Feature" und daher ist deren Einsatz immer ein Gewinn für den Anbieter einer Website - auch bei der Gewinnung von Kunden ohne Behinderung.
