### ISSUE TITLE
9.2.4.2 Forderung für Seitentitel zu streng?

### ISSUE THREAD

**Issue by detlevhfischer** [BIK-BITV/BIK-Web-Test#200]
Historisch fordert der BITV-Test einen allgemeinen und einen spezifischen Teil im Seitentitel ( Bezeichnung der Seite + Name des Angebots). Dass ist sicher auch eine best practice und hilft, die Seite in der Liste der Browsertabs zu identifizieren. Auch bei Bookmarklets wird sie klarer zuzuordnen sein. Nachteile können sein: Der längere Seitentitel wird ggf. im Tab visuell abgeschnitten, und wenn der allgemeine Teil vorne steht, müssen Screenreadernutzer nach Fokussierung länger auf den relevanten unterscheidenden Anteil des title warten.
Es stellt sich die Frage, ob wir nicht über den normativen Text von 2.4.2 hinausgehen, der lediglich sagt:
> Web pages have titles that describe topic or purpose.

Auch die [allgemeine Technik G88](https://www.w3.org/WAI/WCAG21/Techniques/general/G88.html) verlangt nicht explitzit die Nennung des Angebots, sondern sagt nur:

> It may also be helpful for the title to
> - Identify the site or other resource to which the Web page belongs

Ein "may be helpful" legt nicht nahe, das hier die Nennung der Site normativ verlangt würde (und Techniken sind ohnehin grundsätzlich nur informativ).

Zur weiteren Anpassung des Tests an die normativen Minimalanforderungen der WCAG würde ich vorschlagen, die Prüfschrittbeschreibung so zu ändern, dass Thema / Titel oder Zweck der spezifische Seite genannt sein muss, aber nicht zwingend die Site, zu der sie gehört. Wo die Nennung der Site fehlt, könnte das mit "eher erfüllt" und Kommentar vermerkt werden (also konform).

**Comment by johannesFischer84** [comment]
Volle Zustimmung von mir. Ich bewerte aktuell auch mit "eher erfüllt", wenn ein Begriff für den Auftritt fehlt, sonst aber alles passt. In den Beispielen im Understanding-Dokument wird auch kein Titel des Auftritts genannt. Und wenn man sich den eigenen Titel bei der Webseite des WCAG-Dokuments ("Web Content Accessibility Guidelines (WCAG) 2.1") oder der Understanding-Dokumente ansieht, wird dort auch kein Auftritt in deren Seitentitel genannt.

Verwende aber bitte den deutschen Begriff "(Web)Auftritt", nicht "Site". Das ist dann besser verständlich bzw. aussagekräftig.
