### ISSUE TITLE
Prüfschritt 11.7 Benutzerdefinierte Einstellungen

### ISSUE THREAD

**Issue by sprungmarker** [BIK-BITV/BIK-Web-Test#207]
Bei WYSIWYG-Editoren wie CKEditor müsste die Seite nach den vorgenommen Einstellungen noch einmal geladen werden.
Dann sind etwa die grafischen Buttons dann nur noch Textbuttons.
Lädt man die Seite nicht neu, bleibt der herkömmliche Zustand.

https://ckeditor.com/ckeditor-4/demo/

Wie geht man damit um - solche Editoren sind ja weit verbreitet und die Optimierung, die der CKEditor vorgenommen hat, ist ja durchaus eine gute Lösung.

![grafik](https://user-images.githubusercontent.com/656578/123830315-78d0a100-d903-11eb-87a1-421aed85ea0a.png)
Screenshot CKEditor nach Reload bei benutzerdefinierten Einstellungen

Das betrifft nbur den CKEditor Version 4 - Version 5 hat die Buttons für benutzerdefinierte Einstellungen bereits optimiert. Aber CMS wie Drupal setzt auf längere Sicht nur die Version 4 ein.

**Comment by MarcHaunschild** [comment]
Da es sich um ein Werkzeug handelt, dass eingewiesenen Personen zur Verfügung gestellt wird, würde ich das so akzeptieren.

Dazu gehört natürlich eine (barrierefreie) Doku und eine Hotline...

Am 29.06.2021 um 18:01 schrieb Sylvia Egger ***@***.******@***.***>>:



Bei WYSIWYG-Editoren wie CKEditor müsste die Seite nach den vorgenommen Einstellungen noch einmal geladen werden.
Dann sind etwa die grafischen Buttons dann nur noch Textbuttons.
Lädt man die Seite nicht neu, bleibt der herkömmliche Zustand.

https://ckeditor.com/ckeditor-4/demo/

Wie geht man damit um - solche Editoren sind ja weit verbreitet und die Optimierung, die der CKEditor vorgenommen hat, ist ja durchaus eine gute Lösung.

[grafik]<https://user-images.githubusercontent.com/656578/123830315-78d0a100-d903-11eb-87a1-421aed85ea0a.png>
Screenshot CKEditor nach Reload bei benutzerdefinierten Einstellungen

Das betrifft nbur den CKEditor Version 4 - Version 5 hat die Buttons für benutzerdefinierte Einstellungen bereits optimiert. Aber CMS wie Drupal setzt auf längere Sicht nur die Version 4 ein.

**Comment by johannesFischer84** [comment]
> Bei WYSIWYG-Editoren wie CKEditor müsste die Seite nach den vorgenommen Einstellungen noch einmal geladen werden.
Dann sind etwa die grafischen Buttons dann nur noch Textbuttons.
Lädt man die Seite nicht neu, bleibt der herkömmliche Zustand.

Das Neuladen finde ich in Ordnung. Die Einstellungen setzt ein Nutzer in der Regel wohl dauerhaft und nicht nur spontan für eine Seite. Dass sich die Symbole in Text verwandeln, finde ich nicht schlimm. Aus meiner Sicht ist es eine andere Darstellung, die auch in Desktop- und mobiler Ansicht theoretisch in dieser Weise unterschiedlich gestaltet werden dürfte.

**Comment by detlevhfischer** [comment]
@sprungmarker Ich habe jetzt bei 11.7 den Satz hinzugefügt:  "In manchen Fällen muss die Seite neu geladen werden, damit sich die Änderungen auswirken."
Kann ich das Issue schließen?

**Comment by brambro** [comment]
Ich stolpere gerade über diesen Artikel und frage mich, ob 11.7 für Kommunen relevant ist. 11.7 wird in der Liste aufgeführt nach der dieser Punkt für WCAG 2.1 nicht relevant ist und über die Anforderungen hinaus geht. Lese ich das falsch? Das wäre schade, denn den Dark Mode an Webseiten durchzureichen macht ja Sinn.

Requirements in EN 301 549 and relevant to the WAD, but not in WCAG 2.1
https://digital-strategy.ec.europa.eu/en/policies/latest-changes-accessibility-standard#requirements-not-wcag

**Comment by brambro** [comment]
@detlevhfischer Ich muss da nochmal nachfragen. In der EN 301 549 in der Version 3.2.1 lese ich nicht den Dark Mode heraus, sondern die Einstellungen die im Browser gemacht werden. Diese sollen von der Webseite übernommen werden. Die Prüfungsschritte berücksichtigen auch nur diese Browsereinstellungen des Firefox. Dort müßte doch dann auch darauf eingegangen werden, daß die Anforderung über die benutzerdefinierten Browsereinstellungen hinausgeht. Das bedeutet für Webseitenentwickler ja dann die Abfrage des Schemas mit einer Media Query @media (prefers-color-scheme: dark) und einer entsprechenden Farbanweisung für Texte und Hintergrund. Das würde die Prüfung in dieser Form nicht aufdecken.

**Comment by detlevhfischer** [comment]
@brambro Ich denke, wir müssen hier einen Unterscheid machen zwischen den Anforderungen für Webangebote bzw. Web-Anwendungen und für native Apps, für die die mobilen Betriebssysteme und deren Einstellungen wie Dark Mode übernommen werden sollen. Für Web-Inhalte gilt der Browser als die Systemumgebung, deren Einstellungen übernommen werden sollen: siehe im [Püfschritt 11.7](https://github.com/BIK-BITV/BIK-Web-Test/blob/master/Prüfschritte/de/11.7%20Benutzerdefinierte%20Einstellungen.adoc)
> NOTE 2: For web content, the underlying platform is the user agent.

Deshalb reduziert sich die Prüfung im Web-Test auf Änderungen der Browser-Einstellungen. Eine weitergehende Forderung ist vielleicht sinnvoll, aber ich sehe zur Zeit in der EN nichts, was auch die Übernahme von Einstellungen der "underlying platform des user agent", also des Betriebssystems, mit einbezieht. Hinweise sind hier aber sehr willkommen!

**Comment by brambro** [comment]
O.K. Danke! Dann ist aber die Anforderung "Farben (z. B. Darkmode)" hier irreführend.
Wenn ich es dann richtig verstanden habe git die Übernahme des Dark Modes bei kommunalen Websites nur wenn sie ihre Website als Progressive Webapp (PWA) darastellen.

**Comment by detlevhfischer** [comment]
@brambo Stimmt der Hinweis auf 'dark mode' ist hier irreführend, denn dessen Übernahme wird ja, wenn ich es richtig sehe, nicht verlangt. (im App-Test dann schon).
Progressive Web Apps (WPAs) wären trotz Icon auf Home Bildschirm denke ich wie Web Apps zu behandeln, also als Web Content, da sie den Web Technology Stack HTML/CSS/JS nutzen. Wenn ich es richtig verstehe, laufen ja WPAs nicht unabhängig vom mobilen Browser, sondern setzten auf diesem auf. Bin mir da aber nicht sicher - andere mögen gerne bestätigen oder widersprechen..
Ich hä einen PR #228 angelegt, der den Hinweis auf dark mode entfernt. Bite andere nochmal draufgucken.

**Comment by MarcHaunschild** [comment]
Ich habe mir die Forderungen in der EN noch mal angeschaut:

### C.11.7 User preferences

#### Pre-conditions

1. The software is software that provides a user interface.
2. The software has settings for language, colour, contrast, font type, font size, or focus
cursor, that correspond to platform settings.
3. The software is not designed to be isolated from its underlying platforms.

#### Not applicable: Pre-condition 1, 2 or 3 is not met.

Demnach wird gefordert, dass die Software (aka Website) selber diese Änderungen anbietet (mir fallen da spontan a11y-overlays ein).

Wir prüfen aber derzeit, ob die Einstellungen der darunterliegenden Plattform (für Webanwendungen ist das der Browser) übernommen werden.

> Die Seite soll benutzerdefinierte Browsereinstellungen berücksichtigen.

Das kann man IMHO so nicht fordern, weil es von der EN nicht gedeckt wird und auch die WCAG gibt nichts dergleichen her (wird vielleicht mit der Version 3.0 kommen).

**Comment by johannesFischer84** [comment]
@MarcHaunschild 
Wenn du dir nicht nur den Anhang C, sondern die Anforderung 11.7 selbst ansiehst, steht da die NOTE 2: 
> For web content, the underlying platform is the user agent.

Durch diese NOTE ist die Prüfung der Browsereinstellungen von der EN schon gedeckt.

**Comment by MarcHaunschild** [comment]
> > For web content, the underlying platform is the user agent.
> 
> Durch diese NOTE ist die Prüfung der Browsereinstellungen von der EN schon gedeckt.

Ja. Hatte ein (anderes) Verständnis-Problem. Ist für mich manchmal immer noch schwierig mit vielen Verneinungen im englischen...

Klang für mich in den Bedingungen so, als wäre es nur anwendbar, wenn die Einstellungen in der Software und eben nicht in der underlying platform gemacht werden.

Danke für die Richtigstellung, @johannesFischer84
