### ISSUE TITLE
Seite "Werkzeugliste" - Updates Tools

### ISSUE THREAD

**Issue by sprungmarker** [BIK-BITV/BIK-Web-Test#218]
Hier werden Updates gesammelt zu den Tools der Seite "Werkzeugliste"

**Comment by PoNi-BITV** [comment]
Auf der [Werkzeugliste](https://www.bitvtest.de/bitv_test/das_testverfahren_im_detail/werkzeugliste.html) des BITVTests
ist für den PDF Accessibility Checker (PAC 3) noch folgender Link hinterlegt: 
https://www.access-for-all.ch/ch/pdf-werkstatt/pdf-accessibility-checker-pac.html

Hier kann aber nur die Version 3 "PDF Accessibility Checker 3.0 (PAC 3) vom 19.12.2017."  heruntergeladen werden.

Man könnte den Link durch diesen hier ersetzen: 
https://pdfua.foundation/de/pdf-accessibility-checker-pac

Hier gibt es den aktuellen PAC 2021 zum Download.

**Comment by detlevhfischer** [comment]
> Ist das nicht der Link zu dem WCAG Parsing Bookmarklet?

@pp-ernst Nein, dass ist ein Link zum text spacing Bookmarklet...
