### ISSUE TITLE
Prüfschritt 7.3 Bedienelemente für Untertitel und Audiodeskription

### ISSUE THREAD

**Issue by annikacurts** [BIK-BITV/BIK-Web-Test#219]
Guten Tag, ich hoffe, das hier ist der richtige Weg, um praktische Hinweise zur Erfüllung bestimmter Prüfschritte zu erbitten. Wenn dem nicht so ist, bitte ich um Entschuldigung und lösche dann natürlich das Issue.

Für einen Kunden setzt mein Unternehmen gerade einen Web-Relaunch unter Einhaltung der BITV um. An einigen Stellen sollen nun Videos eingebunden werden, von denen manche sicher auch per Definition Audiodeskriptionen benötigen werden.
Der Kunde möchte auf jeden Fall das Medium YouTube zur Einbindung der Videos auf der neuen Seite nutzen. 
Da der YouTube Player allerdings keine Audiodeskriptions-Funktion anbietet, wäre unser Lösungsvorschlag der, dass vom Kunden einfach zwei Video-Versionen bei YT hochgeladen werden und wir innerhalb des Video-Elements dann einen Button o.ä. anbieten, der bei Klick an selber Stelle das YouTube iframe mit der Audiodeskriptions-Video-Variante lädt.

So wie ich nun allerdings 7.3 interpretiere, würde das nicht ausreichen, da es hier so klingt, als müsse die Zuschaltfunktion direkt in den Player integriert sein. Das ist aus meiner Einschätzung nur über deutlich weniger populäre Player zu erreichen, die dann auch keinen eigenen Serverplatz für die hochgeladenen Videos bereitstellen, so wie es YouTube tut. In der Folge müsste unser Kunde bei einer Vielzahl von eingebundenen Videos diese selbst hosten und somit deutlich mehr Geld für Serverspeicher ausgeben, was voraussichtlich nicht möglich sein wird.

Es gibt dann hier im Github wiederum einige Issues, aus denen ich andere Interpretationen als meine herauslese. In einem anderen Issue habe ich beispielsweise eine Diskussion gesehen, in der beschrieben wurde, dass auch Bedienelemente direkt unterhalb des Players o.ä. konform seien. 

Können Sie mir vielleicht Hilfestellung geben, wie diese Video-Anforderungen insbesondere in Bezug auf Audiodeskriptionen praktisch zu erfüllen sind? In den Prüfergebnissen seit März 2021 habe ich leider keinen Webauftritt gefunden, bei dem Prüfschritte zur Audiodeskription anwendbar gewesen wären.

Vielen Dank und viele Grüße

**Comment by MarcHaunschild** [comment]
Hallo annikacurts,

Wenn keine anderen Gründe dagegen sprechen, könnte ein Blick auf den able player lohnen. Der lässt sich auch zusammen mit youtube verwenden.

https://ableplayer.github.io/ableplayer/demos/youtube.html

Gruß,

Marc


Am 21.10.2021 um 14:06 schrieb annikacurts ***@***.******@***.***>>:



Guten Tag, ich hoffe, das hier ist der richtige Weg, um praktische Hinweise zur Erfüllung bestimmter Prüfschritte zu erbitten. Wenn dem nicht so ist, bitte ich um Entschuldigung und lösche dann natürlich das Issue.

Für einen Kunden setzt mein Unternehmen gerade einen Web-Relaunch unter Einhaltung der BITV um. An einigen Stellen sollen nun Videos eingebunden werden, von denen manche sicher auch per Definition Audiodeskriptionen benötigen werden.
Der Kunde möchte auf jeden Fall das Medium YouTube zur Einbindung der Videos auf der neuen Seite nutzen.
Da der YouTube Player allerdings keine Audiodeskriptions-Funktion anbietet, wäre unser Lösungsvorschlag der, dass vom Kunden einfach zwei Video-Versionen bei YT hochgeladen werden und wir innerhalb des Video-Elements dann einen Button o.ä. anbieten, der bei Klick an selber Stelle das YouTube iframe mit der Audiodeskriptions-Video-Variante lädt.

So wie ich nun allerdings 7.3 interpretiere, würde das nicht ausreichen, da es hier so klingt, als müsse die Zuschaltfunktion direkt in den Player integriert sein. Das ist aus meiner Einschätzung nur über deutlich weniger populäre Player zu erreichen, die dann auch keinen eigenen Serverplatz für die hochgeladenen Videos bereitstellen, so wie es YouTube tut. In der Folge müsste unser Kunde bei einer Vielzahl von eingebundenen Videos diese selbst hosten und somit deutlich mehr Geld für Serverspeicher ausgeben, was voraussichtlich nicht möglich sein wird.

Es gibt dann hier im Github wiederum einige Issues, aus denen ich andere Interpretationen als meine herauslese. In einem anderen Issue habe ich beispielsweise eine Diskussion gesehen, in der beschrieben wurde, dass auch Bedienelemente direkt unterhalb des Players o.ä. konform seien.

Können Sie mir vielleicht Hilfestellung geben, wie diese Video-Anforderungen insbesondere in Bezug auf Audiodeskriptionen praktisch zu erfüllen sind? In den Prüfergebnissen seit März 2021 habe ich leider keinen Webauftritt gefunden, bei dem Prüfschritte zur Audiodeskription anwendbar gewesen wären.

Vielen Dank und viele Grüße
