### ISSUE TITLE
7.1.1/7.2.1 Zuschaltung UT/AD - Ausweg zweites Video

### ISSUE THREAD

**Issue by johannesFischer84** [BIK-BITV/BIK-Web-Test#22]
Da sich mein Anliegen in 7.1.1 und 7.2.1 nicht sonderlich unterscheidet, sondern analog funktioniert, mache ich für beide nur ein Issue auf:
## 7.1.1 Zuschaltung UT - Ausweg 2 Video-Versionen
Wenn die Video-Software nicht die Möglichkeit bietet, dass Untertitel zugeschaltet werden können, dann sollte der Seitenbetreiber aus meiner Sicht Konformität sicherstellen können, wenn er zwei Versionen des Videos anbietet, mit und ohne Untertitel (die automatisch zu sehen sind, also open captions)
## 7.2.1 Zuschaltung AD - Auswahl anderer Tonspuren bzw. 2 Video-Versionen
Wenn die Video-Software nicht die Möglichkeit bietet, dass Audiodeskription zugeschaltet werden kann, dann sollte der Seitenbetreiber aus meiner Sicht Konformität sicherstellen können, wenn er zwei Versionen des Videos anbietet, mit und ohne Audiodeskription.

**Comment by helmsaccess** [comment]
Geht es in diesen Prüfschritten denn nicht nur um Videos mit extra Audiospuren (AD) und Untertitelspuren? Es soll ja der Player bewertet werden und nicht die Inhalte.
Wenn es auf der Seite z. B. keine Videos mit eingebetteten Inhalten wie AD und UT gibt, sondern diese in separaten Videos ausgelagert werden (dann z. B. mit Open-Captions), wäre dieser Prüfschritt dann anwendbar?
Ich würde dann im Moment dazu tendieren, diesen PS auf nicht anwendbar zu setzen.

Je nach Ergebnis der Diskussion sollte der Prüfschritt dann im Punkt Anwendbarkeit präzisiert werden.

**Comment by johannesFischer84** [comment]
Ja, es geht um Videos mit AD bzw. UT und der Player, den der Webseiten-Betreiber verwendet, soll bewertet werden. Meine Annahme war, dass ein Betreiber einen Player verwendet, der keine Möglichkeit bietet, AD oder UT zuzuschalten. Beispiel: YouTube erlaubt aktuell nicht die Zuschaltung von AD.
In diesem Fall würden die beiden Prüfschritte eigentlich als nicht konform bewertet. Daher entschließt sich der Webseitenbetreiber, ein zweites Video anzubieten, indem UT bzw. AD bereits im Video direkt vorhanden sind, sie können nicht deaktiviert werden. In diesem Fall ist es kein Problem mehr, dass der Player die Zuschaltung nicht erlaubt hat, weil das zweite Video keine Zuschaltung benötigt.

Ob das dann als konform oder nicht anwendbar gewertet wird, finde ich nicht ganz so wichtig. Ich würde aber nach der EN-Definition für anwendbar (applicable) dazu tendieren, dass es konform ist, denn die Vorbedingungen (preconditions) wie in Annex C angegeben, sind eigentlich erfüllt.

**Comment by helmsaccess** [comment]
Zumindest separat angebotene Videos mit AD sind bereits durch den Prüfschritt 9.1.2.3 "Audiodeskription oder Volltext-Alternative für Videos" abgedeckt:

> 1. 
> Art der Einbindung feststellen. Die Audiodeskription kann auf verschiedenem Wege angeboten werden:
> ◦ 
> Die Audiodeskription ist bereits in der normalen Tonspur enthalten.
> ◦ 
> Eine weitere Version des Videos mit Audiodeskription wird angeboten. Diese Version wird geprüft. Ein funktionierender Link zu dieser Version muss im unmittelbaren Kontext des Videos angeboten werden, ebenso wie ein Zurück-Link (oder das Zurückspringen funktioniert über den Zurück-Button des Browsers).

In den Prüfschritten 9.1.2.2 "Aufgezeichnete Videos mit Untertiteln" und 9.1.2.4 "Videos (live) mit Untertiteln" finde ich keinen expliziten Hinweis darauf, dass ein separat angebotenes Video oder Live-Stream mit UT zur Konformität führt. Wenn dies jedoch in der Praxis wie in 9.1.2.3 bewertet wird und somit konform wäre, wäre die Anwendbarkeit von 7.1.1 und 7.2.1 in gewisser Weise eine Dopplung, die ich gerne vermeiden würde.

**Comment by sweckenmann** [comment]
Dass wir in der Prüf-Anleitung von 9.1.2.3 und 9.1.2.5  auf die Art und Weise eingehen, wie  Audiodescription eingebunden wird, hängt nach meinem Verständnis damit zusammen, dass klar gemacht werden sollte, _welches_ Video getestet wird, d.h. dass gegebenenfalls nicht das Standard-Video getestet wird sondern ein anderes (in einem weiteren Player). Neben dem  Vorhandensein wird ja auch geprüft, ob die Audiodescription als solche taugt. Evtl. könnte man etwas umformulieren.
Bzgl. Captions gehen wir in den alten Prüfschritten glaube ich nicht auf die Möglichkeit ein, open Captions in einem weiteren Player zu prüfen.

Ich verstehe den Sinn der neuen Anforderung nicht so ganz.
Nach WCAG 2.1 sind z.B. closed captions und open captions zur Erfüllung akzeptiert (es gibt jeweils eine Sufficient Technique). Wenn also z.B. 9.1.2.2 (Captions prerecorded) erfüllt ist, musss es ja auch ein mediaelement geben, dass sie anzeigt. Wozu brauche ich noch eine Anforderung, die sagt, das mediaelement muss captions anzeigen können? Geht es darum, dass ein nicht funktionierender CC-Button entecket werden soll? Oder muss ich prüfen, ob eine vtt-Datei eingebunden ist, aber der CC-Button nicht vorhanden ist?

Stimme Johannes Fischer zu, dass auch ein zweiter Player möglich sein sollte. 
Es gibt in der EN bei 7.1.1 zwei Prüfungen: 
> Type of assessment: Inspection, Procedure: 1. Check that there is a mechanism to display the captions.
> Type of assessment: Test 2, Procedure: 1. Check that there is a mechanism to choose to display the captions

Der erste Fall besagt, dass die captions einfach angezeigt werden können (sind hier die open captions gemeint?). Hier wäre auch _nur ein_ Player denkbar, bei dem die open captions werden (es steh ja nirgends, dass der Nutzende auch das Video ohne captions sehen können muss?). Bei Test 2 geht es dann explicit um die closed captions. Woran macht ihr fest, dass es in dieser Anforderung _nur_ um die Einbindung von Closed Captions geht? Wenn ja, dann wäre der Prüfschritt "nicht anwendbar" bei Umsetzung mit open captions. Wenn es um das Anzeigen von captions allgemein ginge, dann wäre er erfüllt.

Äquivalent dazu, würde das auch für Audiodescription gelten? Hier wäre auch ein Player denkbar, wo gleich AD mit ausgegeben wird (oder das Video wird nach Drücken des AD-Buttons im selben Player neu geladen, gabs bei "Das Erste" mal.).

**Comment by johannesFischer84** [comment]
> Wozu brauche ich noch eine Anforderung, die sagt, das mediaelement muss captions anzeigen können? Geht es darum, dass ein nicht funktionierender CC-Button entecket werden soll? Oder muss ich prüfen, ob eine vtt-Datei eingebunden ist, aber der CC-Button nicht vorhanden ist?

Ja, um diese beiden Dinge geht es. Wenn das Video eine Untertitel-Datei verwendet, muss der Player in der Lage sein, diese Untertitel zur Anzeige zur aktivieren.

> Stimme Johannes Fischer zu, dass auch ein zweiter Player möglich sein sollte.

Ein zweiter Player wäre theoretisch auch möglich. Das heißt, eine Webseite würde das Video z. B. mit dem YouTube-Player und dann nochmal mit dem Able-Player oder einfach nur mit `video`-Element (browsereigener Player) vorhalten. Wäre möglich.

Wobei ich eigentlich meinte, dass der gleiche Player zweimal genutzt wird, nur einmal die Untertitel (UT) direkt ins Bild eingebrannt sind bzw. die Audiodeskription (AD) in der regulären Tonspur enthalten ist. In diesem Fall müssen UT und AD nicht mehr gesondert aktiviert werden. Das hast du, Sonja, ja in deinem nächsten Absatz ja auch so beschrieben.

> Bei Test 2 geht es dann explicit um die closed captions. Woran macht ihr fest, dass es in dieser Anforderung nur um die Einbindung von Closed Captions geht?

Es geht um beide Formen, bei den open captions (eingebrannt / direkt sichtbar) ist die Prüfung normalerweise sowieso erfüllt.

> Äquivalent dazu, würde das auch für Audiodescription gelten? Hier wäre auch ein Player denkbar, wo gleich AD mit ausgegeben wird (oder das Video wird nach Drücken des AD-Buttons im selben Player neu geladen, gabs bei "Das Erste" mal.).

Ja, dem würde ich zustimmen. Das Beispiel mit dem Neuladen mit AD im selben Player wäre für mich so eine zweite Videoversion.

@helmsaccess Ja, eine Dopplung tritt teilweise auf. Das lässt sich aber nicht vermeiden. Auch bei den bisherigen WCAG-Prüfungen sind manche Dinge nur schwierig ohne Überschneidung zu trennen.
