### ISSUE TITLE
9.1.3.1h / 9.3.3.2 Möglichkeiten beim Umgang mit Pflichtfeldern

### ISSUE THREAD

**Issue by detlevhfischer** [BIK-BITV/BIK-Web-Test#222]
Wir hatten eine Diskussion, ob bei Formularen, die überwiegend Pflichtfelder enthalten, auch die Markierung der Nicht-Pflichtfelder (Zusatz "optional" im Label) ausreicht. (Dazu gab es bereits eine Diskussion in einem [WCAG issue](https://github.com/w3c/wcag/issues/1698).) Offen ist jedoch noch, in welchen Fällen das ansonstige Fehlen einer Auszeichnung (über `required` oder `aria-required`) dann ein FAIL von WCAG 1.3.1 (Prüfschritt 9.1.3.1h) oder WCAG 4.1.2 bedeuten würde.  Ich denke, es wäre wohl ausreichend, am Beginn des Formulars zu schreiben "Alle Felder sind Pflichtfelder, falls nicht als optional markiert", oder ähnlich. Wie ist es jedoch mit dem Fall, dass (bis auf den Zusatz "optional" bei Nicht-Pflichtfeldern) kein allgemeiner Pflichtfeld-Hinweis zu finden ist? Die Tatsache, dass ein Feld ein Pflichtfeld ist, würde dann also erst beim Abschicken über die Fehlermeldung vermittelt. Ist das ein FAIL von 1.3.1 oder 4.1.2?

Ich habe deshalb dieses [WCAG issue 1698 noch mal geöffnet ](https://github.com/w3c/wcag/issues/1698#issuecomment-953852663).

**Comment by johannesFischer84** [comment]
Ich stimme Sonja ebenfalls zu. Auch in dem Issue der WCAG Working Group geht es so hervor. Eine Kennzeichnung vereinzelter Felder als optional wäre durch den Text im `label` auch programmatisch ermittelbar.
