### ISSUE TITLE
9.2.4.6 Aussagekraft nicht sichtbarer Beschriftungen hier oder in 9.4.1.2?

### ISSUE THREAD

**Issue by detlevhfischer** [BIK-BITV/BIK-Web-Test#225]
Die Prüfschrittbeschreibung fokussiert auf sichtbare Überschriften, geht aber nicht die Frage ein, ob diese sichtbar oder versteckt sind.
Das gleiche gilt für Beschriftungen von Formularelementen, die über `aria-label` oder versteckten Text bereitgestellt werden.
Bei schlechtem Namen / programmatischen Beschriftungsinhalt (z.B. englische aria-label) würde ich das hier bei 9.2.4.6 bewerten, obwohl es nicht sichtbare Beschriftungen / Überschriften sind. Denn wo sonst? (Vielleicht ist das klar und ich bin nur gerade verwirrt). Zustimmung?
Vielleicht sollten wir 9.2.4.6 nicht nur von 9.1.3.1h (Programmatische Ermittelbarkeit) abgrenzen, sondern auch von 9.3.3.2 (Label sichtbar zugeordnet) und 9.4.1.2 (u.a. Name vorhanden)?

**Comment by sweckenmann** [comment]
Guter Punkt, ich habe nochmal nachgelesen, das SC heißt "Headings and labels describe topic or purpose."

"label" ist wie folgt definiert (d.h. label verlinkt auf folgenden Text): 
> text or other component with a text alternative that is presented to a user to identify a component within Web content.

> Note: A label is presented to all users whereas the name may be hidden and only exposed by assistive technology. In many (but not all) cases the name and the label are the same.
Note: The term label is not limited to the label element in HTML.
Quelle: https://www.w3.org/TR/WCAG21/#dfn-labels

Eigentlich stimme ich dir zu, aber die Definition von label scheint sich ja genau wie bei 9.3.3.2 auf sichtbaren Text zu beziehen? (und grenzt sich von versteckten accessible name ab)? Bei 3.3.2 wird auch auf diese Definition verlinkt. Verstehe dann allerdings nicht warum sie im ersten Satz Textalternativen erwähnen? Klickt man hier auf die Definition, wird nur von programmatisch ermittelbarem Text gesprochen. 

Es macht meiner Ansicht nach keinen Sinn, nur die Aussagekraft von sichtbaren Beschriftungen einzufordern, nicht aber von versteckten? Vielleicht eine Frage an die Working Group? 
(Die Aussagekraft von Alternativtexten würde ich aber weiterhin bei 9.1.1.1 bewerten, sonst wird es zu konfus).

**Comment by MarcHaunschild** [comment]
Lässt sich vielleicht eine Formulierung finden, die versteckte Texte dann berücksichtigt, wenn diese für Sehende nicht wichtig sind? - Ich finde es problematisch, wenn Informationen **nur** noch auf eine Art bereit gestellt werden, die Sehenden nicht zugänglich sind. Noch spielt das in der Realität kaum eine Rolle (in der Regel erhalten Blinde zu wenig Informationen) ich habe aber schon ein paar Angebote getestet, wo eine Grafik, die wie Dekoration wirkte, einen langen, informativen alt-Text hatte.
Wenn beispielsweise das Bild eines Mannes, der irgendetwas unterschreibt ein aria-label o.ä  "Konrad Adenauer, 1. Bundeskanzler der Bundesrepublik Deutschland unterzeichnet Vertrag XYZ" enthält, bekommen Sehende diese Informationen nicht.

**Comment by sweckenmann** [comment]
> Wenn beispielsweise das Bild eines Mannes, der irgendetwas unterschreibt ein aria-label o.ä "Konrad Adenauer, 1. Bundeskanzler der Bundesrepublik Deutschland unterzeichnet Vertrag XYZ" enthält, bekommen Sehende diese Informationen nicht.

- Naja, es ist ja eher so, dass DAS BILD vorgibt, was im Alternativtext steht. Nicht der Alternativtext gibt vor, was in der Bildunterschrift oder im Kontext vermittelt wird. Letzteres ist redaktionelle Entscheidung, hier können wir keinen Einfluss nehmen. Das heißt in dem Beispiel kann man vermutlich im Bild / Kontext sehen, dass es Konrad Adenauer ist, der einen Vertrag unterschreibt. Vielleicht noch Vertrag xy (im Kontext).

**Comment by MarcHaunschild** [comment]
Das Beispiel mag hinken. Ich bin überzeugt nicht jede Jugendliche würde ihn auf Anhieb erkennen, wissen dass er der erste Kanzler war und was er da unterschrieben hat.
Das sind schon konkrete Informationen und das Bild zeigt wohl auch genau das, was im zugänglichen Namen steht. Aber Stehende Menschen erfahren das doch nicht, obwohl sie auf einer Seite mit so einem Bild mit hoher Wahrscheinlichkeit über so etwas unterrichtet werden sollen.
Ein Beispiel wo das mal ziemlich extrem war, haben wir sogar gemeinsam getestet.

😉

**Comment by sweckenmann** [comment]
Ich glaube nicht, dass das Erfolgskriterium hergibt, dass wir Bildunterschriften fordern können (selbst wenn sie redaktionell sinnvoll wären). Unabhängig ob man "label" wirklich so weit fassen kann, steht in Understanding 2.4.6:

> This Success Criterion does not require headings or labels. This Success Criterion requires that if headings or labels are provided, they be descriptive.

**Comment by MarcHaunschild** [comment]
> Ich glaube nicht, dass das Erfolgskriterium hergibt, dass wir Bildunterschriften fordern können (selbst wenn sie redaktionell sinnvoll wären). Unabhängig ob man "label" wirklich so weit fassen kann, steht in Understanding 2.4.6:
> 
> > This Success Criterion does not require headings or labels. This Success Criterion requires that if headings or labels are provided, they be descriptive.

Ja, das hätte ich vor meiner Antwort noch mal durchlesen sollen. Ich dachte, da stünde etwas mit gleichwertig, zumindest in 1.1.1 - aber ich denke auch da wird man das nicht rauslesen können, so dass man es aufnehmen kann. War auch nur eine Frage, ob man so eine Formulierung finden könnte.

Letztendlich sollen ja alle Nutzer so weit wie möglich ein ähnliches Erlebnis haben in dem Sinne, dass jeder alle Informationen bekommt. Aber es gibt tatsächlich kein SC, das es verbietet sehr viel Information exklusiv an AT weiterzugeben. Vielleicht ist das einfach kein Problem, weil es in der Praxis so selten vorkommt...?!?

Wie dem auch sei: du hast sicher recht. Danke für die Ausführungen!

**Comment by stefanFarnetani** [comment]
ich sehe das wie @detlevhfischer und @sweckenmann  
9.2.4.6 beurteilt die Aussagekraft von Überschriften und Labels. Dabei ist es egal ob sichtbar oder unsichtbar. Es ist rein an diesem Erfolgskriterium auch egal, ob das label falsch verknüpft ist oder mit display: none falsch unsichtbar gesetzt wurde. Das muss dann in anderen Erfolgskriterien geprüft werden.
Und ich würde fehlende Übersetzung von arial-labels (beliebter Fehler) ebenfalls hier einordnen. 
Eine Forderung nach Gleichbehandlung von programmatischem und sichtbaren Label sehe ich auch nicht im Prüfschritt. Was nicht heißt, dass es im konkretem Fall so heftig ist, dass es ein fail ist. Aber ich würde diesen Extremfall nicht in den Prüfschritt aufnehmen, weil es auch evtl. sinnvolle Umsetzungvarianten verhindern würde.

Noch ein kurzer Exkurs:
Mir ist klar, dass das beim Testen immer verwirrend ist. gerade 9.1.1.1 hat viele Teilaspekte und vieles hängt auch mit anderen Prüfschritten zusammen. Ich überlege deshalb bei solchen Situationen immer wieder, ob wir uns in der Systematik der Prüfkatalog nicht stärker von der Erfolgskriterien lösen und sie anders sortieren sollen. Nur damit das nicht falsch verstanden wird. Weiterhin so genau wie möglich die EN oder WCAG testen. Nur aus der Praxis heraus stärker umstrukturieren. Wir haben Erfolgskriterien ja bereits in mehrere Prüfschritte aufgeteilt. Warum sie jetzt nicht noch anders sortieren. z.B. alles mit Label und Formularen hintereinander weg und alles mit Überschriften hintereinander weg.

**Comment by MarcHaunschild** [comment]
Ja, kann ich alles gut nachvollziehen.

Zur Idee von @stefanFarnetani.

Macht in der Test-Praxis Sinn. Der Bezug zur Nummerierung in der EN könnte dadurch erhalten bleiben, dass die Nummer nicht mehr vorneweg als Sortier-Kriterium aufgeführt wird, sondern nach dem Namen des Prüfschrittes in Klammern.

Aber erst mal sollte es für den Vorschlag von Stefan einen Konsens geben.

Mir würde alternativ auch reichen im Prüftool anders (womöglich nach mehreren Kriterien) sortieren zu können.

Andererseits könnte der Vorschlag von Stefan auch für die Empfänger der Testergebnisse besser verständlich sein, weshalb dann doch eine feste Umsortierung Sinn machen kann.

Ist aber ein eigener thread, oder?

**Comment by detlevhfischer** [comment]
@stefanFarnetani 
Personalisierbare Gruppierbarkeit von Prüfschritten für Prüfer kommt demnächst, mit dem neuen Prüftool.

**Comment by stefanFarnetani** [comment]
@detlevhfischer das klingt nach einem interessantem feature und ich bin gespannt. 
Ich meinte aber eine grundlegende Veränderung des Prüfkataloges.

**Comment by sweckenmann** [comment]
@stefanFarnetani Bei der letzten Angleichung des Verfahrens an WCAG haben wir die Struktur der Prüfschritte möglichst exakt an die Struktur der WCAG angeglichen. 

Der Grund: Eine der Konformitätsbedingungen sagt, dass eine Seite konform ist, wenn alle Erfolgskriterien für diese Seite mit "konform" bewertet worden sind. Wenn man nun die Struktur der WCAG als Grundlage des Prüfkatalogs nimmt, sieht man im Ergebnis genau, welches Erfolgskriterium für "nicht konformität" der Seite verantwortlich ist.
(Bei den beiden Erfolgskriterien, die mehrere Prüfschritte haben, wird das Ergebnis auch auf das Erfolgskriterium bei der Auswertung "gemappt").

Da wir Standardkonformität prüfen, finde ich es eigentlich schon gut, wenn dies so transparent wie möglich für Außenstehende deutlich wird (eben über die Struktur). Fürs Testen selbst ist eine andere Sortierung natürlich kein Problem und oft praktikabler. Das versuchen wir über die Gruppierbarkeit zu lösen.

**Comment by stefanFarnetani** [comment]
@sweckenmann wir brauchen wohl wirklich langsam einen eigenen Thread. 
Ich propagiere ebenfalls die Nähe zu den Erfolgskriterien. Aber es gibt eine inhaltliche Nähe, die nicht davon betroffen sein muss wie man den Test aufbaut. Ich kann doch Prüfschritte aufbauen, die zwei Erfolgskriterien zugewiesen sind. Beim Bericht wird dann wieder nach Erfolgskriterien aufgelistet. 
Wenn noch mehr darüber nachdenken, sollten die Diskussion verlagern. Was wäre ein geeigneter Ort? auch github?

**Comment by johannesFischer84** [comment]
> Bei schlechtem Namen / programmatischen Beschriftungsinhalt (z.B. englische aria-label) würde ich das hier bei 9.2.4.6 bewerten, obwohl es nicht sichtbare Beschriftungen / Überschriften sind. Denn wo sonst? (Vielleicht ist das klar und ich bin nur gerade verwirrt). Zustimmung?
Vielleicht sollten wir 9.2.4.6 nicht nur von 9.1.3.1h (Programmatische Ermittelbarkeit) abgrenzen, sondern auch von 9.3.3.2 (Label sichtbar zugeordnet) und 9.4.1.2 (u.a. Name vorhanden)?

Zweimal Zustimmung (analog zum Working Group Issue)
