### ISSUE TITLE
11.7 Benutzerdefinierte Farben - Buttons

### ISSUE THREAD

**Issue by pp-ernst** [BIK-BITV/BIK-Web-Test#249]
Unklar bleibt beim Abschnitt „3.2 Hinweise“ bei der Beschreibung „Der Firefox-Browser übernimmt für button-Elemente die vom Nutzer gewählte Hintergrundfarbe nicht bzw. setzt eine eigene Farbe. Dies darf nicht als Fehler bewertet werden.“ in meinen Augen noch der Aspekt, dass eine informationstragende Grafik eines Buttons durch eine ähnliche Vorder- und Hintergrundfarbe zu wenig Kontrast haben kann.
Bewerten wir so, als wäre der hellgraue Hintergrund eines Buttons die vom Benutzer definierte Hintergrundfarbe? Also wäre eine informationstragende Grafik in einem Button (z.B. Blätterpfeil eines Karussells) ohne eigenen Hintergrund ein FAIL?

**Comment by johannesFischer84** [comment]
> Also wäre eine informationstragende Grafik in einem Button (z.B. Blätterpfeil eines Karussells) ohne eigenen Hintergrund ein FAIL?

Ist das nicht auch ohne EN 11.7 ein FAIL bei der Kontrastprüfung nach WCAG 1.4.11 (oder 1.4.3)? Ich hab es aber vielleicht nicht ganz verstanden, was Sie sagen möchten.

**Comment by sweckenmann** [comment]
Ich vermute, gemeint ist der Firefox-Bug: Bei angepassten Farben wird der button ja in grau dargestellt. ein Icon kontrastiert dann evtl. nicht mehr. Aber ich denke, da kann der/die Autor/in nihchts dafür.

**Comment by johannesFischer84** [comment]
Ja, das hab ich verstanden. Kann vielleicht vorkommen und sollte dann auch nicht fehlerhaft bewertet werden. Dennoch ist es aus meiner Vorstellung heraus wahrscheinlich in vielen Fällen schon so, dass der Kontrast im Standardmodus der Webseite zu geringen Kontrast aufweist und dort mit Fehler bewertet wird.

**Comment by johannesFischer84** [comment]
In EN 11.7 geht es darum, dass die Einstellungen der Nutzenden übernommen werden. Der Kontrast ergibt sich vor allem daraus, dass Nutzende Vorder- und Hintergrundfarbe in den Browser-Einstellungen nach ihrem Wunsch auswählen. Ich würde das Ergebnis der Nutzer-Einstellung überhaupt nicht auf Kontrast bewerten, egal ob das ein Bedienelement ist, dass Firefox nicht verändert oder ob die Nutzereinstellung ist.

**Comment by pp-ernst** [comment]
Vielen Dank für die Einschätzung und die beiden Zustimmungen!

**Comment by detlevhfischer** [comment]
@pp-ernst Ich denke die Frage ist beantzwortet und das Issue kann geschlossen werden - sonst gerne wieder öffnen...
