### ISSUE TITLE
Prüfschritt 9.4.1.3 Statusmeldungen programmatisch verfügbar - aria-errormessage

### ISSUE THREAD

**Issue by sprungmarker** [BIK-BITV/BIK-Web-Test#253]
Immer öfter sehe ich jetzt nicht mehr die Umsetzung mit WAI-ARIA aria-describedby bei Fehlermeldungen, sondern aria-errormessage (in Kombination mit aria-invald auf dem Formularfeld). Bis dato wenig unterstützt

WAI-ARIA: https://www.w3.org/TR/wai-aria-1.1/#aria-errormessage
Unterstützung: https://a11ysupport.io/tech/aria/aria-errormessage_attribute

Mit Edge und JAWS konnte ich es korrekt nachvollziehen.

Wie gehen wir damit um, ist ja nur eine Browser-Screenreader-Kombination, die bis dato die Technik korrekt ausgibt?

**Comment by marcus-herrmann** [comment]
Gilt hier nicht das Argument "Ist nicht ausreichend _accessibility supported_", ggf mit Link zu https://a11ysupport.io/tech/aria/aria-errormessage_attribute?

**Comment by sweckenmann** [comment]
Meiner Ansicht würde man das noch nicht als "accessibility supported" einstufen können. 
Siehe "Understanding Conformance,[ Level of Assistive Technology Support Needed for "Accessibility Support](https://www.w3.org/TR/UNDERSTANDING-WCAG20/conformance.html#uc-support-level-head)"

Hier könnte man schon Punkt 5 heranziehen "Currently assistive technology that is affordable by the general public is often very poor" (in unserem Fall keine Unterstützung bzgl. NVDA).

**Comment by sprungmarker** [comment]
@sweckenmann ja - stimmt, wenn man nur NVDA als Voraussetzung nimmt. Gut - dann bewerte ich das entsprechend. :)

**Comment by detlevhfischer** [comment]
@sprungmarker Können wir das Issue schließen?

**Comment by stefanFarnetani** [comment]
@sweckenmann @detlevhfischer 

nichts konkret zu diesem ticket.
Aber, weil die Frage gerade aufkam. Was ist unsere Messlatte? 
Ab welchen Unterstützungsgrad betrachten wir es als "accessibility supported".
Zumindest eine Faustregel fände ich in der alltäglichen Arbeit hilfreich. Habt ihr da etwas?

Sowas wie Unterstützung in mindestens 2 der gängigsten vier 4 Browsern (aktuell: NVDA, Jaws, VoiceOver, Talkback) ...?
