### ISSUE TITLE
Kann ein select mit langen Optionen als Ausnahme für 1.4.10 (Umbruch) gelten?

### ISSUE THREAD

**Issue by detlevhfischer** [BIK-BITV/BIK-Web-Test#256]
Bei einer Prüfung einer Anwendung gibt es "offene" (mehrzeilige) `select` Elemente mit längerem, mehrgliedrigen Inhalten in den `option` Einträgen (z.B. Reisenummer, Reisender, Ort, Datum). Diese Auswahl sollte EIGENTLICH über eine Datentabelle, z.B. mit Schaltern pro Zeile, laufen, um eine schnellere nicht-visuelle Navigation (z.B. durch Datumseinträge) zu ermöglichen - aber eine solche Implementierung ist derzeit nicht machbar.
Es bleibt die Frage, ob eine solche Implementierung immer noch als "eher erfüllt" PASS von 9.1.4.10 angesehen werden kann, wenn der Inhalt in den Optionen in einer vergrößerten Ansicht (oder einer schmalen Ansicht von 320 px) horizonal gescrollt werden könnte. So wie ich das sehe, gibt es bei 1.4.10 keine normative Definition, welche Inhalte unter die Ausnahme fallen, sondern nur eine Reihe von Beispielen in der zweiten Note. Habt ihr dazu Meinung?

Ein Issue, dass ich auf WCAG GitHub dazu angelegt habe, blieb bislang ohne Antwort.
https://github.com/w3c/wcag/issues/2275

**Comment by MarcHaunschild** [comment]
Hallo Detlev,

bei einzeiligen Texten finde ich es ok, bei mehrzeiligen eher nicht.

Bin gespannt, wie die anderen das sehen.

--
Mit freundlichen Grüßen

Marc Haunschild
https://Accessibility.Consulting

**Comment by detlevhfischer** [comment]
Glücklicherweise hat sich der Kunde jetzt doch für eine Datentabelle entscheiden können - aber die grundsätzliche Frage bleibt.
Mit einzeiligen Texten meist Du wahrscheinlich: Nicht mehrere distinkte Datenelemente zusammengefassst in einer Option, sondern **eine** lange Option, vermute ich

**Comment by johannesFischer84** [comment]
Ich würde das mindestens mit "eher erfüllt", wahrscheinlich sogar mit "erfüllt" bewerten. Eine Datentabelle ist als zweidimensionaler Inhalt sowieso eine Ausnahme von WCAG 1.4.10. Eine `option`-Angabe, die über die Breite hinausgeht, würde ich auch nicht als fehlerhaft bewerten, sofern kein Umbruch über CSS einstellbar ist.

**Comment by MarcHaunschild** [comment]
Ich meine, dass eine Option nicht umbrechen und horizontal geschellt werden sollte. So kann man eine Option von vorne bis hinten lesen, ohne hin und her springen zu müssen.

Was die Verantwortung der UA-Hersteller angeht. Wir werten vieles ab, weil es von Browsern nicht korrekt umgesetzt wird. Zum Beispiel sieht der HMTL5 Standard den HTML outlining Algorithmus vor. Aber weil der in keinem Browser implementiert ist, bestehen wir auf sinnvolle Überschriftenstrukturen.
