### ISSUE TITLE
9.1.4.10 Inhalte brechen um - Mit Browser-Werkzeug testen?

### ISSUE THREAD

**Issue by sweckenmann** [BIK-BITV/BIK-Web-Test#259]
Spricht etwas dagegen, statt:

> Die Developer Tools rechts angedockt öffnen (über Funktionstaste F12, über die Tastenkombination Strg + Umschalttaste + I, oder über Menü Einstellungen > Weitere Tools > Entwicklertools) und die vertikale Abgrenzung zwischen Seiten- und Tool-Bereich ziehen, bis oben rechts im Seiten-Bereich 320px x (Viewporthöhe) angezeigt wird (wird rechts ein Scrollbalken angezeigt, 14px dazuzählen, also 334px x Viewporthöhe einstellen).

mit dem Browser-Werkzeug zu testen:

Firefox: Extras > Browser-Werkzeuge > Bildschrim-Größe testen > 320 im entsprechenden Formularfeld für die Bildschirm-Breite eingeben.

Ich würde dann die Prüfanleitung anpassen.

**Comment by detlevhfischer** [comment]
Wahrscheinlich nicht - aber man sollte es vielleicht anhand von mehreren Sites mal überprüfen, ob es doch Unterschiede gibt...

**Comment by detlevhfischer** [comment]
Vergleiche mal die mobile Ansicht 320px in Chrome über button, mit der Einstellung wie bislang beschrieben:

- https://www.erbliche-netzhauterkrankungen.de/ - Startseite sieht in den beiden Ansichten anders aus, Text läuft schmaler (wa sbei langen Worten usw, zu unterschoedliche nBeertungen führen könnte funktional keine auffälligen Unterschiede

(wird fortgesetzt)

**Comment by sweckenmann** [comment]
@detlevhfischer Warum 334px (nicht 336) - da ist doch gar kein Scrollbalken? Den Scrollbalken hatten wir ma früher mit einbezogen, als die Prüfüng über die Web Developer Toolbar (Resize Window oder Display Windwow Size (weiß nicht mehr) genacht wurde. Da erschien ein Scrollbalken. Aber in der Weise, wie es jetzt beschrieben wird, ist kein Scrollbalken zu sehen? Oder versteh ich da was nicht?

Wenn man 320px nimmt sehe ich keinen Unterschied? Wo genau?

**Comment by stefanFarnetani** [comment]
ich sehe auch keine nenneswerte Unterschiede beim Testen mit 320 px. man sollte nur bei "Bildschirmgröße Testen" "Berührungssimulation" deaktiviert halten (letztes Icon in der Leiste bei Firefox). Das aktivieren der Funktion gibt unterschiedliche Breiten des Consent-Banners bei Erbliche Netzhauterkrankung aus.

**Comment by johannesFischer84** [comment]
Ich teste schon seit Anbeginn des Erfolgskriteriums mit der Ansicht in Firefox (Die Öffnen-Möglichkeit über das Menü kannte ich noch nicht, ich habe immer die Schaltfläche in den Entwickler-Werkzeugen verwendet). Ich bin mit der Firefox-Umsetzung ganz zufrieden, habe bisher allerdings keine Vergleiche mit der Chrome-Ansicht mit breiten Entwickler-Werkzeugen gemacht.

Danke für ein paar Beispiele, Detlev. Ich habe mal die ersten beiden und das letzte ausprobiert. Bei den Netzhauterkrankungen habe ich keinen Unterschied bemerkt. Bei der Stadtreinigung Hamburg ist mir aufgefallen, dass im Fußbereich die E-Mail-Adresse nachhaltigkeit@stadtreinigung.hamburg.de im Firefox mit einem Bindestrich dargestellt wird, im Chrome dagegen nicht. Die über `body` vererbte CSS-Eigenschaft `hyphens:auto` wird wohl von beiden Browsern unterschiedlich umgesetzt. Und die Scrollbalken, die bei Zara auftauchen, werden auch von verschiedenen Browsern generell unterschiedlich dargestellt.

Aus meiner Sicht scheint keine der beiden Möglichkeiten schlechter oder besser geeignet sein als die andere. Kleinere Details scheinen mir mit der Umsetzung in den Browsern zu tun zu haben, wobei das auch in der Desktop-Ansicht zu kleinen Unterschieden führen kann.

**Comment by detlevhfischer** [comment]
@weckenmann Sollen wir dann die Prüf-Alternativen drin lassen und die Prüfung über DevTools / Mobile Ansicht (da am einfachsten) an die erste Stelle setzen?
