### ISSUE TITLE
7.1.4 Untertitel-Anpassungen - Was wird mindestens gefordert?

### ISSUE THREAD

**Issue by ThomKoeh** [BIK-BITV/BIK-Web-Test#265]
Welche Anpassungen sind bei diesem Prüfschritt denn mindestens gefordert? Die Beschreibung ist ja noch relativ schwammig. Die andere Frage ist, wo denn die Einstellungen vorgenommen werden müssen, ob direkt im Player, oder an anderer Stelle?
Freue mich schon auf Antworten. 
VG
T. Köhler

**Comment by detlevhfischer** [comment]
@ThomKoeh Wenn wir im Testschritt spezifische Einstellungen fordern, würden wir über die (schwammige) normative Anforderungen hinausgehen. Typische Einstellungen sieht man z.B. im Youtube Player, wo Schriftart, Farbe, Größe, Hintergrundfarbe, Transparenz usw, eingestel werden können, Das wird in anderen Playern anders sein. Die Minimalanforderung wäre also, dass sich **irgendeine** Eigenschaft der Untertitel anpassen lässt.
Der Ort, an dem die Einstellungen vorgenommen werden können, ist normativ nicht definiert. Wenn sich die Darstellung der Untertitel also durch browserseitige oder systemseitige Einstellungen anpassen ließe, würde ich den Prüfschritt als "erfüllt" ansehen.

**Comment by ThomKoeh** [comment]
Vielen Dank für die Antwort.

**Comment by sprungmarker** [comment]
@detlevhfischer diese Information sollte dann bitte auch im Prüfschritt erwähnt werden als Option.

> Wenn sich die Darstellung der Untertitel also durch browserseitige oder systemseitige Einstellungen anpassen ließe, würde ich den Prüfschritt als "erfüllt" ansehen.

Ich habe den Prüfschritt so verstanden, dass es nur browserseitig erfüllbar ist, nicht auch systemseitig.  Danke.
