### ISSUE TITLE
9.2.4.7 - Wie umgehen mit dem neuen Firefox-Fokus-Systemkranz (ab Version 100)?

### ISSUE THREAD

**Issue by marcus-herrmann** [BIK-BITV/BIK-Web-Test#266]
![Changed: Firefox has a new focus indicator for links which replaces the old dotted outline with a solid blue outline. This change unifies the focus indicators across form fields and links, which makes it easier to identify the focused link, especially for users with low vision.
](https://user-images.githubusercontent.com/505181/166487045-d81d843c-665e-400d-9c9a-afde17beff85.png)

Ab Version 100 (erschienen am 3.5.22) hat Firefox einen neuen Systemkranz für die Fokusdarstellung (blaue Umrisslinie statt gepunktete, 1px dicke Umrisslinie in Textfarbe). Sie wird damit deutlich robuster und dem Chrome-Fokus-Systemkranz sehr viel ähnlicher.

Wie verhält sich diesbezüglich der Prüfschritt 9.2.4.7? Ist damit die "Fokus-Stil-Verantwortung" vollends auf den User-Agent/Browser übergegangen (natürlich mit der Ausnahme einer aktiven Unterdrückung per `outline: 0` und ähnlichem)?
![Screenshot zur Demonstration des neuen Fokusstils, "Lies die Versionshinweise, um mehr über die Neuerungen in deinem Firefox zu erfahren." Versionshinweise ist fokussiert und hat eine blaue Umrisslinie aus den User Agent Style Sheets.](https://user-images.githubusercontent.com/505181/166489568-6be231c8-69f9-4350-b96c-125302a5e02e.png)

**Comment by stefanFarnetani** [comment]
@marcus-herrmann 
Wenn ich mich an die Diskussion bei Einführung des Fokusringes bei Chrome erinnere, ist das Thema Visible Focus weiterhin Aufgabe des Webseitenersteller. Und das, solange bis der Fokusring z.B. auch auf die Farbe des Hintergrundes reagiert und bei dunklem Hintergrund invertiert dargestellt wird.
Da das auch bei der Umsetzung von Firefox nicht der Fall zu sein scheint. Vermute ich, dass alles bleibt wie bisher.

Siehe auch: https://adrianroselli.com/2017/02/avoid-default-browser-focus-styles.html

**Comment by sprungmarker** [comment]
Ja, grundsätzlich stimme ich zu, aber da nun auch Firefox einen wirklich gut erkennbaren Default-Fokus hat, sollte nur noch darauf geachtet werden, ob er mit einzelnen Hintergründen in unterschiedlichen Zuständen negativ interagiert. Wenn das nicht der Fall ist, kann ich nicht fordern, dass der Fokuszustand optimiert werden sollte vom Webseitenersteller.
Und im zweiten Schritt geht es auch um die Bewertung des Prüfschritts bei Default-Fokus der Browser. Wenn der durchgängig gut erkennbar ist, dann ist der Prüfschritt auch konform - meiner Ansicht nach.

**Comment by stefanFarnetani** [comment]
@sprungmarker 
Bin ich ganz bei dir. Überarbeitung und Anpassung des Prüfschrittes: ja. Ganz wegfallen, weil in der Verantwortung des Browserhersteller: leider aktuell noch nein.

Ich habe den Text des Prüfschrittes kurz überflogen. Aktuell sehe ich keinen großen Überarbeitungsbedarf. Es sei den man will den ganzen Prüfschritt umarbeiten und den Reihenfolge das Testen abändern.
Wegfallen kann aktuell noch nichts. Auch wenn die Programmier-Teams sich stärker auf den default-fokus verlassen können, könnte ja ein eigener Fokus implementiert worden sein und muss dahingehend geprüft werden.

Nur Punkt 6 könnte in meinen Augen "positiver" formuliert werden. Das "nur" klingt unterschwellig als ob es eine schlechtere Lösung sei.

Aktuell:
> Wenn nur der Standard-Browser-Tastaturfokus (Systemkranz) erscheint, prüfen, ob dieser an dieser vor gestalteten (also etwa über CSS gefärbten) Hintergründen gut zu erkennen ist.

Vielleicht besser:
"Wenn der Standard-Browser-Tastaturfokus (Systemkranz) genutzt wird, prüfen, ob dieser an dieser vor gestalteten (also etwa über CSS gefärbten) Hintergründen gut zu erkennen ist."

**Comment by sprungmarker** [comment]
@stefanFarnetani ja, ich habe auch noch mal in den Prüfschritt geguckt, Ich sehe auch keinen Bedarf da noch was anzupassen.

**Comment by detlevhfischer** [comment]
Ist nun so umgesetzt in [9.2.4.7 2. Prüfung](https://github.com/BIK-BITV/BIK-Web-Test/blob/master/Pr%C3%BCfschritte/de/9.2.4.7%20Aktuelle%20Position%20des%20Fokus%20deutlich.adoc#1-anwendbarkeit-des-pr%C3%BCfschritts)

@marcus-herrmann Ich denke, dann können wir das Issue schließen?

**Comment by detlevhfischer** [comment]
@marcus-herrmann Falls was noch offen ist, Issue wieder öffnen...

**Comment by marcus-herrmann** [comment]
Sorry, habe die Juni-Mention an mich übersehen. Ja, kann zu. Danke!
