### ISSUE TITLE
9.4.1.2 - Name, Rolle, Wert - Neue Referenz APG

### ISSUE THREAD

**Issue by sprungmarker** [BIK-BITV/BIK-Web-Test#267]
Die bisherige Referenz zu den WAI Best Practices (https://www.w3.org/TR/wai-aria-practices-1.1/) sind ersetzt worden durch ARIA Authoring Practices Guide (APG - https://www.w3.org/WAI/ARIA/apg/).

Der Hinweis im Prüfschritt müsste entsprechend angepasst werden.

**Comment by sweckenmann** [comment]
Dank @sprungmarker. Habe den Link aktualisiert. Schließe damit das issue.
