### ISSUE TITLE
Prüfung von 9.2.1.1 bei fehlender Fokusvorhebung

### ISSUE THREAD

**Issue by cstrobbe** [BIK-BITV/BIK-Web-Test#270]
Für sehende Tastaturbenutzer hängt die Bedienbarkeit von interaktiven Elementen nicht nur von deren Erreichbarkeit und Eventlisteners ab, sondern auch von Fokusvorhebung. Auf manchen Websites gibt es keine Fokusvorhebung. Es ist in der Regel nicht schwierig, in solchen Fällen eine CSS-Regel für Fokusvorhebung zu definieren (oder das [Force Show Keyboard Focus Bookmarklet](https://pauljadam.com/bookmarklets/focus.html) aus der Werkzeugliste zu benutzen), damit man wenigstens herausfinden kann, wo sich Elemente befinden, die man prüfen sollte.

In der [Prüfschrittbeschreibung](https://webtest.bitv-test.de/index.php?a=di&iid=267&s=n) wird nichts zu Fokushervorhebung gesagt, außer, das sie Gegenstand von Prüfschritt 9.2.4.7 ist. Wäre es nicht hilfreich, unter "Allgemeine Hinweise" darauf hinzuweisen, dass auch Elemente ohne Fokushervorhebung geprüft werden sollen und das man dabei z.B. das Force Show Keyboard Focus Bookmarklet benutzen kann?

(Hintergrund: In Lehrveranstaltungen zum BITV-Test werten Studierende oft eine fehlende Fokushervorhebung als Verstoß gegen 9.2.1.1. Es ist mir allerdings bewusst, dass man im Prüfverbund den Unterschied zwischen 9.2.1.1 und 9.2.4.7 versteht.)

**Comment by detlevhfischer** [comment]
@cstrobbe Habe ich bei Anmerkungen aufgenommen, ist im nächsten Release.
