### ISSUE TITLE
9.2.4.7 Umgang mit Fokus in unsichtbaren Folien im Karussell

### ISSUE THREAD

**Issue by CarstenKaul** [BIK-BITV/BIK-Web-Test#271]
Zwecks Abstimmung mit anderen Experten: Wie geht ihr mit dem nicht sichtbaren Fokus auf ausgeblendeten Karussell-Folien um. 

In der Praxis ist es ja so, dass ein Bilder- und Nachrichtenkarussell sich automatisch weiter bewegt bis man es mit dem Tastaturfokus vom Seitenanfang beginnend erreicht hat. Bis dahin ist mittlerweile z. B. Folie 3 von 6 erreicht und man tabbt im Grunde erst  einmal die ganzen ausgeblendeten Folien durch bis man die aktuell angezeigte Folie erreicht.
Nach meiner Auslegung der BIK-Prüfbeschreibung ist das ein Mangel, weil nun ja der Fokus für längere Zeit nicht wahrnehmbar ist.

Wie bewertet ihr das? Nur in 9.2.4.3 oder redundant auch hier? Gibt es für den Webentwickler überhaupt einen guten einen Workaround dafür? Kennt wer Karussell-Mechaniken die das Problem umgehen?

**Comment by johannesFischer84** [comment]
Wenn der Fokus auf Folien gesetzt wird, die aus dem sichtbaren Bildschirmbereich geschoben wurden, ist das für mich schon ein Fehler der Fokus-Reihenfolge, WCAG 2.4.3. So bewerte ich auch Navigationsmenüs, durch die man unsichtbar tabben kann, solange sie nicht geöffnet sind. Lösen lässt es sich, indem auf die ausgeblendeten Inhalte im CSS `display:none` gesetzt wird. Dann verirrt sich niemand dorthin. Grund für meine Bewertung: Der Fokus darf meiner Meinung nach nur auf Elemente wechseln, die auch sichtbar sind. Geht der Fokus auf unsichtbare Elemente, ist die Fokussetzung falsch.

Als Fehler nach WCAG 2.4.7 würde es nur werten, wenn ein Inhalt auch dann den Fokus nicht anzeigt, wenn er sichtbar (aufgeklappt o. ä.) ist. Bei Karussells passt das vielleicht nicht ganz. Häufig sind folgende beiden Umsetzungsmöglichkeiten:
- Beim Tabben wird automatisch die nächste Folie eingeblendet. Hier könnte man den Fokus anhand der Animation evtl. erkennen. Müsste man sich im Einzelfall ansehen.
- Es wird nur die aktuell sichtbare Folie annavigiert (die anderen sind mit `display:none` ausgeblendet). Über Vor-/Zurück-Schalter kann eine andere Folie eingeblendet werden. Bezüglich der Folie müsste eine Fokus-Kennzeichnung des fokussierten Elements erfolgen. Das ist der Browser-Standardfokus, sofern dieser angezeigt wird, oder eine entwicklerseitige Lösung.

**Comment by CarstenKaul** [comment]
Danke, für die ausführliche Erläuterung. Ich nehme mal folgende Regel für mich mit: 

Ich bemängele die Fokusreihenfolge in 2.4.3, wenn sie in ausgeblendeten Ebenen weitergeführt wird. Die Fokusreihenfolge ist dann nicht logisch.  

Wird auf einem "sichtbaren" Element keine Fokushervorhebung angezeigt bemängele ich es dagegen in 2.4.7. 

Vielleicht kann/will/sollte man das in der jeweiligen Prüfschrittbeschreibung nur etwas deutlicher  klarstellen.

**Comment by MarcHaunschild** [comment]
Ja, es ist ein fail.

Es braucht keinen workaround. Die fokussierten Folien sollen in den viewport. Das ist technisch eine Kleinigkeit - es muss nur dafür gesorgt werden, dass das, was für die Mausbedienung eh schon funktioniert auch bei Fokus angewendet wird.

--
Mit freundlichen Grüßen

Marc Haunschild
https://Accessibility.Consulting

**Comment by sweckenmann** [comment]
> Wird auf einem "sichtbaren" Element keine Fokushervorhebung angezeigt bemängele ich es dagegen in 2.4.7.

Ich würde präziser sagen, das interaktive Element der Folie (z.B. Überschrift oder Call-to-action-Link) braucht eine Fokushervorhebung. 

Falls es um die Navigation der Folien geht: Es gibt Implementierungen, da fokussiert man eine Folie, bei TAB wird die nächste Folie im sichtbaren Bereich eingeblendet usw. Dies Umsetzungen haben aus meiner Erfahrung meist den Nachteil, dass beim Vor- und Rückwärts-navigieren die Darstellung meist etwas buggy ist (eine Folie wird nur halb angezeigt). Wobei ich es nicht als Fail bewerten würde, wenn nutzbar.

Ich würde die Navigation über extra Pfeil-Schaltflächen bevorzugen (auch für Tastaturnutzende). Wenn die Auszeichnung (Beschriftung etc) und die Reihenfolge der Elemente im DOM gut ist, können Nutzende die Folie dann mit den "Pfeiltasten" betreten (oder eben mit TAB, wenn sie interaktive Elemente enthält. 
Vielleicht hilft das: https://tollwerk.fyi/barrierefreie-karussells#struktur-semantik-und-beschriftung

**Comment by detlevhfischer** [comment]
@CarstenKaul Können wir das Issue schließen?
