### ISSUE TITLE
Prüfschritt 9.1.4.12  - Viewportgröße in die Prüfschrittbeschreibung?

### ISSUE THREAD

**Issue by MarcHaunschild** [BIK-BITV/BIK-Web-Test#273]
Als Prüfer möchte ich vergleichbare Ergebnisse zu anderen Prüfern. Es macht bei diesem Prüfschritt einen Unterschied, ob ich ihn auf einem 49"-Monitor in Vollbild oder einem Smartphone ausführe.
Daher finde ich eine Breitenangabe für den Viewport sinnvoll und schlage hiermit 1280 Pixel vor, was aus gutem Grund auch für den Prüfschritt [9.1.4.4 Text auf 200 % vergrößerbar](https://webtest.bitv-test.de/index.php?a=di&iid=261&s=n) gefordert wird.
Vorschlag: unter "wie wird geprüft" noch folgenden Satz ergänzen:

"Viewportbreite auf 1280 Pixel Breite einstellen"

Streng genommen müssten natürlich auch Nutzer von kleinen Bildschirmen (320px breit) oder in Kombination mit Zoom auf 200% in der Lage sein, Texte an ihre Bedürfnisse anzupassen, aber dabei würden wohl zu viele Seiten durchfallen...

## Hinweis

Es geht mir nicht darum, mit dieser Festlegung über die Anforderungen der WCAG hinaus zu gehen (da steht z.B. nicht, dass dieses SC nicht auf auf kleinen Bildschirmen gilt), sondern um die Vergleichbarkeit unserer Ergebnisse.

**Comment by MarcHaunschild** [comment]
Ja klar, @detlevhfischer mach zu. Ich mache nur Anregungen, wenn sich dafür kein Konsens findet, gerne immer schließen.
Für meine eigene Prüfpraxis nehme ich mit, dass bei diesem Prüfschritt der viewport zu vergrößern und zu verkleinern ist (was sich ja leicht und schnell machen lässt).

**Comment by RalfO99** [comment]
Die Thematik der Bildschirmauflösung für den Test diskutieren wir auch immer wieder. Meist können wir von einer geschlossenen Nutzergruppe ausgehen und kennen die Bildschirmauflösung der Standard-Monitore, die wir dann auch für den Test verwenden. Das ist für unbekannte Nutzergruppen und unterschiedliche Endgeräte so nicht möglich. Die Praxis jede Auffälligkeit zu melden und so mit den Entwicklern in den Dialog zu kommen, wenden wir auch an, das führt in vielen Fällen zu Verbesserungen.

**Comment by MarcHaunschild** [comment]
Ja, das reicht mir als Erklärung. Ich mache das ganz pragmatisch indem ich das Fenster von sehr breit (3440px) kleiner mache.
Im issue ging es mir ja um eine Festlegung, wie man prüft.
Die habe ich jetzt.
Vielen Dank!

**Comment by MarcHaunschild** [comment]
> Meist können wir von einer geschlossenen Nutzergruppe ausgehen und kennen die Bildschirmauflösung der Standard-Monitore, die wir dann auch für den Test verwenden.

Also bei mir laufen eigentlich nur Filme in der Vollbildanzeige.

Auf einem Standard-Monitor kennt ihr nur die maximale viewport-Grösse, ohne Skalierung von Schriften. Aber den Nutzen nur wenige (also Vollbild z.B. mit F11 unter Windows).

Wie viele fenste Nutzer sich neben- und übereinander anordnen oder ob sie eines in der Mitte haben usw bleibt wenn unbekannt.

Daher ist Webdesign ≠ Printdesign

Just saying...

> Das ist für unbekannte Nutzergruppen und unterschiedliche Endgeräte so nicht möglich. Die Praxis jede Auffälligkeit zu melden und so mit den Entwicklern in den Dialog zu kommen, wenden wir auch an, das führt in vielen Fällen zu Verbesserungen.
