### ISSUE TITLE
7.1.4 Untertitel-Anpassungen - Was wird mindestens gefordert?

### ISSUE THREAD

**Issue by sprungmarker** [BIK-BITV/BIK-Web-Test#274]
@detlevhfischer diese Information sollte dann bitte auch im Prüfschritt erwähnt werden als Option.

> Wenn sich die Darstellung der Untertitel also durch browserseitige oder systemseitige Einstellungen anpassen ließe, würde ich den Prüfschritt als "erfüllt" ansehen.

Ich habe den Prüfschritt so verstanden, dass es nur browserseitig erfüllbar ist, nicht auch systemseitig.  Danke.

_Originally posted by @sprungmarker in https://github.com/BIK-BITV/BIK-Web-Test/issues/265#issuecomment-1203619391_

**Comment by sprungmarker** [comment]
Im Master ist die Ergänzung bereits vorhanden 
https://github.com/BIK-BITV/BIK-Web-Test/blob/master/Pr%C3%BCfschritte/de/7.1.4%20Untertitel-Anpassungen.adoc

>Der Prüfschritt ist auch erfüllt, wenn sich die Darstellung der Untertitel nicht über Einstellungen des Video-Players, sondern durch browserseitige oder systemseitige Einstellungen anpassen lässt (wenn also etwa die Vergrößerung der Schriftgröße oder angepasste Farb-Schemata in den Browser-Einstellungen sich auf die Darstellung der Untertitel auswirken).

Danke

**Comment by sprungmarker** [comment]
Fragen: wann wird denn der Master upgedated hinsichtlich dieser Ergänzung? Danke.

**Comment by sweckenmann** [comment]
@sprungmarker Der Master müsste schon upgedated  sein. In der KW 38 werden wir ein offizielles Release schnüren, dann werden die Änderungen auch in den Prüfschritt-Beschreibungen im Tool und auf der Microsite zu sehen sein. Danke für deine Geduld.

Den derzeitigen Release Draft findest du hier: https://github.com/BIK-BITV/BIK-Web-Test/releases (es wird aber sicher noch das ein oder andere dazukommen)
