### ISSUE TITLE
Custom Tags

### ISSUE THREAD

**Issue by ThomKoeh** [BIK-BITV/BIK-Web-Test#279]
Hallo, 
wie wird denn mit Custom-Tags, wie sie zum Beispiel von Angular eingesetzt werden können, bewertet. Ein Beispiel wäre <router-outlet></router-outlet). Verhält es sich hier, wie bei den Custom-Attributen, sodass es kein Fehler ist?

**Comment by marcus-herrmann** [comment]
Ein Custom Element ist ohne weitere "Behandlung" erstmal ein `div` mit einem "schicken Namen", wie es TGPi hier nennt: https://www.tpgi.com/custom-element-semantics/ - aber es kommt deswegen unbehandelt genauso semantik-los wie ein div daher. 

In dem oben verlinkten Artikel, der trotz seines Alters korrekt ist, gibt es zwei Punkte:
* Wenn man dem Custom Element eine explizite ARIA-Rolle gibt, hat das Element dann zumindest Semantik (z. B. `<fancy-button role="button">`). Aber wie auch bei einer Verteilung einer ARIA-Rolle auf einem div/span/wasauchimmer muss man natürlich auch das einlösen, was die Rolle verspricht (Tastaturerreichbarkeit, bestimmte Tastaturevents, etc).
* Auf der anderen Seite kann man Custom Elements auch von nativen Elementen "erben" lassen, zumindest auf dem Papier (faktisch weigert sich Apple/WebKit, dies zu implementieren und hält damit den ganzen Laden auf). Stichwort hierfür ist "Type Extention", mehr Details hier: https://web.dev/customelements/#extending-elements.

Kurzfassung: Custom Elements wie `div`s sehen. Wenn ein "unbehandeltes" `div` an einer vorgefundenen Stelle die falsche semantische Wahl wäre, dann entsprechend in 9.4.1.2 behandeln. In anderen Fällen ignorieren, wie man div und span ignoriert, wenn sie irrelevant sind.

**Comment by MarcHaunschild** [comment]
Hallo Marcus;Super zusammengefasst!Ich habe noch eine Frage außerhalb der großen Gruppe.Warum hatte das Beispiel einen einleitenden backslash?Ist das so in Angular, ggfs aus Gründen? Weniger störend?Fügt der Browser ggfs im DOM dann kein öffnendes Tag hinzu (dann wäre es aber gar nichts, nicht mal ein div)?Oder war das nur komisch/ falsch „zitiert“ vom Fragesteller?--Mit freundlichen GrüßenMarc Haunschildhttps://Accessibility.ConsultingAm 13.09.2022 um 13:18 schrieb Marcus Herrmann ***@***.***>:﻿
Ein Custom Element ist ohne weitere "Behandlung" erstmal ein div mit einem "schicken Namen", wie es TGPi hier nennt: https://www.tpgi.com/custom-element-semantics/ - aber es kommt deswegen unbehandelt genauso semantik-los wie ein div daher.
In dem oben verlinkten Artikel, der trotz seines Alters korrekt ist, gibt es zwei Punkte:

Wenn man dem Custom Element eine explizite ARIA-Rolle gibt, hat das Element dann zumindest Semantik (z. B. <fancy-button role="button">). Aber wie auch bei einer Verteilung einer ARIA-Rolle auf einem div/span/wasauchimmer muss man natürlich auch das einlösen, was die Rolle verspricht (Tastaturerreichbarkeit, bestimmte Tastaturevents, etc).
Auf der anderen Seite kann man Custom Elements auch von nativen Elementen "erben" lassen, zumindest auf dem Papier (faktisch weigert sich Apple/WebKit, dies zu implementieren und hält damit den ganzen Laden auf). Stichwort hierfür ist "Type Extention", mehr Details hier: https://web.dev/customelements/#extending-elements.

Kurzfassung: Custom Elements wie divs sehen. Wenn ein "unbehandeltes" div an einer vorgefundenen Stelle die falsche semantische Wahl wäre, dann entsprechend in 9.4.1.2 behandeln. In anderen Fällen ignorieren, wie man div und span ignoriert, wenn sie irrelevant sind.

**Comment by ThomKoeh** [comment]
Vielen Dank für die Antwort!

Das heißt, dass wenn ein Custom Element Namen, Rolle bzw. Wert benötigt, muss dies (wie bei anderen nicht semantischen Elementen) mit ARIA nachgebildet werden. Ist dies nicht der Fall, dann wäre es ein Fehler.

Falls es nur zur Eingrenzung von Inhalten verwendet wird, ohne ein interaktives Element oder Strukturelement zu sein, dann wäre es bei 9.4.1.2 kein Fehler. 

Liege ich da richtig?

@MarcHaunschild habe bei der Frage das öffnende Tag vergessen...

**Comment by marcus-herrmann** [comment]
Hi @MarcHaunschild, das war oben falsch zitiert. Für Custom Elements gelten die gleichen Regeln wie für "eingeborene Elemente", mit dem Unterschied, dass die benutzerdefinierten Elemente ein Bindestrich haben müssen, die "eingeborenen" keins haben dürfen.

**Comment by marcus-herrmann** [comment]
> Das heißt, dass wenn ein Custom Element Namen, Rolle bzw. Wert benötigt, muss dies (wie bei anderen nicht semantischen Elementen) mit ARIA nachgebildet werden. Ist dies nicht der Fall, dann wäre es ein Fehler.

Japp. Die mangelnde Type Extension ist auch eines der Hemmschuhe von Web Components allgemein, bzw. eines der Hauptprobleme von "Framework-HTML". Gäbe es sie verlässlich, würde die Lage besser aussehen.

> Falls es nur zur Eingrenzung von Inhalten verwendet wird, ohne ein interaktives Element oder Strukturelement zu sein, dann wäre es bei 9.4.1.2 kein Fehler.

Nochmal japp, zumindest nach meinem Verständnis der Dinge. Dein `router-outlet` von oben ist garantiert nur "Developer Convenience", eine besondere Semantik sollte wahrscheinlich gar nicht kommuniziert werden.

**Comment by ThomKoeh** [comment]
Vielen Dank noch einmal!

**Comment by detlevhfischer** [comment]
@ThomKoeh Können wir das Issue schließen?

**Comment by ThomKoeh** [comment]
Klar vielen Dank!
