### ISSUE TITLE
cropped focus-indicator bei Test URL wg. "overflow:hidden" in container-tags

### ISSUE THREAD

**Issue by MarcusMorba** [BIK-BITV/BIK-Web-Test#284]
Auf der Seite https://studio.bitvtest.de/test/5577/listenansicht/pruefschritt/1 wird der Fokus Indicator bei der eingegebenen URL abgeschnitten, da die container-divs im CSS das Attribut "overflow:hidden" haben.

`<div class="TestSummaryView__header-content"> <h4 class="TestSummaryView__headline"> Alle Seiten </h4> <div> </div> <div> <a href="https://new.URL.org/en" target="_blank"> https://new.URL.org/en </a> </div> </div>`

Aktuelle Ansicht
![image](https://user-images.githubusercontent.com/22810698/192154093-4a7a7d21-1779-460e-a0bd-76c456bc8a25.png)

Korrekte Ansicht ohne cropping
![image](https://user-images.githubusercontent.com/22810698/192154053-8c81d159-d244-4351-b112-d2d4b5b9374e.png)

**Comment by sweckenmann** [comment]
Vielen Dank für das issue! Ich werde das an unser Entwicklungsteam weitergeben!

**Comment by sweckenmann** [comment]
@detlevhfischer Ja, das Problem ist auch schon gefixed. Ich schließe das issue.
