### ISSUE TITLE
9.2.4.1 Frage zur Bewertung

### ISSUE THREAD

**Issue by CarstenKaul** [BIK-BITV/BIK-Web-Test#289]
> Hinweis in Ziffer 3:
> Das Fehlen von Sprunglinks und die Nichtverwendung von WAI-ARIA Document Landmarks werden nicht negativ bewertet.

Dazu folgende Frage: Im Rückschluss würden fehlende semantische HTML-Bereiche immer als ein Mangel bewertet werden müssen?

> Ziffer 4:
> Erfüllt: Alle Bereiche der Seite können über Überschriften, Sprunglinks, HTML5 Elemente für Regionen und/oder WAI ARIA document landmarks erreicht und übersprungen werden

Dazu folgende Frage: Hier ist nicht klar, ob die Aufzählungen Und-  oder Oder-Bedingungen sind. Im Falle einer Oder-Bedingung wären ausreichend vorhandene Überschriften im Sinne dieser Anforderung ausreichend. Im Falle einer Und-Bedingung wäre der Hinweis in Ziffer 3 aber nicht korrekt.

> Nicht erfüllt: 
> Es gibt auf der Seite verschiedene Bereiche mit für sich nutzbaren Inhalten, diese werden jedoch weder mit Überschriften, noch mit Sprunglinks oder HTML5 Elementen erschlossen
> 
> Auf der Seite werden mehrere klar abgrenzbare Themen behandelt, es wurde aber nur pro forma eine Hauptüberschrift ausgezeichnet

Aus diesen Formulierungen lässt sich ableiten, dass wenn alle abgrenzbare Bereiche Überschriften enthalten, welche korrekt als solche ausgezeichnet sind, diese Anforderung bereits nur deshalb erfüllt wäre. Falls diese Aussage so verstanden werden soll, sind die Erläuterungen dazu missverständlich. Außerdem würde  die Anforderung Tastaturnutzende, die ohne assistive Hilfsmittel navigieren nachteilig, weil diese nicht auf kurzen Wegen in den Inhaltsbereich springen könnten?

Ich würde mir bzgl. der o.a. Interpretation der BIK-Texte eine Klarstellung in der Prüfschrittbeschreibung wünschen. Vielen Dank.

**Comment by MarcHaunschild** [comment]
Jeder Bereich muss erreichbar sein. Sei es per Überschrift oder landmark oder Sprunglink.
Ein formaler Fail ist gegeben, wenn ein oder mehrere Bereiche keine Möglichkeit bieten diese direkt anzusteuern und dadurch die anderen Bereich zu umgehen (z.B. Navigation).

**Comment by detlevhfischer** [comment]
@CarstenKaul können wir das Issue schließen?

**Comment by CarstenKaul** [comment]
Ich möchte eure Einschätzung erst noch mit der UAG Überwachungsstellen besprechen. 
Ich hatte diesen Issue dort angeregt und würde dich bitten den Issue noch bis spätestens Mitte November offen zu lassen. Danke.
