### ISSUE TITLE
12.1.1 Doku Barrierefreiheit/Kompatibilität: Details des Doku-Inhalts ausführlicher

### ISSUE THREAD

**Issue by johannesFischer84** [BIK-BITV/BIK-Web-Test#30]
Im Bereich Prüfung gibt es eine Auflistung der Informationen in der Dokumentation. Darin würde ich zunächst folgende Punkte in Frage stellen, ob man sie nicht wieder entfernt:
- Einschränkungen der Barrierefreiheit
- Auflistung von Barrieren

In der EN in dem Kriterium steht, dass beschrieben werden soll, wie Barrierefreiheitsfunktionalität und Kompatibilitätseigenschaften zu nutzen sind. Es steht aber nicht da, dass vorhandene Barrieren genannt werden soll. Oder ich interpretiere die Begriffe falsch?
Stattdessen könnten aber Alternativen für vorhandene Barrieren beschrieben werden.

Der erste Punkt, Features der Barrierefreiheit, kann aus meiner Sicht als "Sonstige Features der Barrierefreiheit" erhalten bleiben. Ich würde aber gerne mehr Beispiele für Barrierefreiheits-Funktionalität genannt haben, wie in folgender Liste:
- Vorlesefunktion
- Kontrastumschalter / Schalter für Farbschemata / Aktivierung verbesserter Maus-/Tastaturfokus
- Vergrößerungsbedienelemente
- Bedienelemente für Aktivierung anderer Textabstände
- Deaktivierung von Bewegungen oder automatischen Audios
- besondere Bedienungsarten mit Tastatur / Tastenkombinationen
- Verzeichnisse für Abkürzungen

**Comment by helmsaccess** [comment]
@johannesFischer84 Grenzen der Barrierefreiheit sollten doch Teil des Accessibility-Statements sein, oder?

> NOTE 3: The accessibility statement and help pages are both examples of the provision of product information.

Des Weiteren beeinflusst die Barrierefreiheit die Nutzung der entsprechenden Funktionen. Müsste man dies daher nicht sogar noch deutlicher im Prüfschritt erläutern?

> Sollten Inhalte ausnahmsweise noch nicht barrierefrei sein, muss das angegeben werden. Erläutern Sie umfassend, detailliert und verständlich, welche Inhalte noch nicht barrierefrei sind, nennen Sie die Gründe und, falls möglich, geben Sie Hinweise  zu barrierefreien Alternativen.

[Barrierefreiheitserklärung](https://www.bitvtest.de/bitv_test/das_testverfahren_im_detail/vertiefend/die_erklaerung_zur_barrierefreiheit.html)

Die Beispiele für Barrierefreiheitsfunktionen würde ich im Prüfschritt ergänzen.

**Comment by johannesFischer84** [comment]
> @johannesFischer84 Grenzen der Barrierefreiheit sollten doch Teil des Accessibility-Statements sein, oder?

@helmsaccess Emanuel, ja, im Accessibilty-Statement bzw. der Erklärung zur Barrierefreiheit, wie sie die EU-Richtlinie 2016/2102 und der EU-Durchführungsbeschluss 2018/1523 fordern, müssen Einschränkungen der Barrierefreiheit bzw. Barrieren natürlich genannt sein. Aber aus meiner Sicht sind das zwei Kriterien:

Das eine Kriterium ist die Anforderung in EU-Richtlinie bzw. EU-Durchführungsbeschluss. Dieses Kriterium existiert außerhalb der EN 301 549.

Und das zweite Kriterium ist 12.1.1 der EN 301 549. Aus meiner Sicht definiert dieses Kriterium nur, dass in der Erklärung zur Barrierefreiheit etwas darüber stehen muss, wie Barrierefreiheitsfunktionalität und Kompatibilitätseigenschaften zu nutzen sind.

Wenn man nun hier in 12.1.1 fordert, dass Barrieren genannt werden sollen, vermischt man meiner Meinung nach die Kriterien 12.1.1 und EU-Durchführungsbeschluss.

**Comment by helmsaccess** [comment]
@johannesFischer84 das kann ich nachvollziehen, da du in #31 die Barrierefreiheitserklärung sowieso als Beispiel aufgenommen haben möchtest, sind die Einschränkungen der Barrierefreiheit m. m. n. abgedeckt. Ich erstelle mal einen entsprechenden Pull-Request.
