### ISSUE TITLE
Testen mit verschiedenen Auflösungen

### ISSUE THREAD

**Issue by choessle** [BIK-BITV/BIK-Web-Test#304]
Je nach Auflösung eines Endgerätes oder gesetztem Zoom im Browser können sich die dargestellten Inhalte einer Seite und somit beispielsweise auch die Tastaturbedienung (z.B. mobile Navigation) unterscheiden. Wenn ich es richtig sehe, berücksichtigt das der BTIV-Test bislang nicht bzw. wird nicht darauf eingegangen, was vielleicht auch daran liegt, dass die WCAG auch nicht darauf eingeht. In den meisten Prüfschritten im BITV-Test heißt es zu Beginn der Prüfung "Seite im Firefox Browser aufrufen" oder "Seite im Chrome Browser aufrufen". Die zu setzende Fenstergröße wird nicht genannt und somit können sich die Ergebnisse bzw. die Bewertung eines Prüfschrittes unterscheiden.

An dieser Stelle wäre es aus meiner Sicht von Vorteil immer auch eine bestimmte Fenstergröße für den Browser im Prüfschritt anzugeben oder mit mehreren Fenstergrößen zu testen, damit die Ergebnisse vergleichbarer werden. Alternativ wäre ein Hinweis in den jeweiligen Prüfschritten gut, der angibt, dass mit unterschiedlichen Fenstergrößen getestet werden sollte. Wurde hierüber bereits diskutiert?

**Comment by johannesFischer84** [comment]
Diskutiert (wenn auch nicht ausführlich) wurde dazu meines Wissens nach schon bezüglich WCAG-Kriterium 1.4.12, siehe Issues #28 und #273.
Die WCAG geben tatsächlich kein Format an, denn Anforderungen beziehen sich nach dem [Konformitätskriterium 2 Full pages](https://www.w3.org/TR/WCAG/#cc2) immer auf komplette Seiten. Dort wird in der letzten NOTE auch erwähnt, dass die unterschiedlichen Viewport-Größen ("screen sizes") zu berücksichtigen sind.
Im [BITV-Test in der Beschreibung des Prüfverfahrens, Punkt 4 Beschreibung des Prüfverfahrens](https://bitvtest.de/bitv_test/das_testverfahren_im_detail/verfahren.html#c84) wird zumindest in 4.1 in der Liste, was zum Prüfgegenstand gehört, auch auf mobile Ansichten bzw. ein responsives Design als zugehörig zur Prüfung hingewiesen.

**Comment by choessle** [comment]
Alles klar, danke für die Rückmeldungen. Mir war nicht mehr bewusst, dass dieser Punkt bereits innerhalb der Erläuterungen zum Prüfverfahren genannt wird.

Wäre es hier vielleicht dennoch sinnvoll, diesen Hinweis zusätzlich noch direkt in die Prüfschritte mit aufzunehmen? Beispiel: "Die Seite im Firefox aufrufen (auch mobile Ansichten prüfen)."

**Comment by detlevhfischer** [comment]
> "Die Seite im Firefox aufrufen (auch mobile Ansichten prüfen)."

Da das bei vielen Prüfschritten ergänzbar wäre, würde es die Texte zusätzlich aufblähen. Deswegen weiß ich nicht, ob die explizite Nennung so sinnvoll wäre.

@choessle Können wir das Issue schließen?

**Comment by detlevhfischer** [comment]
Ich schließe dieses Issue, @choessle - bei Bedarf wieder öffnen.
