### ISSUE TITLE
11.7 Benutzerdefinierte Einstellungen - Konkretisierung der Prüfschritt-Beschreibung

### ISSUE THREAD

**Issue by sweckenmann** [BIK-BITV/BIK-Web-Test#309]
Im Folgenden der Input von @pp-ernst, den ich für ihn hinsichtlich einer Konkretisierung der Prüfschritt-Beschreibung hier zur Diskussion stellen darf. Ich werde im Anschluss ein PR erstellen.

**1. Schriftgröße**

1. nur bewerten, ob sich die Schriftgröße verändert.
2. beim Testen auch die Mindestschriftgröße berücksichtigen.
3. Hinweis von Sepp: Es sollte definiert werden in welchen Browsern getestet wird. Eine entsprechende Funktion gibt´s ja in CH/FF und Edge.

Erläuterung: da keine Angaben in der Anforderung stehen, welche Schriftgröße gefordert wird und es auch noch die Zoom- und 
Textvergrößerung-Funktion der Browser gibt, kann man keine Schriftgröße vorschreiben. Irgendwann zerreißt es jedes Layout.

**2. Schriftart**

1. wenn sich die Schriftart nicht ändert, negativ bewerten.

**3. Farben**

1. wenn informationstragende Inhalte verschwinden, zum Beispiel weil sie als CSS-Hintergrundgrafiken eingebunden sind, negativ bewerten. 
Zu informationstragenden Inhalten würde ich alles außer dekorative und redundante Elemente rechnen. Redundante Elemente sind zum Beispiel ein Briefsymbol gemeinsam mit dem Text „Kontakt“ in einem Bedienelement.
3. wenn Texte Vorder- oder Hintergrundfarbe nicht ändern, negativ bewerten.
4. wie wir das Verhalten bei Buttons bewerten sollen, kann ich nicht sagen. Das Verhalten je nach Art der Grafik oder anderer Faktoren ist zu undefiniert, komplex oder nicht nachvollziehbar. Im Zweifelsfall ignorieren und nicht negativ bewerten.
5. wenn Grafiken aufgrund von einem transparenten Hintergrund (zum Beispiel Logos) je nach gewählter Hintergrundfarbe nur noch schlecht sichtbar sind (Kontrast unter 3,0:1) ist die Lage auch komplex. Manche Grafiken übernehmen die benutzerdefinierte Vordergrundfarbe, manche nicht. Wenn man das negativ bewertet, würde man die Art der Grafiken, die die Vordergrundfarbe nicht übernehmen, per se als nicht barrierefrei ausschließen. Auf der anderen Seite ist es für Nutzer, die einen dunklen Hintergrund benötigen, eine große Barriere, wenn eine schwarze Schrift auf schwarzem Hintergrund dargestellt wird. Ich kann mich für keine Variante entscheiden.

**Comment by sweckenmann** [comment]
Bzgl. Farben sehe ich es ähnlich wie @johannesFischer84 siehe #305 

> Neben der Übernahme der Einstellungen bin ich dafür, dass man bei nicht mehr bedienbaren, nicht mehr lesbaren, nicht mehr wahrnehmbaren wichtigen Elementen eine Nicht-Konformität feststellt. Ausnahmen sind Browsers-Bugs. Zum Beispiel hatten wir mal festgestellt, dass die Hintergrundfarbe bei -Elementen im Firefox browserseitig nicht richtig übernommen wird (Ich habe nicht geprüft, ob das aktuell noch so ist).

In der Praxis sind mir hier aufgefallen:
- Hamburger-Icon
- Formularelemente und deren Zustände (radio-inputs, checkboxen).

In beiden Fällen kann man das Problem durch Nutzung von SVGs und CSS (current color) Probleme vermeiden.
Siehe auch https://www.sarasoueidan.com/blog/inclusively-hiding-and-styling-checkboxes-and-radio-buttons/

> One of the many benefits of using an inline SVG is that we have real elements (checkmark and square) with real borders (strokes) that we can flexibly style, so we don’t rely on background images and colors alone to create and convey state/behavior, because background images, colors, and effects like drop shadows are normally overridden in user-controlled environments. This is also why I normally recommend using a real outline versus a fake outline created using box-shadow.

Das funktioniert wohl nicht, wenn das Hamburger-Icon eine andere Farbe hat, als mit currentColor zugewiesen werden kann. Aber in den meisten Fällen wohl schon.

**Comment by MarcHaunschild** [comment]
Das mit dem currentColor ist auch einer der Tipps, den ich gebe, wobei es auch eine andere sehr einfache Möglichkeit gibt: man kann Vordergrund und Hintergrund festlegen und dann sind die Symbole in jedem Fall erkennbar. Es ist zwar dann bei eigenen Farben nicht so schön, aber erstens muss es gar nicht schlecht sein, wenn icons auf diese Weise auffälliger werden und zum anderen tut es der Bedienung keinen Abbruch.
Dieses vorgehen lässt sich zudem auch unabhängig von svgs z.b. bei gifs und pngs umsetzen.

**Comment by detlevhfischer** [comment]
@sweckenmann Du könntest dazu wohl einen PR auf meinen älteren PR https://github.com/BIK-BITV/BIK-Web-Test/pull/226 machen.

**Comment by sweckenmann** [comment]
Wir haben einen PR #328  gemacht. Hoffe das passt so. Wenn es keine Einwände gibt, würden wir ihn diese Woche noch mergen, damit er ins Release zum Wochenende mitkommt.
