### ISSUE TITLE
7.1.4 Untertitel-Anpassungen: mehr ein Feature als eine Hilfe zur Barrierefreiheit

### ISSUE THREAD

**Issue by Supportic** [BIK-BITV/BIK-Web-Test#319]
https://ergebnis.bitvtest.de/pruefschritt/bitv-20-web/7-1-4-untertitel-anpassungen

Die einzige Frage, die ich zu diesem Prüfschritt habe, ist, wieso dieser existiert?
Wenn wir davon reden das Internet für Menschen mit Einschränkungen zu verbessern, dann gilt das bei **Videoplayern** hauptsächlich für Menschen die 1) gehörlos oder 2) farbenblind oder beides sind.

Warum sollte es Pflicht sein (bemessen nach Bewertungskriterien) die Untertitel nach belieben einstellen zu können?
Was hat ein gehörloser Mensch davon, wenn die Untertitel gelb, grün, fett, unterstrichen, ... sind?
Was hat ein farbenblinder Mensch davon? Schwarz-Weiß hat schon immer funktioniert.

Hier sollte die Regel nicht die Einstellungsmöglichkeit bewerten, sondern die eigentliche Darstellung in einer leserlichen Form für Menschen mit Einschränkungen wie beispielsweise zu kleiner Text, oder zu transparenter Hintergrund, welche vom Entwickler festgelegt wurden.

Wenn man im Prüfschritt unter "Warum wird das geprüft?" schaut:
> Bei Videos mit Untertiteln ist es für Untertitel-Nutzende hilfreich [...]

dann liest man eigentlich schon, dass es nur **hilfreich** ist. Genauso hilfreich wie für jeden anderen, aber keine wirklich unterstützende Maßnahme für Menschen mit Einschränkungen.

Bitte eure Meinungen und evtl. ein paar open-source Videoplayer (außer Youtube) die das Einstellen von Untertiteln ermöglichen.

**Comment by mitchellevan** [comment]
Es ist wahr, dass die Untertiteleinstellungen jedem mit oder ohne Behinderungen helfen (so wie es physische Rampen tun). Die Untertiteleinstellungen sind eine besondere Hilfe für eine Person, die sowohl ein eingeschränktes Sehvermögen als auch ein eingeschränktes Hörvermögen hat. Diese Kombination von Einschränkungen wird mit zunehmendem Alter (z. B. über das 60. oder 70. Lebensjahr hinaus) immer häufiger.

Ich weiß nicht, wie diese genaue Liste von Farben und Textstilen ursprünglich festgelegt wurde. Aber ich weiß, dass sie in den Vereinigten Staaten als [Anforderungen für das Rundfunkfernsehen](https://www.fcc.gov/display-closed-captioning-equipment) begannen. Die Federal Communication Commission (FCC) wendete später die gleichen Anforderungen auf webbasierte Videoplayer an. Und heute haben wir die Normen, die zwischen den USA und Europa harmonisiert sind.

Noch ein Videoplayer, der diese Untertiteleinstellungen unterstützt, ist Able Player. https://ableplayer.github.io/ableplayer/demos/local-de.html

**Comment by detlevhfischer** [comment]
> Die einzige Frage, die ich zu diesem Prüfschritt habe, ist, wieso dieser existiert?

Die banale Anwort ist, dass er existiert, weil er in der EN 301 549 in Annex A Tabelle A1 als anwendbar aufgeführt wird und wir alle auf HTML-Inhalte anwendbaren Prüfschritte der EN prüfen.

Dass Untertitel-Anpassungen für manche Nutzer nicht nur hilfreich, sondern ggf. auch notwendig sind, hat @mitchellevan  oben ausgeführt.

@Supportic  Können wir das Issue schließen?

**Comment by Supportic** [comment]
Okay, danke euch @detlevhfischer @mitchellevan 

> Die Untertiteleinstellungen sind eine besondere Hilfe für eine Person, die sowohl ein eingeschränktes Sehvermögen als auch ein eingeschränktes Hörvermögen hat. Diese Kombination von Einschränkungen wird mit zunehmendem Alter (z. B. über das 60. oder 70. Lebensjahr hinaus) immer häufiger

Das hatte ich nicht mit bedacht.
