### ISSUE TITLE
12.2.4 Barrierefreie Dokumentation: Prüfung ergänzen

### ISSUE THREAD

**Issue by johannesFischer84** [BIK-BITV/BIK-Web-Test#32]
Außer dem Unterabschnitt Hinweise ist der Abschnitt zur Prüfung noch leer. Ich könnte mir (teils analog zu 12.1.2) folgende Punkte vorstellen:

1. Vom Support bzw. von der geprüften Stelle Dokumente/Links zu Webdokumenten anfordern, die vom Support an den Nutzer ausgegeben werden können.
2. Wenn die Dokumentation (auch) im HTML-Format vorliegt, ist dieser Prüfschritt erfüllt, wenn sämtliche anwendbaren Prüfschritte des Verfahrens mit dem Ergebnis konform durchlaufen wurden.

Bei den Hinweisen könnte man ggf. ergänzen, dass bei umfangreicher Dokumentation wie bei der Seitenauswahl eines Webauftritts ebenso eine Auswahl der zu prüfenden Dokumentation vorgenommen werden muss.

**Comment by detlevhfischer** [comment]
Ich denke, die Formulierung "Documentation provided by support services shall be made available in at least one of the following electronic formats..." kann man so interpretieren, dass der Prüfschritt nur anwendbar ist, wenn die Website tatsächlich Dokumentation bereitstellt - also etwa eine Web-Anwendung, die eine PDF-Anleitung oder Eine HTML-basierte Hilfe anbietet. 
Zurzeit steht im Entwurf bei Anwendbarkeit: immer anwendbar. Ich denke, das ist nicht haltbar. Wenn ein Angebot keine offensichtliche Dokumentation bereitstellt, die sich auf die technische Nutzung, den Umgang mit dem Angebot bezieht, wäre dieser Prüfschrtt nicht anwendbar. Er wäre wohl auch nicht anwendbar, wenn das Angebot ein FAQ zu **inhaltlichen** Fragen enthält.
Wenn HTML-Dokumentation bereitgestellt wird, sollte dies bei der Seitenauswahl bereits berücksichtigt werden, damit solche Hilfsseiten als normaler Teil des Angebots mitgetestet werden. 
Die Idee, als Teil eines Tests von der geprüften Stelle Dokumente anzufordern, scheint mit durch die Anforderung selbst nicht gedeckt. Es würde jede Prüfung natürlich auch deutlich erschweren - vor einer realistischen Kostenschätzung müsste dann erstmal die Anforderung an Support-Dokumente ergehen, diese eingesehen werden, usw.

**Comment by johannesFischer84** [comment]
@detlevhfischer Mit deinen Änderungen über Pull-Request #37 würde sich meine Anmerkung erledigen.

**Comment by helmsaccess** [comment]
Die Änderungen aus dem PR #37 wurden übernommen.
