### ISSUE TITLE
Situation 1: nach denhttps://github.com/BIK-BITV/BIK-Web-Test/issues/320#issuecomment-1434829900_ Artikeln kommt eine Liste mit der Überschrift „weitere News“

### ISSUE THREAD

**Issue by Jeffreyk57** [BIK-BITV/BIK-Web-Test#324]
Situation 1: nach den Artikeln kommt eine Liste mit der Überschrift „weitere News“
Situation 2: das Problem ist mir auch als erstes eingefallen 

alles in allem finde ich, dass es hier keine echte Barriere gibt. Man kennt dieses pattern von vielen Webseiten und außer der nicht erfüllten Erwartung passiert hier nichts. Dass hier irgendeine Information nicht zugänglich ist, kann ich nicht sehen.

ich würde es dennoch nicht als erfüllt ansehen und es als eher erfüllt bestehen lassen.

bin gespannt, wie es andere sehen und welche Entscheidung bezüglich einheitlicher Bewertung gefällt wird.

PS: „ich denke ich an die Entwickler“ ist zwar nett von dir, aber ob es für Entwickler bequem ist, ist für die Bewertung, ob das Ergebnis für Nutzer barrierefrei ist, natürlich nicht wirklich von Bedeutung.

_Originally posted by @MarcHaunschild in https://github.com/BIK-BITV/BIK-Web-Test/issues/320#issuecomment-1434829900_

**Comment by detlevhfischer** [comment]
Ich schließe dieses Issue, da die Diskussion in #320 stattfindet....
