### ISSUE TITLE
9.1.4.12 Textabstände anpassbar - Bookmarklet unterschiedlich

### ISSUE THREAD

**Issue by sprungmarker** [BIK-BITV/BIK-Web-Test#336]
eine kurze Rückfrage - das Bookmarklet "Textabstände anpassen" unterscheidet sich auf den Seiten:

- [Bookmarklets](https://www.bitvtest.de/bitv_test/das_testverfahren_im_detail/werkzeugliste/bookmarklets.html)
- [Werkzeugliste](https://www.bitvtest.de/bitv_test/das_testverfahren_im_detail/werkzeugliste.html) - > verlinkt auf das Codepen-Bookmarklet (https://www.html5accessibility.com/tests/tsbookmarklet.html)

Das ist wohl ein Update ist, um das Bookmarklet auch auf iframes anzuwenden.

Wäre vielleicht gut, wen man das vereinheitlicht oder? Danke.

**Comment by Andreas-Englisch** [comment]
Das mit den iFrames ist nicht der einzige Unterschied. Ein weiterer ist, dass per style-Attribut beim ersten jedem Element die Textabstände inline zugewiesen werden und somit eine höhere Priorität haben. Beim Bookmarklet https://www.html5accessibility.com/tests/tsbookmarklet.html wird lediglich am Seitenanfang das CSS eingefügt, welches somit durch Inline-Styles unwirksam werden kann.

**Comment by sprungmarker** [comment]
Danke für die Info :)
Aber angleichen sollten man die Verlinkungen dennoch - denke ich.

**Comment by detlevhfischer** [comment]
Ist angeglichen und erledigt. Danke für den Hinweis.

**Comment by MarcHaunschild** [comment]
Macht es denn Sinn, dass die Änderungen in-line notiert werden?
Hier soll doch nicht nur geprüft werden, wie das dann aussieht, sondern auch ob sich Änderungen auswirken.
Welcher Nutzer hat denn die Möglichkeit in-line Styles zu schreiben?
Plugins, die ich kenne, fügen die meines Wissens nicht auf diese Weise ein...

**Comment by Andreas-Englisch** [comment]
@MarcHaunschild 
Ja, das macht Sinn, da die guten Tools das CSS der Seite überschreiben, egal wie es notiert ist. 
Falls sie es nicht tun, dann ist das m.E. kein Verstoß gegen 1.4.12, da hier ja nur geprüft wird, ob nach Anpassung alle Inhalte korrekt sichtbar sind. Es wird nicht geprüft, ob die Anpassung an sich funktioniert. D.h. wenn ein Tool Dinge nicht anpassen kann, ist das auch in Ordnung. Das Bookmarklet versucht aber das bestmögliche Tool zu simulieren, welches möglichst viele Inhalte anpassen kann.

**Comment by MarcHaunschild** [comment]
@Andreas-Englisch ja, logisch. Danke.
