### ISSUE TITLE
Anforderung an BITV Konforme Verlinkung von Bildern - 9.1.1.1a

### ISSUE THREAD

**Issue by benjaminkott** [BIK-BITV/BIK-Web-Test#343]
Ich bin mir nicht sicher ob dieses der Korrekte platz dafür ist, 
aber mir wurde geraten mich bei Fragen / zum BITV Test / 
Prüfschritten an dieses Repository zu wenden.

Um etwas Kontext zu bieten, handelt es sich hier um 
Bilder mit Title, Alternativ Text und Beschreibung. 
Diese Bilder werden wahlweise einzeln, oder als Galerie 
in den Kontext der Seite eingebettet. Diese können von
einem Text begleitet werden, müssen es aber nicht.

Die Bilder werden wie gewohnt ausgezeichnet und als Figure 
bereit gestellt, wie erwähnt mit Title, Alternativ Texten 
und Beschreibung (Caption) sofern vorhanden.

Hier ein Beispiel wie ein unverlinktes Bild innerhalb vom 
Content gerendert wird. Da es nicht um den exakten content 
der Attribute geht habe ich diese mit ### Markern als 
Platzhalter versehen.

```html
<figure>
    <picture>
        <source
            media="(min-width: 1400px)"
            srcset="733d86bd49.jpg 1x"
            >
        <source
            srcset="6265870c06.jpg 1x"
            >
        <img loading="lazy"
            src="6a06adfe67.jpg"
            width="461"
            height="345"
            intrinsicsize="461x345"
            title="###TITLE_OF_IMAGE###"
            alt="###ALT_OF_IMAGE###"
            >
    </picture>
    <figcaption class="caption">###CAPTION_OF_IMAGE###</figcaption>
</figure>
```

Bei Verlinkungen sind wir bisher hergegangen und haben das `<a>`
um das `<picture>` Element gelegt. Hierbei haben wir nicht unterschieden
ob sich um einen direkten Link, oder einen Link welcher zusätzlich
das normale verhalten unterbindet und mit JavaScript eine Lightbox 
öffnet um eine größere Version des Bildes anzuzeigen.

```html
<figure>
    <a title="###TITLE_OF_LINK###">
        <picture>
            ...
        </picture>
    </a>
    ...
</figure>
```

Es geht hierbei nun um die Korrekten Inhalte für Title und 
Alternativ Texte für die Links und Bilder.

Während es bisher keine Anmerkungen zu normal verlinken Bildern
gab, wo der Titel des Links sich immer am Link orientiert hat
und der Titel des Bildes als auch der Alternativ-Text am 
jeweiligen verwendeten Bild. 

Beispiel: 

```html
<figure>
    <a href="###SOMEURL###" title="Navigate to: Article XYZ">
        <picture>
            ...
            <img loading="lazy"
                title="Elephant by Pablo Picasso"
                alt="Elephant at sunset"
                >
        </picture>
    </a>
    <figcaption class="caption">An elephant at sunset</figcaption>
</figure>
```

```html
<figure>
    <a href="###LINK_TO_IMAGE###" title="Elephant by Pablo Picasso">
        <picture>
            ...
            <img loading="lazy"
                title="Elephant by Pablo Picasso"
                alt="Elephant at sunset"
                >
        </picture>
    </a>
    <figcaption class="caption">An elephant at sunset</figcaption>
</figure>
```

Nun gab es bei einer Prüfung jedoch Anmerkungen das bei der Lightbox 
Variante die Alternativ Texte des Bildes anzupassen sind, mit der
Begründung das es sich nun um "Functional Images" handelt.

https://www.w3.org/WAI/tutorials/images/functional/

Somit müssten die Alternativ-Texte des Bildes angepasst werden.

Beispiel:

```html
<figure>
    <a href="###LINK_TO_IMAGE###" title="Elephant by Pablo Picasso">
        <picture>
            ...
            <img loading="lazy"
                title="Elephant by Pablo Picasso"
                alt="Show larger version of Image: Elephant at sunset"
                >
        </picture>
    </a>
    <figcaption class="caption">An elephant at sunset</figcaption>
</figure>
```

Ich muss gestehen das ich der Argumentation nicht folgen kann,
und suche hier um Rat bzw Klärung und einer Handlungsempfehlung.

Das Internet gibt hierzu leider nur wenig informationen her,
beziehungsweise folgt dieser Empfehlung nicht.

Ich hoffe das mich hier jemand aufschlauen kann, was hier
die Empfohlene vorgehensweise ist.

Sonnige Grüße
Benjamin

**Comment by benjaminkott** [comment]
CC: @marcus-herrmann

**Comment by mtelgkamp** [comment]
Es stellt sich die Frage, ob es anhand der Information aus [Technique H33: Supplementing link text with the title attribute](https://www.w3.org/WAI/WCAG21/Techniques/html/H33.html) ausreichen würde im `a` Tag das title Attribut zu nutzen `title="Show larger version of Image"`. Wenn man sich nur an die Technique hält, müsste es ausreichen. Aber die Browserunterstützung für das `title` Attribut ist nicht ausreichend. Deshalb sollte das title Attribut vermieden werden (siehe auch ["Note" bei 3.2.6.1 The title attribute](https://html.spec.whatwg.org/multipage/dom.html#the-title-attribute) und [Accessibility concerns](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/title#accessibility_concerns)). Ich würde eine Alternative vorschlagen.

Der Link kann mit einem `aria-label="Show large version of Image: Elephant at sunset"` beschriftet werden, dann kann das `alt` Attribut beim Bild selbst unverändert bleiben.

Zusätzlich ist nach meinem Verständnis das interaktive Element das eine Lightbox öffnet ein `button` (oder ein `a` Tag mit der `role="button"`), da durch die Nutzung nur eine Aktion auf der Seite selbst ausgeführt wird und keine neue Seite geöffnet wird.

**Comment by benjaminkott** [comment]
@mtelgkamp Kurze Ergänzung:

Mit der Lightbox wird hier das Standard Verhalten des Browsers "enhanced". Wenn der Nutzer den Link in einem neuen Tab öffnet bekommt er das Bild ohne Lightbox direkt im Browser angezeigt. Dieses Verhalten soll wenn möglich erhalten bleiben somit denke ich nicht das die Umstellung auf einen `<button>` hier hilfreich währe. Dieses würde dann entfallen und wir sind dann komplett vom JS abhängig an der Stelle.

**Comment by stefanFarnetani** [comment]
Hallo @benjaminkott 

um auf deine Anfangsfrage einzugehen.
Generell ist hier nicht das richtige Forum für Umsetzungsfragen in einem konkreten Projekt. In diesem Repository geht um Fragen rund um die Weiterentwicklung des BIK BITV Test; z.B. wie Prüfschritte ausgelegt und Situationen bewertet werden.

Danke auch für die Frage im [Accessibility Slack Kanal von TYPO3](https://typo3.slack.com/?redir=%2Fmessages%2FC108Q9E2C%2F), dort ist die Frage besser platziert und wir können auf die technischen Besonderheiten von TYPO3 genauer eingehen.

Dort triffst du, neben anderen, auch wieder auf @mtelgkamp und mich aus dem [Accessibiltiy Team von TYPO3](https://typo3.org/community/teams/accessibility). Die Welt ist klein ;)

**Comment by marcus-herrmann** [comment]
Hallo alle,

als Umsetzungsfrage ist das auch nicht gemeint, diese klären wir in einem Projekt mit einem gemeinsamen Kunden. Ich hatte @benjaminkott auf diese Issues hingewiesen, da ihm die Frage nach der Prüfpraxis ungewöhnlich erscheint, mein Ratschlag war aber (minus `aria-label`) exakt der von @mtelgkamp (inklusive `title`-Nuance, auch an anderen StelleN)

**Comment by benjaminkott** [comment]
Hallo alle,

wie @marcus-herrmann bereits schrieb geht es mir darum zu verstehen wie das Regelwerk ausgelegt ist. Ich habe versucht das Beispiel soweit zu reduzieren das wir hier eine Situationsbewertung anhand der Prüfschritte diskutieren können. 

Für das Projekt haben wir bereits eine Lösung, wenn es für diesen Case eine Generelle Auslegung gibt - wird diese natürlich aus Handlungsempfehlung gewertet und weitere Optimierungsschritte im Framework in unserem fall "TYPO3" beeinflussen.

Grundsätzlich stimme ich aber mit der Bewertung als "**Functional Image**" (https://www.w3.org/WAI/tutorials/images/functional/)  nicht zu, was bedeuten würde das wir den alt Text des Bilden anpassen müssten. Dieses fühlt sich in dem Kontext in dem wir uns befinden als falsch an.  Da wir die Funktionalität des Links bewerten und nicht die des Bildes.

Die Vorschläge die @mtelgkamp gebracht hat, sind für mich vollkommen nachvollziehbar und akzeptabel, und beziehen sich jeweils auf den Link und nicht das umschlossene Bild.

**Anpassung Link Title**
Wurde abgelehnt, da es nicht alle Browser korrekt auswerten wie Michael bereits geschrieben hat.

**Anpassung Aria-Label**
Wurde abgelehnt, da es sicht wie beschrieben um per definition um ein Functional Image handelt wo der Alternativ Text des Bildes angepasst werden muss.

Optionen wie `aria-role="button"` wurden bisher nicht besprochen.

Es scheint hier also Spielraum zu geben, was also für den einen Prüfer ok ist, geht bei dem anderen nicht durch.

Wie ich @mtelgkamp bereits per DM geschrieben habe, geht es mir hierbei darum zu definieren was "**Richtig**" ist, und einen Präzedenzfall zu schaffen auf den sich bei weiteren Bewertungen bezogen werden kann. Damit andere diesem Beispiel folgen können. Damit die Auslegung 100% eindeutig ist und keinen Spielraum zulässt.

Sprich XYZ ist die Empfehlung, ZYX ist ebenfalls zulässig.

**Comment by sweckenmann** [comment]
Ich möchte die Diskussion mal auf eine allgemeinere Ebene heben, weil mir scheint, dass du grundsätzlich die Unterscheidung "functional image" und "image" in Frage stellst?

Ich zitiere aus der WCAG (normativer Text des Erfolgskriteriums):

> All non-text content that is presented to the user has a text alternative that serves the equivalent purpose, except for the situations listed below.
>**Controls, Input**
If non-text content is a control or accepts user input, then it has a name that describes its purpose. (Refer to Success Criterion 4.1.2) for additional requirements for controls and content that accepts user input.)
[...]

**Comment by mtelgkamp** [comment]
Ich glaube die zugrundeliegende Frage ist, wie der Linkzweck (purpose) ausreichend beschrieben werden kann.
Was passiert, wenn der Link mit einem `title` attribut angereichert wird oder einem `aria-label` beschieben wird? Ist das Bild dann immer noch als funktionales Bild zu sehen und benötigt ein entsprechendes `alt` Attribut?

Nach meinem Verständnis ist es ausreichend wenn das interaktive Element für assistive Technologien den entsprechenden Textcontent enthält. Dafür gibt es verschiedene Varianten:
- Das alt Attribut vom Bild wird angepasst (siehe [Example 1](https://www.w3.org/WAI/tutorials/images/functional/#example-1-image-used-alone-as-a-linked-logo))
- Zusätzlich zum Bild gibt es innerhalb vom Link noch Text (siehe [Example 2](https://www.w3.org/WAI/tutorials/images/functional/#example-2-logo-image-within-link-text) und [Example 3](https://www.w3.org/WAI/tutorials/images/functional/#example-3-icon-image-conveying-information-within-link-text))
- ein `aria-label` attribut wird am Link Attribut gesetzt (diese Variante überschreibt den Inhalt des Links, dadurch ist nach meinem Verständnis das Bild kein funktionales Bild mehr)
- ein `title` attribut wird am Link gesetzt (siehe [Technique H33: Supplementing link text with the title attribute](https://www.w3.org/WAI/WCAG21/Techniques/html/H33.html), hierbei sind aber die bekannten Probleme mit dem `title` Attribut zu beachten)

Die Frage ist nun: Sind alle aufgezählten Varianten ausreichend?

**Comment by luis-pato** [comment]
Writing in german excludes a lot of people...  😉 

I think if we are placing the image inside a link, we should ask ourselves if the img really needs to be in the accessibility tree.
If the user will just interact with the link element, and if the link already has some kind of "image description" (either via title, aria-label, ..., like described above) then we could probably just add a `aria-hidden` to the image.

**Comment by benjaminkott** [comment]
> Ich möchte die Diskussion mal auf eine allgemeinere Ebene heben, weil mir scheint, dass du grundsätzlich die Unterscheidung "functional image" und "image" in Frage stellst?
> 
> Ich zitiere aus der WCAG (normativer Text des Erfolgskriteriums):
> 
> > All non-text content that is presented to the user has a text alternative that serves the equivalent purpose, except for the situations listed below.
> > **Controls, Input**
> > If non-text content is a control or accepts user input, then it has a name that describes its purpose. (Refer to Success Criterion 4.1.2) for additional requirements for controls and content that accepts user input.)
> > [...]

Hallo @sweckenmann,

ich glaube da wurde ich falsch verstanden. Ich möchte natürlich nicht die Unterscheidung "functional image" und "image" in frage stellen. Ich finde die WCAG dort sehr aussagekräftig und nachvollziehbar.

Allerdings stelle ich die Bewertung der Bilder in dem Beschrieben Kontext oben als "functional image" und nicht als "image" in frage. Wenn ich hier auf den decision tree (https://www.w3.org/WAI/tutorials/images/decision-tree/) zurück greife. Erfüllen die Bilder in dem Beschrieben Kontext was unter "**Does the image contribute meaning to the current page or context?**" fällt. Somit muss der alt-text das Bild beschreiben, was aus meiner Betrachtung das korrekte vorgehen hier ist.

Beziehend auf die Definitionen von:
- https://www.w3.org/WAI/tutorials/images/complex/
- https://www.w3.org/WAI/tutorials/images/groups/

Es geht also darum das durch die Bewertung als "functional image" der Inhalt des alternativ texts verändert werden soll.

Ich teile die Einschätzung von @mtelgkamp das hier der Link korrekt ausgezeichnet werden sollte.

**Comment by MarcHaunschild** [comment]
Die WCAG ist klar: jeder nicht-Text-Inhalt benötigt eine textliche Alternative. Dabei wird keine bestimmte Technik gefordert.
Also jede Technik, bei der eine Text-Alternative bereit gestellt wird, erfüllt das SC.
Verlinkte Grafiken sind interaktive Elemente und müssen **zusätzlich** den Zweck (also bei Links das Ziel) nennen.
Wer mich kennt, weiß, dass ich immer gegen `aria-label` und andere exklusive Techniken argumentiere. Einerseits wegen der ersten ARIA-Regel (Benutze - aus Gründen - kein ARIA, wenn es sich vermeiden lässt).
Was an ARIA am schlimmsten ist aus meiner Perspektive: Per ARIA (z.B. `aria-label`) übermittelte Informationen sind exklusiv, denn sie können ausschließlich mit Hilfsmitteln wie einem Screenreader erreicht werden. Selbst das hier (zu recht) verpönte `title`-Attribut hat eine breitere Unterstützung!
Man kann argumentieren, alle ohne Screenreader können das Bild ja sehen. Aber das ist falsch, denn das Bild kann aufgrund eines technischen Fehlers nicht verfügbar sein, dann gibt der Browser an Stelle des Bildes den Wert des `alt`-Attributes aus, was schon wesentlich besser ist, aber immer noch Menschen ausschließt. Denn wer mal Zeugen befragt hat - und ich rede von ehrlichen Leuten, die nicht absichtlich lügen - weiß dass 10 Leute mindestens drölf Varianten eines Tatherganges schildern. Es ist also für viele Menschen wichtig, ausdrücklich gesagt zu bekommen, was auf dem Bild jetzt die im Kontext nötige Information ist.
Um auf die Frage der Bewertung zurückzukommen: wie gesagt ist lediglich eine Text-Alternative gefordert. Ob die nur Blinde erreichen können, spielt dabei keine Rolle. Hier ist die WCAG (mal wieder) getragen von Annahmen (Hier: jeder der das Bild nicht sieht, hat einen Screenreader und kann den auch bedienen).

**Comment by Bunnyfield** [comment]
`Nein, die Regel ist eher: ist ein Bild verlinkt, wird es dadurch zu einem "functional image".`

Ich würde da gern ein "auch" einfügen, weil es je nach Anwendungsfall für die Besucher ausreicht, die Lightbox eben nicht zu öffnen, sondern nur durch die "normal großen" Bilder zu blättern. Das wäre für Anwender von Screenreadern identisch. Letztere würden durch die Beschränkung auf "functional link" dazu gezwungen, die Lightbox zu öffnen, um an weiterführende Informationen zu gelangen was ganz sicher nicht im Sinne der BITV ist.

**Comment by Bunnyfield** [comment]
> Letztere würden durch die Beschränkung auf "functional link" dazu gezwungen, die Lightbox zu öffnen, um an weiterführende Informationen zu gelangen was ganz sicher nicht im Sinne der BITV ist.

Meine Schlussfolgerung daraus ist, dass der Ansatz mit einem Prefix in einer der Varianten für alternative Texte die breiteste Abdeckung der Anwendungsfälle hätte.

Damit bleibt der alternative Text z. B. im CMS für Bilder und/oder Bildreferenzen identisch, wird aber im Fall einer Verwendung in einer Lightbox durch entsprechende Hinweise ergänzt:

`Öffnet eine vergrößerte versehene Version von: Hier kommt mein Bildtext hin.`
oder
`Öffnet eine vergrößerte und mit mehr Informationen versehene Version von: Hier kommt mein Bildtext hin.`

Wenn man beim Prefix hinsichtlich der Informationen unterscheidet, wissen die Anwender von Screenreadern, ob sich der Klick überhaupt lohnt oder eher nicht.

**Comment by MarcHaunschild** [comment]
> Ggf. kann man das auch als Suffix formulieren, dann wird das für die Anwender von Screenreadern nicht so nervig, dass jedes Bild mit "Öffnet eine Vergrößerung ..." anfängt. ;-)

Wie man es macht, ist es falsch: brechen SR-Nutzerinnen die Ausgabe ab, weil sie ihnen zu lang ist, erfahren sie nichts über die Funktion, steht sie am Anfang, ist der Nerv-Faktor hoch. ;-)

So oder so wäre der Prüfschritt erfüllt.

**Comment by benjaminkott** [comment]
@MarcHaunschild, vielen dank erneut für die Ausfühliche erklärung.

Ich versuche das einmal zusammen zu fassen und mit Code Beispielen zu belegen.
Die CSS Klasse `.screenreader` soll hier als Beispiel für eine Anweisung dienen
welche den Inhalt für Screenreader accessible macht und für andere Nutzer verbirgt.
Das Bild-Element wird jeweils mit verschiedenen zielen verlinked. Ich hoffe es wird
dadurch etwas greifbarer. Die Beispiele sind aus Sicht eines CMS Providers erstellt 
worden. Somit haben wir nur wenig einfluss auf JavaScript haben uns müssen uns so
auf Server-Side Generated Markup konzentrieren.

Folgende dinge werden in betracht gezogen:

1. Vermeidung von `aria-label` wenn möglich
1. Unzureichender Browser support für `title` nur als fallback
1. Aktion mit bei Verlinkten Bildern irgendwo im link stehen 

Voraussetzungen:

1. JavaScript ist Userland
1. Minimum CSS kann ausgeliefert werden
1. Markup wird Server-Side gerendert
1. JavaScript als enhancement, links funktionieren auch ohne
1. Image alt wird nicht verändert
1. Interaktionsbeschreibungen werden vom CMS generiert

## Minimal CSS

```css
*:focus {
  outline-offset: 1px;
  outline: 2px solid;
}
.image {
  position: relative;
}
.lightbox {
  cursor: zoom-in;
}
.screenreader {
  position: absolute;
  width: 1px;
  height: 1px;
  padding: 0;
  margin: -1px;
  overflow: hidden;
  clip: rect(0,0,0,0);
  white-space: nowrap;
  border: 0;
}
.screenreader-overlay {
    position: absolute;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    outline: 0;
    overflow: hidden;
    text-indent: -9999px;
    &:focus {
        outline-offset: 1px;
        outline: 2px solid;
    }
}
```

## Verlinkungen auf Aktionen (Lightbox)

```html
<figure class="image">
    <a href="large-elephant.jpg" class="lightbox" role="button" data-action="lightbox" title="Navigate to: Elephant">
        <span class="screenreader">Show larger version for: Elephant</span>
        <picture>
            <img loading="lazy"
                title="Elephant by Pablo Picasso"
                alt="Elephant at sunset"
                src="elephant.jpg"
                >
        </picture>
    </a>
    <figcaption class="caption">An elephant at sunset</figcaption>
</figure>
```

## Verlinkungen auf Bilder

```html
<figure class="image">
    <a href="large-elephant.jpg" title="Show larger version for: Elephant">
        <span class="screenreader">Show larger version for: Elephant</span>
        <picture>
            <img loading="lazy"
                title="Elephant by Pablo Picasso"
                alt="Elephant at sunset"
                src="elephant.jpg"
                >
        </picture>
    </a>
    <figcaption class="caption">An elephant at sunset</figcaption>
</figure>
```

## Verlinkungen auf Content

```html
<figure class="image">
    <a href="/elephant" title="Navigate to: Elephant">
        <span class="screenreader">Navigate to: Elephant</span>
        <picture>
            <img loading="lazy"
                title="Elephant by Pablo Picasso"
                alt="Elephant at sunset"
                src="elephant.jpg"
                >
        </picture>
    </a>
    <figcaption class="caption">An elephant at sunset</figcaption>
</figure>
```

## Alernative

```html
<figure class="image">
    <picture>
        <img loading="lazy"
            title="Elephant by Pablo Picasso"
            alt="Elephant at sunset"
            src="elephant.jpg"
            >
    </picture>
    <figcaption class="caption">An elephant at sunset</figcaption>
    <a href="/elephant" class="screenreader-overlay" title="Show larger version for: Elephant">
        Show larger version for: Elephant
    </a>
</figure>
```

CodePen: https://codepen.io/benjaminkott/pen/LYXNGPM

Wenn ich es immer noch nicht gerafft habe, bitte korrigiert mich.

**Comment by MarcHaunschild** [comment]
> @MarcHaunschild, vielen dank erneut für die Ausfühliche erklärung.
> 
> Ich versuche das einmal zusammen zu fassen und mit Code Beispielen zu belegen. 
> 
> Folgende dinge werden in betracht gezogen:

Da reden wir zum Teil bereits von best practices, nicht von Voraussetzungen für ein pass. 

> Voraussetzungen:

Also bisher waren meine Anmerkungen bewusst allgemein. Wie hier schon gesagt wurde, geht es hier im Repo um die Diskussion der Prüfschritte. Das ist schon eine ganz konkrete Einzelfall-Umsetzung und eigentlich eine Beratung.

Ich versuche es mal ganz kurz:
 
> ## Warum keine Texte im Alt-Bereich des Bildes
> Es ist aus CMS sicht schwierig diese Entscheidung und Notwendigkeit für den Nutzer zu treffen. Es kommt immer auf den fall an wo das Bild verwendet wird und wie. Da wir im TYPO3 Kontext mit Datei Referenzen arbeiten könnte das vom Nutzer an der Stelle der Verwendung sicherlich hinzugefügt werden.

Ja, es gibt keine "passt-immer"-Lösungen. In der Regel sind es "kommt-drauf-an "-Lösungen und können nur für einen bestimmten Fall empfohlen werden.

Eine Lösung die immer passt, gibt es praktisch nie. So sollte `figure` nur verwendet werden, wenn das semantisch passt. Bist du sicher, dass das immer der Fall ist?

> ## Verlinkungen auf Aktionen (Lightbox)

Da sind viel zu viel Texte drin, wie gesagt Redundanzen und Wiederholungen vermeiden. Und wolltest du nicht auf `title` verzichten?

Hier mein Vorschlag (falls `figure`korrekt ist):

> ```
> <figure class="image">
>     <a href="large-elephant.jpg" class="lightbox" role="button" data-action="lightbox">
>         <span class="screenreader">Show larger version for: </span>
>         <picture>
>             <img loading="lazy"
>                 alt="Elephant at sunset by Pablo Picasso"
>                 src="elephant.jpg"
>                 >
>         </picture>
>     </a>
>     <figcaption class="caption" aria-hidden="true">An elephant at sunset</figcaption>
> </figure>
> ```
> 
> ## Verlinkungen auf Bilder

wie oben
 
> ## Verlinkungen auf Content
> ```
> <figure class="image">
>     <a href="/elephant">
>         <span class="screenreader">Navigate to: </span>
>         <picture>
>             <img loading="lazy"
>                 alt="Elephant at sunset by Pablo Picasso"
>                 src="elephant.jpg"
>                 >
>         </picture>
>     </a>
>     <figcaption class="caption" aria-hidden="true">An elephant at sunset</figcaption>
> </figure>
> ```
> 
> ## Alernative
> ```
> <figure class="image">
>     <picture>
>         <img loading="lazy"
>             alt="Elephant at sunset by Pablo Picasso"
>             src="elephant.jpg"
>             >
>     </picture>
>     <figcaption class="caption" aria-hidden="true">An elephant at sunset</figcaption>
>     <a href="/elephant" class="screenreader-overlay">
>         Show larger version for: Elephant
>     </a>
> </figure>
> ```

Das `aria-hidden` im `caption` nur, wenn die `caption` keine neuen Informationen enthält. Meine Empfehlung wäre aber `alt`-Attribut und figcaption sinnvoll unterschiedlich zu befüllen. Das fällt aber in den Bereich einer Redakteurs-Schulung.

Wir kommen hier jetzt zu weit ab, es ist ja kein a11y-Forum. Die gibt es ja auch.

Zusammenfassend: Es ist wirklich so einfach:

1. Sag was auf dem Bild ist
2. Sag, was der Link/ der Button tut
3. Vermeide Wiederholungen

Wie der Code dann genau aussieht, ist wirklich euch überlassen. Aber denke bitte dran: die eine Lösung, die für alles passt, gibt es eigentlich nicht. Wenn das Bild eine `figure` im Sinne des HTML-Elementes `figure` ist, passt der Code, sonst hast du implizit falsche Rollen verwendet ([9.4.1.2 Name, Rolle, Wert verfügbar](https://ergebnis.bitvtest.de/pruefschritt/bitv-20-web/9-4-1-2-name-rolle-wert-verfuegbar)) - das wird wohl eher selten ein fail sein, aber auch hier wieder: kommt auf die konkrete Seite/ Umsetzung an...

`figure` muss weder für jedes Bild verwendet werden, noch ist `figure` ausschließlich für Bilder gedacht, es können sich dort auch Tabellen, Code oder andere Dinge drin finden.
https://html.spec.whatwg.org/multipage/grouping-content.html#the-figure-element
Know your standards...

;-)

**Comment by MarcHaunschild** [comment]
@benjaminkott ich wollte jetzt auch nicht, dass du dich entschuldigst.
😲
Wenn man nicht mehr mag, antwortet man halt nicht mehr.

Aber wenn es jetzt gelöst ist, ist das schön und manchmal muss man auch einfach irgendwo mal jemanden fragen können.

Die Formulierungen in der WCAG sind auch ziemlich eigen. Auch native speaker müssen sich erst ins wording rein finden...

**Comment by MarcHaunschild** [comment]
Noch ein Hinweis: wenn das Bild nicht nur hier im Beispiel "elephant.jpg" oder sogar "elephant-by-picasso.jpg" heißt, ist das der erste Schritt einer progressive enhancement Strategie. (Kale ist wieder nicht technisch, sondern redaktionell, aber Barrierefreiheit geht halt nur im Zusammenspiel).
Selbst wenn aller sonstiger Kontext fehlt, was zu einem fail führen würde, bekämen screenreader-Nutzerinnen schon mal eine Vorstellung vom Inhalt des Bildes.
Der Wert des Alt-Attributes überschreibt das dann mit etwas besserem, die figcaption ergänzt es weiter und am Ende sollte im Screenreader und bei sehenden etwas ankommen, was hintereinander weg gelesen sinnvoll ist (auch in der Reihenfolge) und möglichst keine Wiederholungen enthält.

**Comment by johannesFischer84** [comment]
Ich habe nicht bei allen Beiträgen jedes Wort gelesen. Mir scheint das Thema auch geklärt zu sein. Nur ganz allgemein möchte ich aber noch zu einer Sache etwas anmerken:
> Es ist leider sehr schwierig zu diesem exakten Thema valide Informationen zu finden.
Alles was an Ressourcen im A11Y Bereich dazu aufgetrieben werden konnte ignoriert die Funktionsbeschreibung.

Aus meiner Sicht gibt es ein paar Informationen dazu, wie man grafische Bedienelemente (hier "functional images" genannt), informationsvermittelnde Grafiken und dekorative Grafiken auseinanderhalten kann und was jeweils getan werden muss:

Zum einen gibt es das [Understanding-Dokument von WCAG 1.1.1](https://www.w3.org/WAI/WCAG21/Understanding/non-text-content.html). Im Bereich "Techniques" sind mit "Situation" A, B, usw. die verschiedenen Möglichkeiten aufgegliedert. Die Functional Images würden Situation C entsprechen ("If non-text content is a control or accepts user input"). Dahinter sind Techniken aufgeführt, wie man beispielhaft so etwas umsetzen sollte. Ich persönlich würde dies für die Informationen empfehlen.

Im BIK BITV-Test ist das WCAG-Kriterium 1.1.1 schon in mehrere Prüfschritte aufgeteilt. Die Functional Images werden im [Prüfschritt 1.1.1a](https://ergebnis.bitvtest.de/pruefschritt/bitv-20-web/9-1-1-1a-alternativtexte-fuer-bedienelemente) abgeprüft. Richtig ist allerdings, dass dort im Wesentlichen keine Code-Beispiele sind. Man kann diese ggf. aus der Textbeschreibung herauslesen.

Zur Vollständigkeit: In den [Handreichungen der Überwachungsstelle Bund](https://handreichungen.bfit-bund.de/) gibt es einen Leitfaden "Nachschlagewerk zur Erstellung barrierefreier User Interface Elemente". Darin gibt es Abschnitte zu Grafiken und auch zu Bedienelementen. Für Functional Images allein gebe ich aber zu, dass man es da als Laie schwer hat, sich die entsprechenden Stellen für ein grafisches Bedienelement herauszusuchen.

Ich würde daher wie gesagt die WCAG-Quellen am ehesten empfehlen.

**Comment by benjaminkott** [comment]
@johannesFischer84 auch dir Vielen Dank für die Informationen. 

Ohne dafür studiert zu haben, ist das beste was man 
Die WAI ist relativ eindeutig was die Handhabung von `Functional Images` angeht und damit auch den zu implementierenden Code. Da ist auch nicht viel Spielraum für Interpretation. https://www.w3.org/WAI/tutorials/images/functional/

> For instance, as shown in examples below, the text alternative should be “print this page” rather than “(image of a) printer”, “search” rather than “magnifying lens” or “Example.com homepage” rather than “Example.com logo”.

Das gleiche gilt auch für Prüfschritt 1.1.1a 
https://ergebnis.bitvtest.de/pruefschritt/bitv-20-web/9-1-1-1a-alternativtexte-fuer-bedienelemente

> Grafische Bedienelemente (alle verlinkten / interaktiven Grafiken und Bilder) müssen mit Alternativtexten versehen werden (nicht verlinkte bzw. nicht interaktive Grafiken und Bilder werden in Prüfschritt 9.1.1.1b "Alternativtexte für Grafiken und Objekte" geprüft).

Die Frage ist also was mit Alternativtexten für interaktiven Grafiken und Bilder gemeint ist.
So wie es mir erklärt worden ist, und wie ich es aus den Texten verstehe wird hier vom `alt-attribute` des Bildes geredet.
Das ist allerdings eine rein **Technische Betrachtungsweise**.

Wenn es "nur" darum geht das der Screenreader-Nutzer den Kontext versteht. Ist es nicht notwendig die Funktion im `alt-attribute` unterzubringen. Wenn der Prüfschritt aber genau darauf zielt, muss es da drin stehen.

Durch die Diskussion ist nun klar geworden das es hier um das **Ergebnis/Erlebnis** für den Screenreader-Nutzer geht und nicht um die Technische Implementierung. An der Stelle erneut vielen dank an alle beteiligten.

**Comment by benjaminkott** [comment]
Wenn keiner etwas dagegen hat, würde ich dieses Issue gerne schließen und es damit als erledigt abhaken. <3

**Comment by johannesFischer84** [comment]
> Die Frage ist also was mit Alternativtexten für interaktiven Grafiken und Bilder gemeint ist.

"Interaktiv" bzw. "Interaktion" in diesem Zusammenhang bedeutet, dass Nutzende durch eine Eingabeoperation (z. B. click-Ereignis, keyup-Ereignis bzw. Mausklick, Drücken der Eingabetaste) eine Aktion auslösen können. Das alt-Attribut ist tatsächlich eine stark vereinfachte Sichtweise darauf, wie für Screenreader oder andere assistive Technologien ein Alternativtext verfügbar gemacht wird.

> Wenn keiner etwas dagegen hat, würde ich dieses Issue gerne schließen und es damit als erledigt abhaken. <3

Ich habe nichts dagegen.
