### ISSUE TITLE
1.4.3 Kontraste von Texten ausreichend: nicht-aktiver Tab

### ISSUE THREAD

**Issue by sprungmarker** [BIK-BITV/BIK-Web-Test#364]
eine Frage, die immer wieder aufkommt, was fällt alles unter "nicht-aktiv". Fallen bei einer Reihe von Tabs die gerade "nicht-aktiven" Tabs unter "nicht-aktiv".

Meiner Meinung nach handelt es sich hierbei um einen Navigationsmechanismus und insofern müssen auch nicht-aktive Inhalte hinreichend Kontrast haben.

Wie seht ihr das?

**Comment by marcus-herrmann** [comment]
Sehe es genauso mit dem Navigationsmechanismus. Das "andere nicht-aktiv" ist für mich meist gleichbedeutend mit der Existenz des `disabled`-Attributs und einer Nicht-Interaktivität von etwas.

**Comment by sprungmarker** [comment]
Ja - danke. Dachte auch, dass es sich auf nicht-aktive bzw. deaktivierte Bedienelemente bezieht. :)
