### ISSUE TITLE
HTML code element: CSS Änderung 

### ISSUE THREAD

**Issue by sprungmarker** [BIK-BITV/BIK-Web-Test#365]
Könntet ihr bitte eine CSS Änderung vornehmen und etwa das padding in CSS für das Code-Element rausnehmen.
Derzeit springt jedes code-Element aus dem Lesefluss raus.
Das ist etwas anstrengend. :)

![2023-08-08 18_19_42-Prüfschritt 9 1 3 1h Beschriftung von Formularelementen programmatisch ermittelb](https://github.com/BIK-BITV/BIK-Web-Test/assets/656578/f0acaf49-4e7f-4270-bc70-ff0480d3a8a1)

**Comment by sweckenmann** [comment]
Wurde gefixed.
