### ISSUE TITLE
Akkordeon-Funktion in den Prüfschritten seit 09-20-2023 dysfunktional

### ISSUE THREAD

**Issue by thoreine** [BIK-BITV/BIK-Web-Test#374]
Hallo zusammen,
da ich grade eine Website teste und dazu immer noch hier und da in die Prüfschritte spicken muss, ist mir ein Problem aufgefallen, das gestern noch nicht existierte: Die Inhalte der Akkordeons lassen sich nicht mehr aufklappen. Teils klappte dies eben auf einigen Seiten noch über die "Alles aufklappen"-Funktion, auf den meisten Seiten klappt aber auch die nun nicht mehr.

**Comment by sweckenmann** [comment]
@thoreine Können Sie mir einen beispielhafte Seite nennen, wo es nicht funktioniert?

**Comment by Andreas-Englisch** [comment]
Vor ca. einer Stunde ging es auf den meisten Seiten nicht, z.B. https://ergebnis.bitvtest.de/pruefschritt/bitv-20-web/bitv-20-web-9-3-1-1-hauptsprache-angegeben, aber inzwischen scheint es wieder zu gehen

**Comment by thoreine** [comment]
@sweckenmann - Gestern Abend funktionierte alles noch wie gewohnt. Als ich heute morgen gegen 10h erstmals reingeschaut habe, funktionierte es wie oben geschildert auf alles Seiten nicht mehr bzw. nur noch sehr eingeschränkt.

Kann @Andreas-Englisch Aussage bestätigen, seit einigen Minuten scheint alles wieder wie gewohnt zu funktionieren.
Beide Phänomene konnten über verschiedene Personen mit unterschiedlichen Browsern bestätigt werden.

**Comment by sweckenmann** [comment]
@thoreine vielen Danke. Ich werde das im Auge behalten und an unsere Entwickler weitergeben.

**Comment by sweckenmann** [comment]
Da es wieder funktioniert, schließe ich das issue (sonst gerne wieder öffnen).
