### ISSUE TITLE
Prüfschritt 9.3.1.2 Absatz über "Auszeichnung ohne praktischen Nutzen"

### ISSUE THREAD

**Issue by MarcHaunschild** [BIK-BITV/BIK-Web-Test#376]
In der Prüfschrittbeschreibung steht folgender Absatz, den ich empfehle zu streichen:

> Keinen praktischen Nutzen hat die Auszeichnung von Wörtern, die ohne Auszeichnung üblicherweise nicht anders ausgesprochen werden. **Sie müssen nicht ausgezeichnet werden**. Beispiele für solche Wörter: Web, Link, Top, Enter, Helpdesk.

## Begründung

Dieser Satz kann zu Verwirrung führen. In einem aktuellen Fall hat sich eine Diskussion ergeben, weil einige wenige türkische Wörter so klingen, wie man es als deutscher erwarten würde. Eine Abwertung/ Auszeichnung erschien daher nicht nötig. Diese Meinung kann ich nicht teilen, weil

1. Das [entsprechende WCAG-Kriterium](https://www.w3.org/WAI/WCAG21/Understanding/language-of-parts.html) sieht solch eine Ausnahme nicht vor. [Anderssprachige Wörter müssen programmatisch ermittelbar ausgezeichnet werden heißt es da.](https://www.w3.org/TR/WCAG21/#language-of-parts) Eine generelle Pingeligkeitsverhinderungsklausel, bei einzelnen, vergessenen Begriffen haben wir eh schon in der Bewertung (ein paar vergessene Fremdwörter sollen zu keiner Abwertung führen).
2. Es geht nicht nur um Aussprache im entsprechenden WCAG-Kriterium. Während der normative Text keine Ausnahmen zulässt, steht in den Erläuterungen, dass sowohl Screenreader, als auch grafische Browser auf die korrekte Auszeichnung angewiesen sind, um beispielsweise Silben korrekt zu trennen, ltr- und rtl-Texte korrekt darzustellen usw
3. "Ohne praktischen Nutzen" kann aufs Glatteis führen. Wenn man sich fremdsprachige Software von einer Text-to-Speech-Software ausgeben lässt, mag das so klingen, wie man es als deutscher erwartet. Es gibt aber solche Wörter, die einem Fremden korrekt klingen würden, aber durch eine andere Aussprache ihren Sinn ändern. Beispiel aus dem deutschen: weg vs Weg (solch eine Unterscheidung allein durch die Länge eines Vokals kennen z.B. Russen nicht, die zum Beispiel auch mit beach vs bitch oder sheet vs shit Probleme haben).
Umgekehrt gibt es im Russischen Unterschiede, die uns nicht auffallen würden wie: harte Konsonanten vs weiche oder bedeutungstragende Betonungen wie писать vs писать, beides identisch geschrieben, einmal auf dem и betont ([pinkeln](https://www.deepl.com/translator#de/ru/pinkeln)), einmal auf dem а ([schreiben](https://www.deepl.com/translator#de/ru/schreiben)).
Das heißt als Ausländer kann man oft meinen, das klingt ja genau so als ob ich es selber vorlesen würde, aber die Bedeutung kann eine ganz andere sein. Selbst in vertrauten Sprachen. Hier noch ein schönes Beispiel: https://www.instagram.com/reel/Cw7u35FNg2K/?igshid=MzRlODBiNWFlZA%3D%3D
Es gibt Sprachen, die überwiegend so ähnlich klingen, wie wir deutschen lesen würden (spanisch) und andere, in denen das überhaupt nicht der Fall ist (französisch).

Was ich damit sagen möchte: wir können in der Regel den praktischen Nutzen nicht bewerten. Daher erscheint mir dieser Absatz nicht hilfreich, sondern viel mehr irreführend und ich plädiere dafür, ihn zu entfernen.

**Comment by johannesFischer84** [comment]
Wenn es darum geht, Prüfschritte an die WCAG anzugleichen, bin ich immer dafür. Bezüglich des Themas zu wie im Deutschen klingende Worte habe ich im Understanding-Dokument von 3.1.2 Folgendes entdeckt:

> Frequently, when the human language of text appears to be changing for a single word, that word has become part of the language of the surrounding text. Because this is so common in some languages, single words should be considered part of the language of the surrounding text unless it is clear that a change in language was intended. If there is doubt whether a change in language is intended, consider whether the word would be pronounced the same (except for accent or intonation) in the language of the immediately surrounding text.

Die WCAG sagen also, einzelne fremdsprachige Worte in einem Fließtext sind normalerweise Teil der Sprache geworden, außer es ist ein absichtlicher Sprachwechsel erkennbar. Bei Zweifeln wird tatsächlich die Aussprache herangezogen.

Vielleicht könnte man den Absatz in der Prüfschrittanleitung in ähnlicher Weise formulieren. Denn es könnte ja folgender Satz auftauchen: "Wenn Sie Enter drücken und nicht weiterkommen, wenden Sie sich bitte an unseren Helpdesk." Entsprechend der Beschreibung aus dem Understanding-Dokument würde ich hier nur einzelne Worte sehen und würde keinen absichtlichen Wechsel auf Englisch erkennen. Bestenfalls könnte ich bei Helpdesk noch etwas Zweifel haben, weil ich "Hotline" oder "Support" als gebräuchlichere Worte im Deutschen empfinde. Dann wäre entweder gar keine Sprachauszeichnung nötig oder die Aussprache könnte entscheiden.

**Comment by detlevhfischer** [comment]
@MarcHaunschild Ich habe den Text entwas angepasst: #413 

Können wir das Issue schließen?

**Comment by MarcHaunschild** [comment]
Ja
