### ISSUE TITLE
9.1.3.2 Sinnvolle Reihenfolge - Videoplayer nicht erreichbar mit Pfeiltasten oder nur teilweise

### ISSUE THREAD

**Issue by sprungmarker** [BIK-BITV/BIK-Web-Test#378]
Ein Videoplayer ist nicht oder nur teilweise mit Pfeiltasten erreichbar (z.B. Start, Fortschrittsnavigation).

Sinnvolle Reihenfolge erfordert doch nicht, dass alle Inhalte / komplexe Widgets vollständig mit Pfeiltasten erreich- und bedienbar sein müssen - also vollständig ohne TAB.

Im entsprechenden Erfolgskriterium der WCAG findet sich auch in den Techniken kein Hinweis auf eine Nutzung der Pfeiltasten.

Weil die Frage jetzt mir öfter gestellt wird ... :)

**Comment by johannesFischer84** [comment]
Die Pfeiltasten werden aus meiner Sicht in der Prüfschrittanleitung nur erwähnt, weil man sie benötigt, um eine Webseite lesen zu können. Es geht in WCAG 1.3.2 nicht darum, ob und mit welchen Tasten die Inhalte per Tastatur erreichbar sind. Stattdessen ist nur die Reihenfolge entscheidend, in welcher die Inhalte vorgelesen werden.

Die Erreichbarkeit interaktiver Bedienelemente mit der Tastatur ist Sache von WCAG 2.1.1. Dort sind theoretisch alle Bedienmöglichkeiten der Tastatur erlaubt.

**Comment by sprungmarker** [comment]
> Die Pfeiltasten werden aus meiner Sicht in der Prüfschrittanleitung nur erwähnt, weil man sie benötigt, um eine Webseite lesen zu können. Es geht in WCAG 1.3.2 nicht darum, ob und mit welchen Tasten die Inhalte per Tastatur erreichbar sind. Stattdessen ist nur die Reihenfolge entscheidend, in welcher die Inhalte vorgelesen werden.
> 
> Die Erreichbarkeit interaktiver Bedienelemente mit der Tastatur ist Sache von WCAG 2.1.1. Dort sind theoretisch alle Bedienmöglichkeiten der Tastatur erlaubt.

Danke. Das habe ich auch so gesehen. :)

**Comment by detlevhfischer** [comment]
@sprungmarker  Können wir das Issue schließen?

**Comment by sprungmarker** [comment]
@detlevhfischer ja klar
