### ISSUE TITLE
Bookmarklet für das Prüfen von 2.5.8 Target Size (Zielgröße Minimum)

### ISSUE THREAD

**Issue by sweckenmann** [BIK-BITV/BIK-Web-Test#388]
Wir sind auf der Suche nach einem Bookmarklet, das die Prüfung der neuen WCAG 2.2-Anforderung "Target Size" zumindest unterstützen kann. Derzeit im Sinn:

1. Chrome-Erweiterung: https://chrome.google.com/webstore/detail/accessibility-tools-targe/kofnlhenkilpdacklecdifdfigomanje
2. Steve Faulkner's Target Size Checker: https://html5accessibility.com/stuff/2023/08/28/quick-and-very-dirty-target-size-checker/

Im Moment ist der Target Size Checker in der Prüfanleitung (siehe https://github.com/BIK-BITV/BIK-Web-Test/pull/381), aber ich überlege, es durch die Chrome-Erweiterung zu ersetzen.

Falls es Meinungen oder weitere Ideen gibt, gerne!

**Comment by stefanFarnetani** [comment]
Hallo @sweckenmann ich persönlich mag das bookmarklet mehr. In der Sache erfüllen beide ihren Zweck.
Die Extension bietet ja mehrere Funktionen. Das wäre interessant, wenn dadurch andere bookmarklets wegfallen würden. Die Extension bietet auch text-spacing. Auf den ersten Blick scheint das auch gut zu funktionieren.

**Comment by detlevhfischer** [comment]
@sweckenmann @stefanFarnetani Beide Tools sind jetzt in der Prüfung genannt. Ich schließe das Issue.
