### ISSUE TITLE
9.3.1.2 Anderssprachige Wörter und Abschnitte - Umgang mit Title-Attributen

### ISSUE THREAD

**Issue by CarstenKaul** [BIK-BITV/BIK-Web-Test#39]
Gibt es für einen solchen Fall schon Angaben wo das einzuordnen und wie das zu bewerten ist? 

Hier meine Fehlerbeschreibung eines Beispiels. Wie geht ihr damit um?

Fehlerbeschreibung:
Das leere Anchor-Element XY (umschliesst eine CSS-Hintergrundgrafik) und enthält im title-Attribut den Text "Opens external link in new window", welcher nicht der Hauptsprache der Webseite entspricht. Dieser Inhalt wird somit von Screenreadern mit falscher Intonation vorgelesen. Für Nutzer, die auf eine Sprachausgabe angewiesen sind, ist der gesprochene Text so unverständlich. 

Empfehlung des Prüfers: Bitte übersetzen Sie Texte,welche nicht mit dem lang-Attribut ausgezeichnet werden können in die Hauptsprache der Webseite oder verwenden Sie andere Techniken über die Sie anderssprachige Texte korrekt mit Lang-Attributen auszeichnen zu können.

**Comment by johannesFischer84** [comment]
Sofern möglich, habe ich so etwas nie im WCAG-Kriterium 3.1.2 bewertet, sondern nur in 1.1.1 / 2.4.4 / 2.4.6 (je nachdem, was zutrifft). Ich hab dann geschrieben, dass ein englischsprachiger Text auf einer deutschsprachigen Seite nicht aussagekräftig ist. Das `lang`-Attribut habe ich dann gar nicht angemerkt, denn ich will ja gar nicht, dass der Text auf Englisch formuliert wird.

**Comment by sweckenmann** [comment]
@CarstenKaul Ich denke, das issue ist geklärt, würde es dann schließen, sonst mach es gerne wieder auf.
