### ISSUE TITLE
Prüfschritt 9.1.4.5 Verzicht auf Schriftgrafiken

### ISSUE THREAD

**Issue by anatom5** [BIK-BITV/BIK-Web-Test#393]
**Mich irritiert der Satz "Der Prüfschritt ist anwendbar, wenn das Webangebot Schriftgrafiken enthält" in der Prüfschrittbeschreibung.** Das heißt ja, wenn im Prüfschritt 9.1.4.5 Verzicht auf Schriftgrafiken keine Schriftgrafiken verwendet werden, ist er nicht anwendbar. Oder bin ich urlaubsreif? Der Prüfschritt müsste doch immer anwendbar sein, oder?

### Vorschlag 1
"Der Prüfschrift ist immer anwendbar"

### Vorschlag 2
"Der Prüfschrift ist anwendbar, wenn das Webangebot Bilder und Grafiken enthält"

**Comment by anatom5** [comment]
Danke. Dann muss wohl der Prüfschritt umbenannt werden in _9.1.4.5 Schriftgrafiken_. Mit der Bezeichnung _9.1.4.5 Verzicht auf Schriftgrafiken_ macht das nämlich keinen Sinn. Das wäre mein dritter Vorschlage gewesen, den ich dann aber wieder gelöscht hatte ...

**Comment by johannesFischer84** [comment]
Es kommt darauf an, ob man den Prüfschritt aus Sicht der EN 301 549 oder aus Sicht der WCAG sieht. Bezüglich EN stimme ich Andreas (@Andreas-Englisch) zu. Wenn man nur die WCAG heranzieht, lautet deren Anwendbarkeitsregel: "If the technologies being used can achieve the visual presentation". Das liefe aus meiner Sicht quasi auf immer anwendbar heraus, weil Webseiten immer grafische Darstellung und auch Text-Darstellung ermöglichen.
Da gesetzlich die EN 301 549 wohl relevanter ist, kann man die Anwendbarkeitsregel meiner Meinung nach so lassen, wie sie ist. Bezüglich der Benennung des Prüfschritts ist mir beides Recht, die bisherige Benennung und die von Jörg Morsbach (@anatom5) vorgeschlagene.

**Comment by detlevhfischer** [comment]
Der Prüfschritt wird in 9.1.4.5 Schriftgrafiken umbenannt.
