### ISSUE TITLE
2.5.8: Anpassungen im Bereich "2. Prüfung"

### ISSUE THREAD

**Issue by johannesFischer84** [BIK-BITV/BIK-Web-Test#400]
An der neuen Prüfschrittanleitung sind mir ein paar Kleinigkeiten aufgefallen, die man im Bereich "2. Prüfung" evtl. anpassen könnte:

# Panel Berechnet und Layout

> Im Panel "Berechnet" des Inspektors werden ebenfalls die Werte für Höhe und Breite des ...

Noch empfehlenswerter finde ich das Panel "Layout", wo im Bereich "Box-Modell" die Klickfläche und Außenfläche grafisch aufbereitet werden. Vielleicht könnte man dieses Panel zusätzlich oder statt dem Berechnet-Panel nennen.

# CSS-Eigenschaften für Abstand und Klickfläche erklären

> ... sowie andere berechneten CSS-Eigenschaften angezeigt, um etwa den Abstand der Elemente zu ermitteln (margin, padding).

Ich finde, das ist etwas eine Vermischung von der Klickfläche mit dem Abstand. Zum Abstand gehört doch eigentlich nur `margin`, oder? Die `padding`-Eigenschaft gehört noch zur Klickfläche. Außerdem gibt es noch die `border`-Eigenschaft. Bei dieser habe ich keine Spezifikation gefunden, wo sie explizit zur Klickfläche dazugezählt wird, wobei Firefox und Chrome eine `border `beispielswiese zu einem `<button>` klickbar machen. Was ich meine: Für den Abstand wäre nur `margin` zu nennen, aber man kann bei Bedarf auch eine Erklärung der CSS-Eigenschaften für die Klickfläche machen.

# Ausnahmenliste

> Prüfen, ob es sich bei den unterdimensionierten Elementen um Ausnahmen im Sinne des Prüfschritts handelt, denn diese werden nicht bewertet:

Es werden hier drei Ausnahmen genannt, die **gleichwertige Alternative** fehlt aber - die Abstandsausnahme fehlt zwar auch, sie wird aber in den Prüfpunkten davor bereits genannt. Wenn man hier Ausnahmen nennt, sollte es vollständig sein, die gleichwertige Alternative sollte also auch genannt sein. Alternativ könnte man die Ausnahmenliste auch weglassen und für die Ausnahmen auf den Was-wird-geprüft-Bereich verweisen.

**Comment by detlevhfischer** [comment]
@johannesFischer84 Danke für Deine Hinweise, ich habe die Prüfbeschreibung in PR #411 angepasst. 

Zur Ausnahmenliste: Wir erwähnen unter den Ausnahmen bereits:

> "Gleichwertige Alternative: Man kann mit einem anderen Bedienelement, welches die Anforderung erfüllt und sich auf derselben Seite befindet, die Funktion ausführen."

 (oder Sonja hat das zwischenzeitlich ergänzt).

**Comment by johannesFischer84** [comment]
@detlevhfischer Danke, Detlev, die ersten beiden Punkte sind erledigt. Bei der Ausnahmenliste / gleichwertige Alternative erkläre ich detaillierter, was ich meine:

Ich beziehe mich auf das Ende von Abschnitt "2. Prüfung". Dort steht:
> Prüfen, ob es sich bei den unterdimensionierten Elementen um Ausnahmen im Sinne des Prüfschritts handelt, denn diese werden nicht bewertet:
> * Native Bedienelemente, deren Größe vom Benutzeragenten bestimmt sind, etwa native Checkboxen
> * Ziele, deren Größe von umgebendem Text bestimmt sind (z. B. Textlinks in einem Absatz)
> * Eine bestimmte Darstellung des Ziels ist unerlässlich oder gesetzlich vorgeschrieben

Die Abstands-Ausnahme wurde innerhalb von "2. Prüfung" schon weiter oben genannt. Nun nennt die zitierte Liste die restlichen Ausnahmen. Nur die Ausnahme des weiteren Bedienelements fehlt in dieser Auflistung.
Natürlich sind die Ausnahmen alle schon im Abschnitt "Was wird geprüft" genannt, wie du richtig schreibst. Aber wenn innerhalb von "2. Prüfung" eine erneute Nennung der Liste erfolgt, sollte die eine fehlende Ausnahme auch noch genannt werden. Alternativ könntet ihr die Liste auch ganz weglassen und nur schreiben:
> Prüfen, ob es sich bei den unterdimensionierten Elementen um Ausnahmen im Sinne des Prüfschritts handelt, denn diese werden nicht bewertet. Siehe Abschnitt Was-wird-geprüft.

Übrigens hast du wohl aus Versehen im Abschnitt "Was wird geprüft" zuletzt die gleichwertige Alternative ein zweites Mal genannt, nämlich vor "Essentiell":
> * Benutzeragenten: Die Größe des Ziels [...]
> * *Gleichwertige Alternative
> * Essenziell: Eine bestimmte [...]

Diese zweite Erwähnung in Was-wird-geprüft kannst du wieder entfernen.

**Comment by detlevhfischer** [comment]
@johannesFischer84 Danke Joahannes, ich habe iie Prüfbeschreibung überarbeitet. Ich habe noch einen Verweis nebst kleiner Anleitung für die Chrome Extension von HalfAccessible hinzugefügt.

**Comment by johannesFischer84** [comment]
Vielen Dank :-)
