### ISSUE TITLE
3.2.6: Fall "Hilfe in Aufklappelement" nach G220 Ex. 3 fehlt bisher

### ISSUE THREAD

**Issue by johannesFischer84** [BIK-BITV/BIK-Web-Test#401]
In der Technik G220, die sich auf WCAG-Kriterium 3.2.6 bezieht, ist im [Example 3](https://www.w3.org/WAI/WCAG22/Techniques/general/G220#example-3-a-link-sometimes-in-a-disclosure-widget) die Möglichkeit angegeben, dass das Kriterium auch erfüllt ist, wenn sich die Hilfe auf manchen Seiten in einem Aufklappelement (disclosure) befindet. Zwar wird das nicht empfohlen, aber das Erfolgskriterium ist erfüllt.

Ich rege an, dass diese Möglichkeit in einem Hinweis zusätzlich erwähnt wird.

**Comment by detlevhfischer** [comment]
@johannesFischer84  Danke, #410 ergänzt den genannten Hinweis.
