### ISSUE TITLE
3.3.8, Nr. 2.1 Prüfung Anmeldevorgänge: Fehlende Positiv-Beispiele

### ISSUE THREAD

**Issue by johannesFischer84** [BIK-BITV/BIK-Web-Test#402]
Laut [WCAG-Understanding-Dokument](https://www.w3.org/WAI/WCAG22/Understanding/accessible-authentication-minimum.html) ist die Verwendung einer **Verifzierung mit Drittanbieter-Zugängen** konform, also z. B. mit Facebook- oder Google-Konto. Das wird im Understanding-Dokument durch folgendes Example deutlich:

> A web site offers the ability to login with a third-party provider using the OAuth method.

Weiterhin ist das Kriterium konform, wenn ein **Login mit eigenem Gerät (biometrisch)** erlaubt ist, dessen mögliche Alternativen unterstützt werden, z. B. Iris-Scan und Fingerabdruck. Dafür gibt es folgendes Example im Understanding:

> A web site uses WebAuthn so the user can authenticate with their device instead of username/password. The user's device could use any available modality. Common methods on laptops and phones are facial-scan, fingerprint, and PIN (Personal Identification Number). The web site is not enforcing any particular use, it is assumed a user will setup a method that suits them. 

Der **Scan eines QR-Codes auf anderem Gerät** ist ebenso konform im Sinne des Erfolgskriteriums, wozu ein Example genannt ist:

> A web site that requires two-factor authentication displays a QR code which can be scanned by an app on a user's device to confirm identity.

Zur Verdeutlichung sollten diese Dinge meiner Meinung nach entweder im Prüfung-Bereich (2.1) oder im Hinweis-Bereich (3.) genannt werden.

**Comment by detlevhfischer** [comment]
@johannesFischer84 Danke für Deine hilfreichen Hinweise und guten Vorschläge, habe ich soweit im PR #408 umgesetzt. Wenn Du zustimmst, könntest du dieses Issue #402 sowie #403 und #404 schließen.
