### ISSUE TITLE
3.3.8, Nr. 2.2 Prüfung 2-Faktor: Ergänzung Text-Einfügen für Webseite nicht blockiert

### ISSUE THREAD

**Issue by johannesFischer84** [BIK-BITV/BIK-Web-Test#403]
In der Prüf-Anleitung steht aktuell:
> ... Sofern es keine Alternative gibt (beispielsweise die Bestätigung eines Vorgangs mithilfe eines Links oder einer Schaltfläche), wäre dies als Fehler im Sinne des Prüfschritts zu werten.

Im Hinweis-Bereich (3.2) wird dagegen korrekt genannt, dass die Bewertung nur die Überprüfung erfordert, "ob der Webinhalt das Einfügen des Inhalts der Zwischenablage in das entsprechende Authentifizierungsfeld erlaubt."
Dass das Einfügen von Text in das Authentifizierungsfeld bei 2-Faktor-Authentifizierung nicht blockiert ist, sollte daher unter 2.2 zur Prüfung ergänzt werden.

**Comment by detlevhfischer** [comment]
@johannesFischer84 Danke. Sollte sinngemäß ergänzt sein, siehe #408 
Wenn's passt, bitte Issue schließen.
