### ISSUE TITLE
Prüfschritt 7.1.1 Wiedergabe von Untertiteln

### ISSUE THREAD

**Issue by richbdr** [BIK-BITV/BIK-Web-Test#423]
ich prüfe gerade Videoplayer und habe eine Frage zum Prüfschritt 7.1.1 Wiedergabe von Untertiteln.
 
Es ist nicht klar formuliert, ob der Button zum Einblenden der Untertitel (z.B. "CC" oder "UT") vor dem Abspielen des Videos sichtbar sein muss.  Einige Player zeigen die Schaltfläche erst nach dem Start des Videos an. 
 
Ist es zwingend erforderlich, dass der Button vor dem Abspielen des Videos sichtbar ist (sonst verpasst man eventuell den ersten Untertitel)?

**Comment by MarcHaunschild** [comment]
Relevant ist das nicht bei 7.1.1, sondern bei https://bitvtest.de/pruefschritt/bitv-20-web/bitv-20-web-7-3-bedienelemente-fuer-untertitel-und-audiodeskription
Gute Frage, ob das jetzt dieselbe Ebene ist. Es ist ja üblicherweise so, dass man ein Bild mit einem großen Dreieck als Vorschau hat und wenn man darauf klickt, wird der Player erst geladen. Unter Umständen läuft das Video schon. Wenn dann auf derselben Ebene wie der Play/Pause-Button Untertitel aktiviert werden, würde ich das nicht abwerten. Sicher kann man zum Anfang des Videos zurück.

**Comment by johannesFischer84** [comment]
@MarcHaunschild Marc, bei 7.3 wird vorausgesetzt, dass man Untertitel abspielen kann und es geht dann um die Menü-Hierarchie-Ebene, die gleich zu primären Funktionen wie Wiedergabe/Pause positioniert sein müssen. Vor Beginn der Wiedergabe würde ich ein Fehlen der Untertitel-Schaltfläche unkritisch sehen. Schwieriger ist die Frage zu beantworten, wenn die Schaltfläche für Untertitel vor Beginn des Videos nur in einem Untermenü zu finden ist, wärend Play/Pause direkt sichtbar ist.

@richbdr Aus meiner Sicht ist das schon bei 7.1.1 relevant, weil es dort um die Videoplayer geht und dass Untertitel vom Player angezeigt werden können. Wie Sie schreiben, ist es aber nicht klar formuliert bzw. es werden keine richtigen Vorgaben gemacht. Sofern die Schaltflächen direkt nach dem Start des Players zu sehen sind, würde ich mir da keine Gedanken machen. Man kann ggf. direkt das Video auf Position 0 zurückspulen, auch wenn das vielleicht etwas nervig ist und die Sichtbarkeit der Schaltfläche vor Beginn der Wiedergabe komfortabler wäre. Fehlerhaft im Sinne der EN 301 549 würde ich das aber nicht bewerten.

**Comment by richbdr** [comment]
Hallo @MarcHaunschild, @johannesFischer84,

wenn man die Prüfschritte in 7.3 anwendet, dann ist es in Ordnung, wenn das Untertitelelement erst beim Abspielen sichtbar wird.  Das ist genau so beschrieben: 

1. Das Video mit dem auf der Website eingebundenen Player **abspielen**.
2. **Prüfen, ob Bedienelemente zur Anzeige von Untertiteln** und / oder Audiodeskription auf gleicher Ebene wie die Bedienelemente zur Wiedergabekontrolle (z. B. Abspielen, Pause, Lautstärke etc.) **angeboten werden**.

Es sei also durchaus akzeptabel, wenn Untertitel erst beim Abspielen erscheinen.

Der Sinn von BITV ist es jedoch, Webseiten barriere**ARM** zu gestalten.

Wenn der Nutzer erst abspielen, dann Untertitel einschalten und dann zurück spülen muss, hat man bewusst eine Barriere geschaffen, die ein anderer Nutzer nicht hat.

Zu beachten ist auch, dass Untertitel in mehreren Sprachen angeboten werden können.  Die Aktivierung der Untertitel erfolgt daher nicht einfach durch Anklicken des Bedienelements, sondern durch Auswahl einer Sprache aus einem Menü und ggf. Einstellung der Schriftgröße etc.

**Comment by richbdr** [comment]
Hallo @MarcHaunschild , @detlevhfischer 

Vielen Dank für die sehr informativen Antworten.  Ich bin kein Experte (wie man sieht) und habe mich sehr über Ihre Hilfe gefreut.  Super Diskussion :-)

Grüße
Rich

**Comment by MarcHaunschild** [comment]
Hallo @richbdr ,

Gerne.

vielleicht noch ein kleiner Hinweis: bei mehreren Sprachversionen von Untertiteln ist dann auch 7.1.5 zu beachten...

https://bitvtest.de/pruefschritt/bitv-20-web/bitv-20-web-7-1-5-gesprochene-untertitel

**Comment by detlevhfischer** [comment]
@richbdr Ich denke, die Frage ist beantwortet und wir können das Issue schließen. Sonst gerne wieder öffnen.
