### ISSUE TITLE
Gebärdensprachevideos: Herunterladen und Angaben zur Größe der Datei

### ISSUE THREAD

**Issue by richbdr** [BIK-BITV/BIK-Web-Test#424]
Hallo (again),

In dem Gesetz "Verordnung zur Schaffung barrierefreier Informationstechnik nach dem Behindertengleichstellungsgesetz (Barrierefreie-Informationstechnik-Verordnung - BITV 2.0) Anlage 2 (zu § 3 Absatz 2)" unter Teil 1 steht:

_Für die Bereitstellung von Informationen in Deutscher Gebärdensprache im Internet oder Intranet gelten die folgenden Vorgaben:
...
7. Der Gebärdensprach-Film ist darüber hinaus als Datei zum Herunterladen verfügbar.
Es sind Angaben zur Größe der Datei sowie zur Abspieldauer verfügbar._

[https://www.gesetze-im-internet.de/bitv_2_0/anlage_2.html](url)

Meine Fragen sind:

1. Ist das Gesetz aktuell und anwendbar?
2. Ist es dann richtig, dass Gebärdensprachevideos heruntergeladen werden können müssen und dass Angaben zur Dateigröße vorhanden sein müssen?
3. Gibt es hierfür einen Prüfschritt?

Danke 
Rich

**Comment by MarcHaunschild** [comment]
Hallo zurück,

> 1. Ist das Gesetz aktuell und anwendbar?

Ja

> 2. Ist es dann richtig, dass Gebärdensprachevideos heruntergeladen werden können müssen und dass Angaben zur Dateigröße vorhanden sein müssen?

So verstehe ich das.

> 3. Gibt es hierfür einen Prüfschritt?

Nein. Es wird nur HTML geprüft. Die Videos selber nicht.

Der Test überprüft ja sowieso nicht die BITV direkt, sondern die europäische Norm EN 301 549 die ich n Paragraf 3 der BITV genannt wird.

Der Name BITV-Test ist historisch bedingt. Das Verfahren wurde so genannt weil mit dem Test früher tatsächlich die BITV getestet wurde, die damals einen eignen Anhang mit Kriterien enthielt.

Dieser ist später weggefallen und jetzt wird Konformität zur EN geprüft.

Siehe auch https://bitvtest.de/tests-und-beratung/bik-bitv-test-web

**Comment by richbdr** [comment]
Hallo,

meine Frage zielte nicht darauf ab, ob der Inhalt des Videos noch gesetzeskonform ist, sondern ob das Video heruntergeladen werden kann.  Das ist eine Anforderung an die Webseite bzw. den Player und nicht an das Video selbst. Es geht nicht um die Prüfung eine heruntergeladene Dokument.

z.b. hier ist eine sehr schöne Beispiel: https://www.bundesregierung.de/breg-de/mediathek/dgs-video-feedback-und-kontakt-1677082

**Comment by sweckenmann** [comment]
@richbdr Wir haben einen Artikel veröffentlicht [Was prüft der BITV-Test, was prüft er nicht](https://bitvtest.de/blog/detail/die-bitv-20-was-prueft-der-bitv-test-was-prueft-er-nicht). Hier finden Sie auch Informationen zum Thema Gebärdensprachvideos.

**Comment by richbdr** [comment]
Hi @sweckenmann 
ja ich habe verstanden, dass man den Inhalt das Videos nicht prüfen soll.  Jedoch hier geht es um eine Bedienung der Webseite und zwar ob es eine Möglichkeit gibt das Video herunterzuladen wie im Bundesgesetz vorgeschrieben ist.
Grüße Rich

**Comment by Andreas-Englisch** [comment]
@richbdr Der BITV-Test prüft eben nicht nach BITV, sondern nur nach EN 301 549. Somit sind ALLE zusätzlichen Anforderungen aus der BITV nicht abgedeckt, auch nicht die Frage, ob das Video heruntergeladen werden kann.

**Comment by MarcHaunschild** [comment]
> Hi @sweckenmann ja ich habe verstanden, dass man den Inhalt das Videos nicht prüfen soll. Jedoch hier geht es um eine Bedienung der Webseite und zwar ob es eine Möglichkeit gibt das Video herunterzuladen wie im Bundesgesetz vorgeschrieben ist. 

Kleine Korinthe: es ist kein Gesetz, sondern eine Verordnung.  BITV steht für Barrierefreie Informations-Technik Verordnung.

Darüber hinaus steht im von @sweckenmann genannten Link (der auch auf der von mir verlinkten Seite genannt wird), was ich bereits schrieb: geprüft wird die EN 301 549 - die harmonisiert die vorher sehr unterschiedlichen Vorgaben zur Barrierefreiheit in den Mitgliedsländern.

Sie ist aber ein freiwilliger Mindeststandard (aus EU-Sicht), der erst durch den Verweis in der BITV hier in Deutschland verbindlich wird. Die Idee ist, dass man mit der BITV eben keinen Kriterien-Katalog mehr braucht, sondern dass immer die aktuelle Version der EN geprüft wird.

Und zwar nur Web-Dokumente.

Weil die EN aus der BITV referenziert und dadurch die relevante Anforderung an Barrierefreiheit im Sinne von BITV wird, ist der Name auch nicht falsch. Das habe ich zwar nicht gesagt, aber der Hinweis von @detlevhfischer  war natürlich wichtig, dass die Anforderungen der BITV weiter gehen, als das was dieser Test überprüft hat und dass das auch schon immer so war. Darum gibt es ja eine Seite, auf der genau erklärt wird, was geprüft wird.

Nun fordert die EN diese Dinge aber nicht und der Test prüft Konformität zur EN und versucht dabei sehr nah an der WCAG zu sein.

Daher gibt es vermutlich auch keinen entsprechenden Prüfschritt - @detlevhfischer und @sweckenmann  können das vielleicht noch mal bestätigen.

**Comment by Andreas-Englisch** [comment]
@MarcHaunschild 

> Was hat ein Betroffener davon? Welchen Vorteil siehst du darin für Menschen mit Behinderungen?

Darüber könnte diskutiert werden. Aber es ist völlig irrelevant, zu welchem Ergebnis wir da kommen, denn Fakt ist, dass es die BITV verlangt und es somit geprüft werden müsste, wenn das Prüfverfahren Konformität zur BITV feststellen will (wie ja unter https://bitvtest.de/ auf der ersten Kachel behauptet wird).

**Comment by MarcHaunschild** [comment]
> @MarcHaunschild
> 
> > Was hat ein Betroffener davon? Welchen Vorteil siehst du darin für Menschen mit Behinderungen?
> 
> Darüber könnte diskutiert werden.

Lieber nicht. Mich hat nur der Hintergrund der Frage interessiert.

> Aber es ist völlig irrelevant

Genau.

> denn Fakt ist, dass es die BITV verlangt und es somit geprüft werden müsste, wenn das Prüfverfahren Konformität zur BITV feststellen will (wie ja unter https://bitvtest.de/ auf der ersten Kachel behauptet wird).

Nein, da steht schon auch die EN: 

> Mit dem BITV-Test (Web) ermitteln wir die Konformität Ihres Webangebots gemäß BITV 2.0 / EN 301 549 und unterstützen Sie dabei, Barrierefreiheit umzusetzen.

Ich halte es auch für absolut notwendig, das so zu formulieren, weil diejenigen, die eine Konformitätsprüfung brauchen sehr oft nicht wissen, dass es so etwas wie die EN gibt. Es würde also gar keinen Sinn machen, einen EN-Test anzubieten statt einen BITV-Test nach EN. Weil einen EN-Test würde niemand buchen.

**Comment by MarcHaunschild** [comment]
> Es würde also gar keinen Sinn machen, einen EN-Test anzubieten statt einen BITV-Test nach EN. Weil einen EN-Test würde niemand buchen.

Was mir gerade einfällt: die Prüfung nach EN ist natürlich auch für Organisationen interessant, die in den Geltungsbereich des BFSG fallen.

Vielleicht sollte wir das noch ein bisschen deutlicher kommunizieren als das derzeit passiert - das könnten wir intern mal diskutieren...

**Comment by richbdr** [comment]
Hallo zusammen,
ich möchte kurz erklären, wie ich vorgegangen bin.  Ich muss mehrere Videoplayer prüfen - unter anderem auf Barrierefreiheit.  Über Google kommt man auf die BIK Webseite, BITV Prüfverfahren und auch die BITV "Gesetzt" (steht ja unter gesetze-im-internet).
Dort findet man, dass ein Gebärdensprachvideo heruntergeladen werden muss.  Warum weiß ich auch nicht - ist für mich nicht zu hinterfragen.
Um bei jedem Player gleich vorzugehen, versuche ich die BITV-Web (und APP) Prüfschritte anzuwenden.  
Aber in den Prüfschritten finde ich nichts zum Thema "Herunterladen eines Gebärdensprachvideos".  Ich bin dann verunsichert - ist das "Gesetz" anwendbar oder fehlt ein Prüfschritt?  Und deshalb habe ich hier meine Frage gestellt.

Gesetz vs. Verordnung: Wenn man das googelt, findet man dieses Beispiel:
https://praxistipps.focus.de/unterschied-zwischen-gesetz-und-verordnung-einfach-erklaert_124657

- Ein gutes Beispiel für den Zusammenhang zwischen Gesetz und Verordnung ist das Gesetz über die Gleichstellung behinderter Menschen. Das Gesetz beinhaltet unter anderem die Barrierefreiheit.
- Wie diese gesetzlich geforderte Barrierefreiheit jeweils umgesetzt wird, wird über eine Verordnung geregelt. Diese Verordnungen bestimmen beispielsweise, wie öffentliche Gebäude oder Verkehrsmittel gestaltet sein müssen, um der geforderten Barrierefreiheit zu entsprechen. 

Das verstärkt mein Verständnis, dass ein Gebärdensprachvideo herunterladbar sein muss.

Das ist an sich schon alles, was ich zu verstehen versucht habe:

a) Gibt es hier eine "gesetzliche" Verpflichtung? 
b) wenn ja, gibt es einen Prüfschritt, den ich übersehen habe?

**Comment by MarcHaunschild** [comment]
Hallo Rich,

ich versuche noch mal ein bisschen zu klären, aber dann sollten wir das Issue hier vielleicht schließen. Du bist ja im Git-Repository zur Weiterentwicklung des BIK-BITV-Tests. Zum Lernen von Barrierefreiheit gibt es andere Foren, z.B. auf LinkedIn o.ä.

1. der Test hier prüft Konformität von Webdokumenten (HTML) zur EN.
2. Die Einhaltung der EN wird von BFSG und BITV gefordert
3. BFSG gilt für die Privatwirtschaft
4. BITV gilt für öffentliche Stellen
5. es gibt zahlreiche Gesetze in denen Barrierefreiheit behandelt wird. Ein sehr wichtiges hast du genannt, das Gesetz zur Gleichstellung von Menschen mit Behinderungen (BGG), die BFIT Bund listet aber mehr als 110 Vorschriften (Gesetze und Verordnungen), die allein für den Bund gelten mit einem Bezug zur Barrierefreiheit. https://www.bundesfachstelle-barrierefreiheit.de/DE/Rechtssammlung/suche_node.html Für die Länder gelten oft weitere Regelungen, u.U noch mehr für bestimmte Kommunen. Das alles bezieht sich ausschließlich auf öffentliche Stellen
6. Darüberhinaus gibt es weitere Rechtsvorschriften für die Privatwirtschaft
7. Der Test hier prüft nicht alles, wasin diesen Gesetzen steht, auch nicht alles, was die BITV verlangt
8. Konform zu allen gesetzlichen Anforderungen ist man natürlich erst, wenn du nicht nur die EN, sondern auch alle anderen anzuwendenden Vorschriften einhältst
9. Dein Vorgehen ist sinnvoll, alle (dir bekannten) Vorschriften zu prüfen und dann für den Player ein Fazit zu ziehen. Es ist nicht notwendig, dass dazu immer ein Prüfschritt existiert
10. du kannst auch weitere Tests durchführen (z.B. sind die Videos inhaltlich korrekt?) und bewerten. Im Grunde entwickelst du so ein Prüfverfahen über umfassende Konformität von DGS-Videos. Das kann sehr sinnvoll sein, ist dann aber schlicht und ergreifend ein anderes Verfahren, das speziell für DGS-Videos konzipiert ist und viele Dinge aus dem Test hier überhaupt nicht testen muss. Beispielsweise muss weder im Videoplayer, noch im Video geschaut werden, ob es da Überschriften gibt und die ganzen Prüfschritte zu zwei-Wege-Kommunikation, Formularen u.a.m fallen weg. Ob du Doku prüfst oder nicht, liegt letztlich an dir und sollte dokumentiert werden.
11. Um einen eigenen Prüfkatalog zu erstellen und danach zu prüfen gibt es übrigens spezielle kostenpflichitge Tools. Ich weiß, dass CAAT so was kann. https://www.caat.report/de

**Comment by richbdr** [comment]
Hi @MarcHaunschild,
Super antwort, und ich werde damit dann das Ticket schliessen.
Besten Dank
Rich
