### ISSUE TITLE
9.1.1.1.b longdesc Verwendung wird nicht mehr empfohlen 

### ISSUE THREAD

**Issue by ovau** [BIK-BITV/BIK-Web-Test#428]
Ich bin gerade im Artikel von WebAIM über Alternativtexte über einen Hinweis gestolpert, dass das londesc Attribut nicht mehr aktiv unterstützt wird in HTML: https://webaim.org/techniques/alttext/#complex MDN sagt  ebenfalls, dass das Attribut nicht weiter unterstützt wird: https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/longDesc 
Sollte der entsprechende Hinweis auf diese Technik dann nicht aus den Prüfschritt-Erläuterungen (2.6 Angemessenheit von Textalternativen im Kontext) entfernt werden?

**Comment by johannesFischer84** [comment]
Stimmt, in der HTML-Spezifikation ist das `longdesc`-Attribut im Abschnitt 16.3.3 (https://html.spec.whatwg.org/multipage/obsolete.html#other-elements%2C-attributes-and-apis) zu obsoleten Elementen und Attributen erwähnt.

**Comment by detlevhfischer** [comment]
Guter Hinweis.
Habe `longedesc` rausgenommen und die Beschreibung der Langtextalternative noch etwas angepasst. Siehe #431
