### ISSUE TITLE
Prüfschritt 9.2.2.2 Bewegte Inhalte abschaltbar - Mindestzeit für Werbung essentiell

### ISSUE THREAD

**Issue by ThomKoeh** [BIK-BITV/BIK-Web-Test#429]
Hallo zusammen,

da ja das Barrierefreiheitsstärkungsgesetz ab 2025 greift, werden wir höchstwahrscheinlich beim Testen vermehrt auf Werbung stoßen. Für Werbung gibt es ja unter anderem die Anforderung (9.2.2.2 Bewegte Inhalte abschaltbar), dass sie anhaltbar sein soll.

Es tauchen ja oft Werbungen auf, die eine Mindestdauer haben. Zum Beispiel, wenn in einem Spiel ein Video eingeblendet wird, das mindestens eine Minute angesehen werden muss, um überhaupt weiter zu kommen. Es ist möglich, dies als essentiell zu betrachten, da es ja Teil eines Geschäftsmodells ist. Ablenkend und verwirrend kann es trotzdem sein. Hier sehe ich eine Diskrepanz zwischen Geschäftsmodell und Barrierefreiheit und wäre froh, wenn ich hier Meinungen dazu erhalten könnte.

Oft tauchen Elemente auf, die anhaltbar bzw. ausblendbar sind. Das ist jedoch oft nicht von Dauer, da nach einer gewissen Zeitspanne neue Werbung an der Stelle auftaucht. Hier würde dies auch unter 9.2.2.2 als Fehler zu dokumentieren. Hierzu würde ich mich auch über Einschätzungen freuen.

Prinzipiell als nicht essentiell und als Barriere und Fehler sehe ich flackende Inhalte, egal ob es das Geschäftsmodell hergibt oder nicht.

Vielen Dank für Eure Einschätzungen!

**Comment by MarcHaunschild** [comment]
Ich glaube, bei deinem Beispiel mit dem Film, den man erst ansehen muss, gibt es kein Problem.
Bewegte Inhalte sind ja störend neben anderen Inhalten, von denen abgelenkt werden soll.
Die gibt es in deinem Beispiel aber nicht. Da ist der Film ja der Inhalt.
Klar sollte man ihn pausieren und noch mal von vorn anschauen können.
Wenn man will, muss man den Film verstehen können, also muss er auch Untertitel haben und alle anderen Anforderungen an Barrierefreiheit erfüllen.

**Comment by Carsten-Harms** [comment]
Das ist bei dem Film schon auch ein Problem, da Werbefilmchen sich oft durch schnelle Schnitte und - im wahrsten Sinne - von einem Feuerwerk blinkender Glitzereffekte mitgeprägt werden, die beipielsweise die Anfallsgefährdung betroffener Menschen dramatisch erhöht. 
So gesehen gibt es da auch beim Film ein Problem!

**Comment by johannesFischer84** [comment]
Wenn die Bewegung parallel zu anderen Inhalten dargestellt wird, muss sie pausierbar sein. Parallel dargestellte animierte Werbung ist aus meiner Sicht auch nicht essentiell, denn man könnte sie als alleinigen Inhalt darstellen.  Bei alleiniger Darstellung wie bei dem beschriebenen Spiel, wo die Werbung 1 Minute angesehen werden muss und bei dem man während des Abspielens der Werbung keine anderen Inhalte nutzen kann, ist WCAG 2.2.2 nicht anwendbar.

Flackerende Inhalte gehören nicht zu 2.2.2, sondern zu 2.3.1. Wobei der Übergang zwischen beiden Prüfschritten etwas fließend ist.

**Comment by sweckenmann** [comment]
>  Bei alleiniger Darstellung wie bei dem beschriebenen Spiel, wo die Werbung 1 Minute angesehen werden muss und bei dem man während des Abspielens der Werbung keine anderen Inhalte nutzen kann, ist WCAG 2.2.2 nicht anwendbar.

@johannesFischer84 Woher leitest du das ab? Nutzende aktivieren ja nicht selbständig das Spiel (oder eienen Film). Die Werbung ist Teil des digitalen Angebots (der Anbieter verantwortlich, welche Art von Werbung er schaltet) und somit ist automatisch abgespielte Bewegung vorhanden, welche nicht abgeschaltet werden kann (möglicherweise auch Audio, wobei sich das meist abschalten lässt). 

Mir ist schon klar, dass das bedeuten würde, das derartige Werbung dann nicht mehr möglich wäre und hier Werbeeinnahmen flöten gingen.

**Comment by johannesFischer84** [comment]
> Bei alleiniger Darstellung wie bei dem beschriebenen Spiel, wo die Werbung 1 Minute angesehen werden muss und bei dem man während des Abspielens der Werbung keine anderen Inhalte nutzen kann, ist WCAG 2.2.2 nicht anwendbar.
> @johannesFischer84 Woher leitest du das ab?

@sweckenmann Sonja, in der Anforderung des Erfolgskriterium heißt es:

> For any moving, blinking or scrolling information that (1) starts automatically, (2) lasts more than five seconds, and (3) is presented in parallel with other content, there is [...]

Ich leite das aus Nummer (3) ab. Voraussetzung für die Anwendbarkeit ist, dass der animierte Inhalt parallel zu anderen Inhalten angezeigt wird. Wenn also Text auf einer Seite steht, den ich lesen will und dann ist irgendwo im Fenster zusätzlich animierter Inhalt, stört das. Wenn aber der Werbefilm alleine dargestellt wird, z. B. in einem Overlay vor die Seite geblendet wird, ist der Werbefilm der einzige Inhalt, den ich wahrnehme. Er wird dann nicht parallel zu anderen Inhalten dargestellt und damit ist das Anwendbarkeitskriterium nicht gegeben.

**Comment by detlevhfischer** [comment]
ich denke, @MarcHaunschild und @johannesFischer84 haben Recht, dass die Anforderung nicht greift, wenn die bewegten Inhalte nicht parallel zu anderen angeboten werden. Ein Vorgeschaltetes Video wäre also ärgerlich für alle, aber keine Barriere im Sinne dieses Prüfschritts.

@ThomKoeh wenn Werbung angehalten wird und von alleine eine andere animierte Werbung wieder anfängt, würde ich das als klares FAIL sehen, selbst wenn sich auch diese zweite Werbung stoppen ließe, denn die Bewegung soll ja nachhaltig abschaltbar sein. Das ließe sich auch durch den Punkt 2 zu Auto-Updating rechtfertigen (hier auto-updated sich ja die Werbung). (Einziges Loophole bei diesem Punkt ist, dass normativ nicht verlangt wird, dass die Frequenz auch auf null  - "gar nicht mehr" - gestellt werden können muss.) Aber schon der erste Punkt (moving, blinking, scrolling) impliziert m.M. nach, dass "Stoppen" bedeutet, dass dann nichts mehr von alleine erneut loslegt nach einer Pause.

@ThomKoeh Können wir das Issue schließen?
