### ISSUE TITLE
 11.7 Benutzerdefinierte Einstellungen - Mindestschriftgröße

### ISSUE THREAD

**Issue by stefanFarnetani** [BIK-BITV/BIK-Web-Test#451]
In der Prüfanleitung steht unter Punkt 2:
>  In den Einstellungen "Erweitert…​" sollte für Mindestschriftgröße "Keine" ausgewählt sein.

Ich habe gerade den Fall, dass die Anpassung der Schriftgröße in Firefox keine Auswirkung hat, aber die Einstellung einer Mindestschriftgröße Wirkung zeigt.

Wenn nur durch die Einstellung der Mindestschriftgröße die Vergrößerung der Schrift abgedeckt wird, ist die Anforderung der Anpassung der Schriftgröße im Prüfschritt 11.7 damit auch erfüllt?

In der Prüfanleitung steht "sollte". Also ist es kein Verbot diese Funktion zu nutzen?

Gibt es einen Grund wieso nicht generell mit der Funktion Mindestschriftgröße getestet wird? Ich habe ein wenig herum getestet und es scheint, als ob die Funktion deutlich stabiler die Schrift vergrößert.

**Comment by sweckenmann** [comment]
@stefanFarnetani Wir hatten die Diskussion schon mal in einem issue. Ich erinnere es nicht mehr genau, aber ich glaube, wenn du in Chrome die Schriftgröße in den Browsereinstellungen vergrößerst, würde sie sich nicht verändern, kann das sein - hast du das mal ausprobiert? Oder wie es ein anderer Prüfer mal ausgedrückt hat, eigentlich prüfen wir hier, ob die Voraussetzungen gegeben sind, dass sich die Schrift vergrößern lässt, nämlich dass die Schriftgröße in relativen Maßeinheiten angegeben ist. 

(Btw wir sind in den Prüfanleitungen glaube ich nicht so konequent mit "soll" und "muss").

**Comment by sweckenmann** [comment]
Ich glaube, das war das entsprechende issue https://github.com/BIK-BITV/BIK-Web-Test/issues/258 ob es jetzt viel weiterhilft weiß ich nicht, aber bei 11.7 muss auf EN-Ebene viel gklärt werden.

**Comment by johannesFischer84** [comment]
Stefan, vielleicht hilft dir auch mein Kommentar aus dem [Issue 190 am 26. April 2021](https://github.com/BIK-BITV/BIK-Web-Test/issues/190#issuecomment-826814254) weiter. Also möglicherweise hat die Webseite zum Beispiel im `<html>`-Element ein `font-size` als CSS hinterlegt.

**Comment by stefanFarnetani** [comment]
@sweckenmann danke für die Verknüpfung. Ich hatte eigentlich gesucht. Bin anscheinend nicht sehr aufmerksam gewesen. Lustigerweise hatte ich in dem thread sogar mitgeschrieben. 

@johannesFischer84 Danke für den Hinweis. Es könnte technisch wirklich daran liegen.

Wenn ich es richtig hat auch die alte Diskussion nicht beantwortet, ob wir den Prüfschritt als erfüllt betrachten. Wenn ich in Firefox und in Chrome/Edge jeweils die Mindestschriftgröße als Funktion nutze, dann erreiche ich eine Veränderung. 
Bewerten wir das als ausreichend? WCAG ist agnostisch. Die Funktion ist in beiden großen Desktop-Browsern verfügbar.

**Comment by sweckenmann** [comment]
@stefanFarnetani Wenn ich es dem anderen Faden richtig entnommen habe, geht es letztendlich darum, ob man die Schriftgrößenangabe in Pixel akzeptiert oder nicht. Richtig?

Wir hatten damals die jetzige Formulierung eingeführt (siehe Verlinkung auf den PR in dem anderen issue). Stand heute prüfen wir ohne Nutzung der Mindestschriftgröße. Auch wenn das "sollte" vielleicht nicht ideal formuliert ist.

Es gab ja Stimmen, die meinten px-Angabe wäre nicht akzeptabel und ich meine, in Chrome gabs die Änderung der Mindestschriftgröße nicht, was letztendlich ausschlaggebend war (oder wir haben damals da was übersehen)?

11.7 ist aber eh ein großes Thema, dass wir auch bei den EN-Macher*innen einbringen, ich hoffe, dass es auch in anderer Hinsicht hier noch Klärung gibt. @detlevhfischer es gibt ja ein issue zum Thema Farbeinstellungen dort, das Thema sollte man vielleicht noch ergänzen.

**Comment by MarcHaunschild** [comment]
> Gibt es einen Grund wieso nicht generell mit der Funktion Mindestschriftgröße getestet wird? Ich habe ein wenig herum getestet und es scheint, als ob die Funktion deutlich stabiler die Schrift vergrößert.

Mindestschriftgröße auf z.B. 32 Pixel bedeutet, dass man Überschriften und Fließtexte alle gleich dargestellt bekommt. Seitenstrukturen sind so nicht mehr erkennbar.

Bei der "normalen" Schtiftvergrößerung wachsen alle Schriften proportional zueinander und die visuellen Hervorhebungen durch Schriftgrößen bleiben erhalten.

Aber das ist meine persönliche Erklärung. Wie Sonja sagte, fehlt es hier an Text von Seiten ETSI/ EN-Autoren. Eine offizielle Begründung wäre mir lieber auch wenn ich selber Texte extrem schwierig zu lesen finde, in denen sich Überschriften nicht von Fließtext unterscheiden lassen. Man kann solche Seiten praktisch nicht mehr scannen und der Aufwand steigt erheblich für Nutzerinnen.

**Comment by stefanFarnetani** [comment]
Ok. Danke. An alle Teilnehmer.
Damit ist das für mich geklärt wie der BIK-Test vorgeht.
Das reicht mir erstmal.
Eine genauere Klarstellung durch die offizielle Stelle wäre wünschenswert.
Bis dahin bin ich mit der gemeinsamen Position glücklich.

Ich schließe dieses Faden. Vielen Dank.
