### ISSUE TITLE
Klarstellung zu Anwendbarkeit von 11.8.2 Barrierefreie Erstellung von Inhalten 

### ISSUE THREAD

**Issue by barigorokarl** [BIK-BITV/BIK-Web-Test#452]
Da es gerade intern zu einer Diskussion kam, würden wir uns über eine Klarstellung zu diesem Prüfschritt freuen: :-)

Wir bieten eine Kommentarfunktion an, in der man eine Überschrift und einen Kommentar _in zwei getrennten Textfeldern_ eintragen kann. Ohne, das jedwede WYSIWYG Funktionalität angeboten wird. 

Es gibt also nur ein `<input type="text>` und eine `<textarea>`.

Wir haben das unter "Fällt nicht unter diesen Prüfschritt" einsortiert, da wir den Editor nicht als Autorenwerkzeug in diesem Sinne ansehen.

> Ebenfalls anwendbar ist der Prüfschritt auf Kommentarfunktionen, die die Strukturierung von Kommentaren erlauben, zum Beispiel **die Vergabe einer Kommentar-Überschrift** oder Funktionen zur Binnenauszeichnung des Kommentars, etwa Listen oder Texthervorhebungen.

lässt sich so verstehen. 

Allerdings sorgt das Template danach für eine semantische Auszeichnung der beiden Eingaben.

Ist das wohl richtig von uns eingeordnet?

Danke schonmal!

**Comment by stefanFarnetani** [comment]
Sehe ich wie @marcus-herrmann .
Es handelt sich um eine Art "Mini"-Autorentool.
Prüfschritt ist damit "anwendbar".

**Comment by barigorokarl** [comment]
@marcus-herrmann 

> Wenn ich richtig verstehe, unterstützt damit das Autorentool die Erstellung von barrierefreien Dokumenten, man kann sogar selbst mit bösen Vorsatz keine unzugänglichen erstellen, durch die Architektur. Anwendbar + erfüllt, oder?

Ja, richtig, Tags werden gefiltert.

Okay, ich sehe mich korrigiert ;-) 

Vielen Dank für die schnellen Antworten!

Ich bin sowieso begeistert von der Community hier, wäre schön, wenn das so an anderer Stelle auch funktionieren würde :-)
