### ISSUE TITLE
9.3.1.2 Sprache von Teilen: WCAG-Ausnahmen erwähnen

### ISSUE THREAD

**Issue by johannesFischer84** [BIK-BITV/BIK-Web-Test#46]
Bei der Auszeichnung fremdsprachiger Abschnitte und Sätze erlaubt die WCAG ein paar Ausnahmen, wo eine Auszeichnung nicht erforderlich ist:
> except for proper names, technical terms, words of indeterminate language, and words or phrases that have become part of the vernacular of the immediately surrounding text

Diese Ausnahmen sind in der Prüfanleitung bisher nicht erwähnt (außer dem letzten Teil mit aus anderen Sprachen entlehnten Begriffen). Man könnte dafür zum Beispiel den Prüfpunkt 3 folgendermaßen ergänzen:
Prüfen, ob andersprachige Wörter und Abschnitte richtig ausgezeichnet sind. Eine Ausnahme gilt für Eigennamen, Fachbegriffe und unklare Sprache (siehe auch 3.Hinweise).

**Comment by detlevhfischer** [comment]
@johannesFischer84 Ich habe das in PR #62  übernommen - guckst Du noch mal?

**Comment by johannesFischer84** [comment]
@detlevhfischer Sieht gut aus so, danke :-)
