### ISSUE TITLE
9.2.4.3 Schlüssige Reihenfolge bei der Tastaturbedienung - Link auf Show Tab Focus bookmarklet fehlerhaft

### ISSUE THREAD

**Issue by JSchwehn** [BIK-BITV/BIK-Web-Test#462]
Hi, mir ist aufgefallen das der Link auf das `Show Tab Focus` bookmarklet von Jeff Smith auf eine 404 Seite führt.
Die korrekte URL wäre `https://codepen.io/jeffsmith/details/bebKpq`. Ist es Ok, wenn ich einen PR stelle?

**Comment by detlevhfischer** [comment]
@JSchwehn gerne! Danke für die Aufmerksamkeit.

**Comment by JSchwehn** [comment]
@detlevhfischer Habe den PR erstellt. https://github.com/BIK-BITV/BIK-Web-Test/pull/463
