### ISSUE TITLE
Link zu Github Issue wird nicht richtig angezeigt

### ISSUE THREAD

**Issue by detlevhfischer** [BIK-BITV/BIK-Web-Test#5]
In der Ausgabe der Prüfschritte wird anscheinend der Ausdruck  GitHub {web-issue-url}[ein Issue zu diesem Prüfschritt erstellen]. nicht als Link umgesetzt,

**Comment by helmsaccess** [comment]
Github scheint das Inkludieren von anderen Dateien nicht zu unterstützen, daher wird die Datei mit den Variablen in include/attributes.adoc nicht eingefügt, sodass die Variable nicht aufgelöst werden kann.

Bei der Umwandlung in HTML-Dateien gibt es dieses Problem nicht. Bis GitHub dieses Feature unterstützt, können wir den Issue-Link nur auf herkömmliche Weise einbinden. Allerdings ist die Issue-Page ja auch hier in der Repo-Navigation immer erreichbar.
