### ISSUE TITLE
6.4 und 6.5.4 nicht in Tabelle A1 (Webseiten) - keine Prüfung nötig

### ISSUE THREAD

**Issue by johannesFischer84** [BIK-BITV/BIK-Web-Test#56]
Die Anforderungen 6.4 (Alternativen zu sprachbasierten Diensten) und 6.5.4 (Synchronität bei Videotelefonie) sind in der EN 301 549 weder in Version 2.1.2 noch in Version 3.1.1 in der Tabelle A1 für Webseiten-Prüfung enthalten. Daher müssten sie für Webseiten nicht geprüft werden.

In Tabelle A2 für mobile Anwendungen sind sie dagegen enthalten. Ich vermute, dass diese Inkonsistenz ein Fehler in der Norm ist. Jedoch sollte man in den beiden Prüfschrittanleitungen des Web-Tests vielleicht darauf hinweisen, dass die Prüfungen bei Webseiten von der Norm aktuell nicht gefordert sind.

**Comment by helmsaccess** [comment]
@johannesFischer84 vielen Dank für den Hinweis, ich habe beide Prüfschritte in den Ordner "optional" verschoben.

Das Issue wird durch Commit https://github.com/BIK-BITV/BIK-Web-Test/commit/c102293e52b3b26acbf4795963025d7a04513273 geschlossen.
