### ISSUE TITLE
11.6.2 Einordnung meta viewport user-scalable=no

### ISSUE THREAD

**Issue by CarstenKaul** [BIK-BITV/BIK-Web-Test#69]
Habe hier im github zum Suchwort viewport nichts passendes gefunden, also habe ich dazu folgende Frage:

Im Hinblick auf die EN 301 549- Anforderung 11.6.2 (Keine Unterbrechung der Barrierefreiheitsfunktionen) frage ich mich, ob ich einen meta-viewport mit "user-scalable=no" nicht besser dort einordnen sollte, anstatt wie bisher in 9.1.4.4 (Text vergrößern).

**Comment by johannesFischer84** [comment]
Das WCAG-Kriterium 1.4.4 schreibt die Vergrößerungsmöglichkeit auf 200% vor. Wenn `user-scalable=no` eingesetzt wird und keine andere Vergrößerungsmöglichkeit besteht, würde ich das auf jeden Fall als WCAG-1.4.4-Fehler sehen.

Das Kriterium 11.6.2 der EN 301 549 ist in Version 2.1.2 in Tabelle A1 für Webseiten enthalten, bei Version 3.1.1 nicht mehr. Wenn das Kriterium bewertet wird, könnte man aus meiner Sicht auch dort einen Fehler anmerken, weil die Barrierefreiheitsfunktion Vergrößerung des Browsers umgangen wird, ohne eine alternative Form bereitzustellen.

Ich würde also im Bedarfsfall bei beiden Kriterien einen Fehler sehen.

**Comment by CarstenKaul** [comment]
Danke. *closed*
