### ISSUE TITLE
12.2.3 Effektive Kommunikation , allgemeine Kontaktinformationen

### ISSUE THREAD

**Issue by CarstenKaul** [BIK-BITV/BIK-Web-Test#71]
Wie ist bei Webseiten und Software zu verfahren, wenn dort nur eine Kontaktadresse angeben ist. Diese Adresse also nicht deutlich als "Support" oder "Helpdesk" bezeichnet ist und somit als einzig sinnvoller und verfügbarer Kontakt für Rückfragen zu verstehen ist?
Die Beschränkung auf "Unterstützungsdienste" mit dem Hinweis, dass sich diese unter anderem auf "Helpdesks, Callcenter, technischer Support, Umsetzungsdienstleistungen und Schulungen" beziehen wäre m.E. in dem Kontext nicht ausreichend.

**Comment by johannesFischer84** [comment]
Auch wenn in 12.2.1 steht, dass "ICT support services" nicht auf die Beispielliste beschränkt sind, fällt meiner persönlichen Ansicht eine einfache Kontaktmöglichkeit nicht in den Anwendungsbereich. Ein Unterstützungsdienst muss zumindest Hilfestellung bei der Nutzung der Inhalte bieten. Die Kontaktmöglichkeit sollte dafür klar so gekennzeichnet sein, dass man Fragen zu den Inhalten des Auftritts klären kann. Nur dann würde ich sie als Unterstützungsdienst zählen. Auf der Seite des [Verkehrsverbundes im Vogtlandkreis](https://vogtlandauskunft.de) gibt es eine `h3` "Servicetelefon". So etwas wäre für mich ein Unterstützungsdienst.

Bei einfachen Kontaktmöglichkeiten, die keine zweite Alternative bieten, würde ich wahrscheinlich einen Hinweis im Sinne einer dringenden Empfehlung geben. Ich würde es auch gut finden, wenn man das fordern kann. Aber aus meiner Sicht gibt das die Anforderung 12.2.3 nicht her.

**Comment by CarstenKaul** [comment]
Sehe ich auch so wie Du. Meine Frage bezieht sich auch nur auf den speziellen Fall, das für die zu prüfende Anwendung/den Dienst ein entsprechender Support "erwartungskonform" wäre und dort nur eine Kontaktmöglichkeit vorhanden ist, die nicht klar als solche bezeichnet ist. 

Ich schließe den Issue und nehme da jetzt für mich mit, dass wir diese Anforderung nur dann prüfen, wenn der Kontakt unmissverständlich als ein Support i. S. der Anforderung ausgezeichnet ist.
