### ISSUE TITLE
9.1.4.11 Ergänzung für Styleswitcher

### ISSUE THREAD

**Issue by CarstenKaul** [BIK-BITV/BIK-Web-Test#80]
Man sollte auch hier in den Erläuterungen nochmal erwähnen, dass grafische Bedienelemente, die als Kontrast-Styleswitcher eingesetzt werden 4,5:1 erfüllen müssen. Zumindest dann, wenn diese Funktion bei 1.4.3 berücksichtigt werden soll.

**Comment by johannesFischer84** [comment]
Carsten, es kommt darauf an, ob der Kontrastumschalter selbst Text ist oder eine Grafik. Darüber wurde/wird auch in Issue #13 ausführlich diskutiert.

**Comment by CarstenKaul** [comment]
Danke für den Verweis auf die bestehende Diskussion. Genau das hatte ich gesucht.  
Natürlich betrifft die Ausnahme nur Grafiken, deshalb habe ich ja auch extra "grafische Bedienelemente" geschrieben ;)
*closed*
